import type { CorpQuestionSeed } from "./types";

export const QUESTIONS_P1: CorpQuestionSeed[] = [
  // ── Estratégia de IA ────────────────────────────────────────────────────────
  {
    domainSlug: "estrategia-ia",
    order: 1,
    text: "A organização possui uma estratégia de IA formalmente documentada e aprovada pela alta gestão?",
    description: "Avalia a existência de um documento estratégico de IA com objetivos, escopo e horizonte temporal aprovado pela liderança executiva.",
    objective: "Verificar a formalização e o patrocínio executivo da estratégia de IA.",
    justification: "Sem uma estratégia formal, iniciativas de IA tendem a ser pontuais, descoordenadas e desalinhadas do negócio, dificultando a captura de valor.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; Gartner AI Maturity Model",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "estrategia-ia",
    order: 2,
    text: "Em que grau a estratégia de IA está alinhada aos objetivos estratégicos corporativos e ao planejamento de negócio?",
    description: "Mede o nível de integração entre a estratégia de IA e o plano estratégico corporativo e as metas de negócio.",
    objective: "Avaliar o alinhamento entre iniciativas de IA e a direção estratégica da organização.",
    justification: "O alinhamento estratégico garante que a IA priorize problemas de alto valor e evite investimentos desconexos do negócio.",
    marketReference: "COBIT 2019; Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 3,
    text: "Existe um executivo (C-level) formalmente responsável por patrocinar e liderar a agenda de IA?",
    description: "Verifica a existência de um patrocinador executivo com mandato claro sobre a agenda de IA.",
    objective: "Identificar o patrocínio e a accountability executiva sobre IA.",
    justification: "O patrocínio de C-level assegura recursos, prioridade e remoção de barreiras organizacionais para a IA.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 4,
    text: "Qual o horizonte de planejamento da estratégia de IA da organização?",
    description: "Avalia se a estratégia de IA contempla horizontes de curto, médio e longo prazo.",
    objective: "Verificar a maturidade do planejamento temporal da estratégia de IA.",
    justification: "Um horizonte de planejamento estruturado sustenta investimentos consistentes e evolução progressiva das capacidades de IA.",
    marketReference: "Gartner AI Maturity Model; TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Não há horizonte definido",
      "Apenas curto prazo (até 1 ano)",
      "Curto e médio prazo (1 a 3 anos)",
      "Curto, médio e longo prazo (acima de 3 anos)",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 5,
    text: "A organização definiu indicadores estratégicos (KPIs) para medir o sucesso das iniciativas de IA?",
    description: "Avalia a existência de métricas estratégicas que conectam a IA a resultados de negócio.",
    objective: "Medir a capacidade de acompanhar o valor estratégico gerado pela IA.",
    justification: "KPIs estratégicos permitem demonstrar valor, sustentar investimentos e corrigir rumos das iniciativas de IA.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 6,
    text: "Existe orçamento dedicado e recorrente para iniciativas de IA?",
    description: "Verifica a alocação orçamentária formal e recorrente destinada à IA.",
    objective: "Avaliar a sustentabilidade financeira da agenda de IA.",
    justification: "Orçamento recorrente é condição para escalar iniciativas além de experimentos e sustentar capacidades ao longo do tempo.",
    marketReference: "FinOps Foundation; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 7,
    text: "Em que grau a estratégia de IA considera o posicionamento competitivo e as tendências de mercado do setor?",
    description: "Mede se a estratégia de IA incorpora análise competitiva e tendências setoriais.",
    objective: "Avaliar a consciência competitiva e de mercado embutida na estratégia de IA.",
    justification: "Considerar o contexto competitivo evita que a organização perca relevância frente a concorrentes que adotam IA de forma agressiva.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 8,
    text: "A estratégia de IA é revisada e atualizada periodicamente?",
    description: "Avalia a existência de um ciclo formal de revisão da estratégia de IA.",
    objective: "Verificar a adaptabilidade e a atualidade da estratégia de IA.",
    justification: "Dada a rápida evolução tecnológica, uma estratégia estática torna-se obsoleta e desalinhada das oportunidades emergentes.",
    marketReference: "ISO/IEC 42001; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 9,
    text: "Qual o percentual das áreas de negócio que possuem iniciativas de IA vinculadas à estratégia corporativa?",
    description: "Mede a abrangência da adoção estratégica de IA entre as áreas de negócio.",
    objective: "Quantificar o alcance organizacional da estratégia de IA.",
    justification: "Uma adoção ampla indica maturidade e reduz o risco de a IA ficar restrita a silos isolados.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 10,
    text: "A estratégia de IA define claramente os casos de uso prioritários e critérios de priorização?",
    description: "Verifica a existência de critérios objetivos para priorização de casos de uso de IA.",
    objective: "Avaliar a disciplina de priorização de iniciativas de IA.",
    justification: "Critérios claros de priorização otimizam o uso de recursos escassos e maximizam o retorno das iniciativas.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 11,
    text: "A organização definiu uma visão sobre o modelo de operação de IA (centralizado, federado ou híbrido)?",
    description: "Avalia a definição do modelo operacional que sustenta a execução da estratégia de IA.",
    objective: "Verificar a clareza sobre a estrutura operacional para entregar IA.",
    justification: "Um modelo operacional definido evita duplicação de esforços e conflitos de responsabilidade entre áreas.",
    marketReference: "TOGAF; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Não há modelo definido",
      "Centralizado (CoE único)",
      "Federado (por unidade de negócio)",
      "Híbrido (CoE + times distribuídos)",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 12,
    text: "A estratégia de IA contempla explicitamente o uso de IA generativa e modelos de linguagem?",
    description: "Verifica se a estratégia aborda oportunidades e riscos específicos de IA generativa.",
    objective: "Avaliar a atualização da estratégia frente às tecnologias generativas.",
    justification: "A IA generativa traz oportunidades e riscos distintos que exigem posicionamento estratégico explícito.",
    marketReference: "Gartner AI Maturity Model; OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 13,
    text: "Em que grau a estratégia de IA é comunicada e compreendida pelos colaboradores da organização?",
    description: "Mede o nível de disseminação e compreensão da estratégia de IA entre as equipes.",
    objective: "Avaliar a efetividade da comunicação da estratégia de IA.",
    justification: "Uma estratégia bem comunicada mobiliza as equipes e aumenta o engajamento na execução das iniciativas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 14,
    text: "A estratégia de IA está integrada à estratégia de dados da organização?",
    description: "Avalia o grau de integração entre a estratégia de IA e a estratégia de dados corporativa.",
    objective: "Verificar a coerência entre as agendas de dados e de IA.",
    justification: "Sem dados de qualidade e governados, a estratégia de IA não se sustenta; a integração é fundamental para o sucesso.",
    marketReference: "DAMA-DMBOK; Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "estrategia-ia",
    order: 15,
    text: "Descreva os principais objetivos estratégicos que a organização busca alcançar com IA nos próximos anos.",
    description: "Coleta qualitativa dos objetivos estratégicos prioritários associados à IA.",
    objective: "Compreender a intenção estratégica e as ambições da organização com IA.",
    justification: "A articulação dos objetivos revela a maturidade da visão e serve de base para avaliar o alinhamento das demais dimensões.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Governança de IA ────────────────────────────────────────────────────────
  {
    domainSlug: "governanca-ia",
    order: 1,
    text: "Existe um comitê ou fórum formal responsável pela governança de IA na organização?",
    description: "Verifica a existência de uma estrutura de governança formal dedicada à IA com mandato definido.",
    objective: "Avaliar a formalização da estrutura de governança de IA.",
    justification: "Um comitê formal assegura supervisão, tomada de decisão estruturada e accountability sobre o uso de IA.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; ISO/IEC 42001",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "governanca-ia",
    order: 2,
    text: "Papéis e responsabilidades relacionados à IA estão claramente definidos e atribuídos?",
    description: "Avalia a definição de papéis, responsabilidades e accountability (ex.: modelo RACI) para atividades de IA.",
    objective: "Verificar a clareza de responsabilidades na governança de IA.",
    justification: "Responsabilidades ambíguas geram lacunas de controle e dificultam a gestão de riscos e a conformidade.",
    marketReference: "ISO/IEC 42001; COBIT 2019",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 3,
    text: "A organização mantém um inventário atualizado de todos os sistemas e modelos de IA em uso?",
    description: "Verifica a existência de um inventário centralizado e atualizado de sistemas de IA.",
    objective: "Avaliar a visibilidade e o controle sobre o portfólio de IA em operação.",
    justification: "Sem inventário, a organização não consegue governar, auditar nem avaliar riscos dos sistemas de IA que utiliza.",
    marketReference: "ISO/IEC 42001; EU AI Act; NIST AI RMF 1.0 — MAP",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "governanca-ia",
    order: 4,
    text: "Em que grau a governança de IA está integrada às estruturas de governança corporativa existentes?",
    description: "Mede o nível de integração da governança de IA com governança de TI, riscos e compliance.",
    objective: "Avaliar a integração da governança de IA ao ecossistema de governança corporativa.",
    justification: "A integração evita silos, aproveita controles existentes e garante consistência na supervisão organizacional.",
    marketReference: "COBIT 2019; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 5,
    text: "Existem critérios formais de aprovação (gates) para a entrada de sistemas de IA em produção?",
    description: "Avalia a existência de pontos de controle e aprovações formais antes da produtização de modelos.",
    objective: "Verificar a existência de controles de aprovação no ciclo de vida da IA.",
    justification: "Gates de aprovação reduzem o risco de colocar em produção sistemas inadequados, inseguros ou não conformes.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MANAGE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 6,
    text: "Com que frequência o comitê de governança de IA se reúne para deliberar sobre a agenda de IA?",
    description: "Avalia a periodicidade e a regularidade das reuniões de governança de IA.",
    objective: "Medir a atividade e a operacionalidade da estrutura de governança.",
    justification: "Reuniões regulares indicam uma governança ativa e capaz de responder tempestivamente a riscos e demandas.",
    marketReference: "COBIT 2019; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Não há reuniões regulares",
      "Anualmente ou de forma esporádica",
      "Trimestralmente",
      "Mensalmente ou com maior frequência",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 7,
    text: "A governança de IA classifica os sistemas por nível de risco (ex.: risco inaceitável, alto, limitado, mínimo)?",
    description: "Verifica a adoção de uma abordagem baseada em risco para governar sistemas de IA.",
    objective: "Avaliar a existência de classificação de risco dos sistemas de IA.",
    justification: "A classificação por risco permite alocar controles proporcionais e atende exigências regulatórias emergentes.",
    marketReference: "EU AI Act; NIST AI RMF 1.0 — MAP",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 8,
    text: "Existe um processo formal de auditoria interna sobre sistemas e práticas de IA?",
    description: "Avalia a existência de auditoria interna cobrindo controles, riscos e conformidade de IA.",
    objective: "Verificar a maturidade da terceira linha de defesa sobre IA.",
    justification: "A auditoria independente valida a efetividade dos controles e reforça a confiança na governança de IA.",
    marketReference: "COBIT 2019; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 9,
    text: "Qual o percentual dos sistemas de IA em produção que estão registrados no inventário e sob governança formal?",
    description: "Mede a cobertura da governança formal sobre os sistemas de IA em operação.",
    objective: "Quantificar a abrangência da governança de IA.",
    justification: "Sistemas fora da governança representam risco oculto (shadow AI) e potenciais violações não monitoradas.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MAP",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 10,
    text: "A governança de IA adota um modelo de três linhas de defesa (áreas de negócio, riscos/compliance, auditoria)?",
    description: "Avalia a aplicação do modelo de três linhas de defesa à governança de IA.",
    objective: "Verificar a estrutura de controles e segregação de funções na governança de IA.",
    justification: "O modelo de três linhas estabelece camadas independentes de controle e reduz conflitos de interesse.",
    marketReference: "COBIT 2019; IIA Three Lines Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 11,
    text: "Existem mecanismos para identificar e controlar o uso não autorizado de IA (shadow AI)?",
    description: "Verifica a existência de controles para detectar uso de ferramentas de IA fora da governança.",
    objective: "Avaliar a capacidade de mitigar riscos de shadow AI.",
    justification: "O uso não governado de IA expõe a organização a vazamentos de dados e a decisões sem controle de qualidade.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 12,
    text: "A governança de IA define claramente a documentação mínima obrigatória por sistema (ex.: model card, ficha de risco)?",
    description: "Avalia a exigência de documentação padronizada para cada sistema de IA.",
    objective: "Verificar a padronização da documentação de governança dos sistemas de IA.",
    justification: "Documentação consistente sustenta auditabilidade, transparência e continuidade do conhecimento sobre os sistemas.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MAP",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 13,
    text: "Em que grau as decisões da governança de IA são registradas e rastreáveis?",
    description: "Mede a rastreabilidade e o registro formal das deliberações de governança de IA.",
    objective: "Avaliar a auditabilidade das decisões de governança de IA.",
    justification: "O registro das decisões garante prestação de contas e evidências para auditorias e reguladores.",
    marketReference: "COBIT 2019; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 14,
    text: "A governança de IA abrange também soluções de IA fornecidas por terceiros e em SaaS?",
    description: "Verifica se a governança cobre IA embarcada em produtos de fornecedores e serviços em nuvem.",
    objective: "Avaliar a abrangência da governança sobre IA de terceiros.",
    justification: "IA de terceiros pode introduzir riscos não controlados; sua governança é essencial para uma visão completa.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-ia",
    order: 15,
    text: "A organização define métricas e reporta periodicamente indicadores de governança de IA à alta gestão?",
    description: "Avalia a existência de reporte estruturado de indicadores de governança de IA para a liderança.",
    objective: "Verificar a prestação de contas da governança de IA à alta gestão.",
    justification: "O reporte periódico mantém a liderança informada sobre riscos e desempenho, sustentando decisões estratégicas.",
    marketReference: "COBIT 2019; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Políticas e Normas de IA ────────────────────────────────────────────────
  {
    domainSlug: "politicas-normas",
    order: 1,
    text: "A organização possui uma política corporativa formal de uso responsável de IA?",
    description: "Verifica a existência de uma política formal aprovada que estabeleça diretrizes de uso de IA.",
    objective: "Avaliar a formalização de diretrizes corporativas para IA.",
    justification: "Uma política formal estabelece limites, princípios e expectativas, reduzindo riscos legais, éticos e operacionais.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "politicas-normas",
    order: 2,
    text: "Em que grau as políticas de IA são de conhecimento e efetivamente aplicadas pelas equipes?",
    description: "Mede o nível de disseminação e aplicação prática das políticas de IA na organização.",
    objective: "Avaliar a efetividade da adoção das políticas de IA.",
    justification: "Políticas não conhecidas ou não aplicadas são ineficazes e não mitigam os riscos que se propõem a controlar.",
    marketReference: "ISO/IEC 42001; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 3,
    text: "Existe uma política ou norma específica para o uso de IA generativa e ferramentas públicas de LLM?",
    description: "Verifica a existência de diretrizes específicas para uso de ferramentas de IA generativa pelos colaboradores.",
    objective: "Avaliar a cobertura normativa sobre IA generativa.",
    justification: "O uso de ferramentas públicas de LLM sem diretrizes pode expor dados sensíveis e violar sigilo e conformidade.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 42001; LGPD Art. 46",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 4,
    text: "As políticas de IA definem critérios claros sobre uso aceitável e casos de uso proibidos?",
    description: "Avalia se as políticas especificam usos permitidos, restritos e vedados de IA.",
    objective: "Verificar a clareza dos limites de uso estabelecidos pelas políticas.",
    justification: "Limites claros evitam usos indevidos que possam gerar danos reputacionais, legais ou a clientes.",
    marketReference: "ISO/IEC 42001; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 5,
    text: "As políticas de IA são revisadas e atualizadas em intervalos definidos?",
    description: "Verifica a existência de um ciclo formal de revisão e atualização das políticas de IA.",
    objective: "Avaliar a manutenção e a atualidade do arcabouço normativo de IA.",
    justification: "Diante da rápida evolução tecnológica e regulatória, políticas desatualizadas perdem aderência e eficácia.",
    marketReference: "ISO/IEC 42001; COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 6,
    text: "Qual o nível de abrangência das normas de IA na organização?",
    description: "Avalia se as normas cobrem desenvolvimento, aquisição, uso, monitoramento e descomissionamento de IA.",
    objective: "Verificar a cobertura do arcabouço normativo ao longo do ciclo de vida da IA.",
    justification: "Normas abrangentes garantem consistência de controles em todas as fases do ciclo de vida dos sistemas de IA.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Não há normas formais",
      "Cobrem apenas desenvolvimento interno",
      "Cobrem desenvolvimento e uso",
      "Cobrem todo o ciclo de vida, incluindo terceiros",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 7,
    text: "Existem consequências e mecanismos disciplinares definidos para violações das políticas de IA?",
    description: "Verifica a existência de sanções formais associadas ao descumprimento das políticas de IA.",
    objective: "Avaliar a exequibilidade e o enforcement das políticas de IA.",
    justification: "Sem consequências definidas, as políticas perdem força coercitiva e tendem a ser negligenciadas.",
    marketReference: "ISO/IEC 27001; COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 8,
    text: "As políticas de IA foram elaboradas com participação de áreas de jurídico, compliance, riscos e segurança?",
    description: "Avalia a multidisciplinaridade na construção das políticas de IA.",
    objective: "Verificar a robustez e a abrangência das políticas quanto às diferentes perspectivas de risco.",
    justification: "A colaboração multidisciplinar garante que as políticas cubram aspectos legais, de risco e de segurança de forma equilibrada.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 9,
    text: "Qual o percentual de colaboradores que formalmente tomaram ciência das políticas de IA?",
    description: "Mede a cobertura do aceite formal das políticas de IA entre os colaboradores.",
    objective: "Quantificar a adesão formal às políticas de IA.",
    justification: "A ciência formal é evidência de conformidade e reforça a responsabilização individual sobre o uso de IA.",
    marketReference: "ISO/IEC 27001; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 10,
    text: "Existem padrões técnicos (standards) definidos para desenvolvimento e documentação de modelos de IA?",
    description: "Verifica a existência de padrões técnicos e templates para desenvolvimento e documentação de modelos.",
    objective: "Avaliar a padronização técnica no desenvolvimento de IA.",
    justification: "Padrões técnicos aumentam qualidade, reprodutibilidade e reduzem risco operacional no desenvolvimento de modelos.",
    marketReference: "ISO/IEC 42001; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 11,
    text: "As políticas de IA estão alinhadas às demais políticas corporativas (segurança, privacidade, ética, conduta)?",
    description: "Avalia a consistência das políticas de IA com o corpo normativo corporativo existente.",
    objective: "Verificar a coerência entre as políticas de IA e as demais políticas da organização.",
    justification: "Políticas conflitantes geram insegurança jurídica e dificuldades de aplicação pelas equipes.",
    marketReference: "ISO/IEC 27001; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 12,
    text: "Existe uma política específica para aquisição e contratação de soluções de IA de terceiros?",
    description: "Verifica a existência de diretrizes normativas para compra e contratação de soluções de IA externas.",
    objective: "Avaliar a cobertura normativa sobre aquisição de IA de terceiros.",
    justification: "Diretrizes de aquisição mitigam riscos de fornecedores e asseguram due diligence adequado antes da contratação.",
    marketReference: "ISO/IEC 42001; COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 13,
    text: "As políticas de IA estabelecem diretrizes sobre classificação e manuseio de dados usados em modelos?",
    description: "Avalia se as políticas orientam o tratamento de dados conforme sua classificação de sensibilidade em contextos de IA.",
    objective: "Verificar a integração entre políticas de IA e classificação de dados.",
    justification: "O uso inadequado de dados sensíveis em IA pode violar a LGPD e gerar exposição significativa.",
    marketReference: "LGPD Art. 46; ISO/IEC 27001; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 14,
    text: "Em que grau as políticas de IA são acessíveis e de fácil consulta pelos colaboradores?",
    description: "Mede a disponibilidade e a facilidade de acesso às políticas de IA pelas equipes.",
    objective: "Avaliar a acessibilidade prática do arcabouço normativo de IA.",
    justification: "Políticas de difícil acesso reduzem a adesão e comprometem a efetividade das diretrizes.",
    marketReference: "ISO/IEC 42001",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "politicas-normas",
    order: 15,
    text: "Descreva quais políticas e normas de IA já estão formalizadas e quais estão em desenvolvimento.",
    description: "Coleta qualitativa do status do arcabouço normativo de IA da organização.",
    objective: "Mapear a cobertura atual e as lacunas do arcabouço normativo de IA.",
    justification: "O mapeamento evidencia o grau de maturidade normativa e orienta prioridades de formalização.",
    marketReference: "ISO/IEC 42001",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Gestão de Riscos de IA ──────────────────────────────────────────────────
  {
    domainSlug: "gestao-riscos-ia",
    order: 1,
    text: "A organização possui um processo formal de identificação e avaliação de riscos específicos de IA?",
    description: "Verifica a existência de um processo estruturado para identificar e avaliar riscos próprios de sistemas de IA.",
    objective: "Avaliar a formalização da gestão de riscos de IA.",
    justification: "Sem um processo formal, riscos como viés, alucinação, drift e ataques adversariais passam despercebidos.",
    marketReference: "NIST AI RMF 1.0 — MAP/MEASURE; ISO/IEC 23894",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 2,
    text: "Em que grau os riscos de IA estão integrados ao framework corporativo de gestão de riscos (ERM)?",
    description: "Mede a integração dos riscos de IA ao processo de gestão de riscos corporativa.",
    objective: "Avaliar a integração dos riscos de IA ao ERM.",
    justification: "A integração ao ERM garante visão consolidada de riscos e priorização adequada de mitigações.",
    marketReference: "ISO/IEC 23894; COSO ERM; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 3,
    text: "Existe uma metodologia formal de classificação e priorização de riscos de IA (ex.: probabilidade x impacto)?",
    description: "Avalia a existência de critérios objetivos para classificar e priorizar riscos de IA.",
    objective: "Verificar a estruturação metodológica da avaliação de riscos de IA.",
    justification: "Uma metodologia consistente permite alocar recursos de mitigação de forma proporcional ao risco.",
    marketReference: "ISO/IEC 23894; NIST AI RMF 1.0 — MEASURE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 4,
    text: "A organização mantém um registro (matriz) de riscos de IA atualizado com planos de tratamento?",
    description: "Verifica a existência de uma matriz de riscos de IA com ações de mitigação e responsáveis.",
    objective: "Avaliar a gestão contínua e documentada dos riscos de IA.",
    justification: "Um registro atualizado assegura acompanhamento, accountability e evidência para auditorias.",
    marketReference: "ISO/IEC 23894; COBIT 2019",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 5,
    text: "Os riscos específicos de IA generativa (alucinação, vazamento, prompt injection) são avaliados formalmente?",
    description: "Avalia se a gestão de riscos contempla ameaças específicas de modelos generativos e LLMs.",
    objective: "Verificar a cobertura de riscos próprios de IA generativa.",
    justification: "A IA generativa introduz riscos distintos que, se não avaliados, podem gerar danos a clientes e à reputação.",
    marketReference: "OWASP Top 10 for LLM; MITRE ATLAS",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 6,
    text: "Qual o nível de maturidade do monitoramento contínuo de riscos de IA em produção?",
    description: "Avalia a capacidade de monitorar riscos ao longo da operação dos sistemas de IA.",
    objective: "Medir a maturidade do monitoramento contínuo de riscos de IA.",
    justification: "Riscos de IA evoluem com o tempo (drift, novos ataques); o monitoramento contínuo é essencial para mitigá-los.",
    marketReference: "NIST AI RMF 1.0 — MANAGE; ISO/IEC 23894",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 7,
    text: "A organização define apetite e tolerância a risco específicos para iniciativas de IA?",
    description: "Verifica a existência de declaração formal de apetite e tolerância a risco para IA.",
    objective: "Avaliar a definição de limites de risco aceitáveis para IA.",
    justification: "O apetite a risco orienta decisões de investimento e mitigação, evitando exposição indevida.",
    marketReference: "ISO/IEC 23894; COSO ERM",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 8,
    text: "Qual abordagem a organização adota para tratar os riscos de IA identificados?",
    description: "Avalia as estratégias predominantes de tratamento de risco (mitigar, transferir, aceitar, evitar).",
    objective: "Verificar as estratégias de tratamento de riscos de IA utilizadas.",
    justification: "A escolha consciente da estratégia de tratamento demonstra maturidade e otimiza o uso de recursos.",
    marketReference: "ISO/IEC 23894; ISO 31000",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Não há tratamento estruturado",
      "Predominantemente aceitação informal",
      "Mitigação com controles definidos",
      "Combinação estruturada de mitigar, transferir, evitar e aceitar",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 9,
    text: "Qual o percentual dos sistemas de IA em produção que passaram por avaliação formal de riscos?",
    description: "Mede a cobertura da avaliação de riscos sobre o portfólio de IA em operação.",
    objective: "Quantificar a abrangência da avaliação de riscos de IA.",
    justification: "Sistemas sem avaliação de risco representam exposição não gerenciada à organização.",
    marketReference: "NIST AI RMF 1.0 — MAP; ISO/IEC 23894",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 10,
    text: "A gestão de riscos de IA considera riscos de terceiros e da cadeia de suprimentos de IA?",
    description: "Avalia se a gestão de riscos cobre modelos, dados e componentes fornecidos por terceiros.",
    objective: "Verificar a cobertura de riscos da cadeia de suprimentos de IA.",
    justification: "Dependências de terceiros (modelos de fundação, APIs, datasets) podem introduzir riscos significativos e ocultos.",
    marketReference: "NIST AI RMF 1.0 — MAP; MITRE ATLAS",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 11,
    text: "Existem indicadores-chave de risco (KRIs) definidos e monitorados para sistemas de IA?",
    description: "Verifica a existência de KRIs para acompanhar a evolução dos riscos de IA.",
    objective: "Avaliar a mensuração quantitativa dos riscos de IA.",
    justification: "KRIs permitem detecção precoce de deterioração de risco e acionamento tempestivo de mitigações.",
    marketReference: "ISO/IEC 23894; NIST AI RMF 1.0 — MEASURE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 12,
    text: "A organização realiza avaliação de impacto de IA (AIA) para sistemas de alto risco?",
    description: "Verifica a realização de avaliações de impacto para sistemas de IA classificados como de alto risco.",
    objective: "Avaliar a adoção de avaliações de impacto para IA de alto risco.",
    justification: "Avaliações de impacto antecipam danos a direitos e ao negócio e atendem exigências regulatórias emergentes.",
    marketReference: "EU AI Act; ISO/IEC 42005; LGPD Art. 38",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 13,
    text: "Em que grau os riscos de IA são reportados periodicamente ao comitê de riscos ou à alta gestão?",
    description: "Mede a frequência e a estrutura do reporte de riscos de IA às instâncias superiores.",
    objective: "Avaliar a comunicação de riscos de IA à governança.",
    justification: "O reporte estruturado assegura que a liderança tome decisões informadas sobre exposição a riscos de IA.",
    marketReference: "COSO ERM; COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 14,
    text: "A organização considera riscos sistêmicos e de concentração ao depender de poucos provedores de IA?",
    description: "Avalia a consideração de riscos de concentração e dependência de provedores de modelos de fundação.",
    objective: "Verificar a atenção a riscos sistêmicos na estratégia de fornecedores de IA.",
    justification: "A dependência excessiva de poucos provedores expõe a organização a riscos de continuidade e de custo.",
    marketReference: "BACEN Res. 4.893; NIST AI RMF 1.0 — MAP",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-riscos-ia",
    order: 15,
    text: "A gestão de riscos de IA está articulada com as áreas de segurança da informação e continuidade de negócio?",
    description: "Avalia a integração entre a gestão de riscos de IA, a segurança da informação e a continuidade de negócio.",
    objective: "Verificar a coordenação entre riscos de IA e demais funções de risco.",
    justification: "A articulação evita lacunas de controle e assegura resposta coordenada a incidentes envolvendo IA.",
    marketReference: "ISO/IEC 27001; ISO 22301; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Compliance Regulatório ──────────────────────────────────────────────────
  {
    domainSlug: "compliance-regulatorio",
    order: 1,
    text: "A organização mapeia formalmente as regulamentações aplicáveis ao uso de IA em suas operações?",
    description: "Verifica a existência de um mapeamento atualizado das normas e regulamentações incidentes sobre IA.",
    objective: "Avaliar o conhecimento formal do arcabouço regulatório aplicável à IA.",
    justification: "Sem mapear as exigências aplicáveis, a organização fica exposta a sanções, multas e restrições operacionais.",
    marketReference: "LGPD; EU AI Act; BACEN Res. 4.893",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 2,
    text: "Em que grau os sistemas de IA estão em conformidade com a LGPD no tratamento de dados pessoais?",
    description: "Mede o nível de aderência dos sistemas de IA às exigências da LGPD.",
    objective: "Avaliar a conformidade dos sistemas de IA com a legislação de proteção de dados.",
    justification: "O uso de dados pessoais em IA sem conformidade com a LGPD pode gerar multas e responsabilização significativa.",
    marketReference: "LGPD Art. 6, 20 e 46; ANPD",
    criticality: "critica",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 3,
    text: "Existe um processo formal de monitoramento de mudanças regulatórias relacionadas a IA?",
    description: "Verifica a existência de acompanhamento estruturado da evolução regulatória sobre IA (horizon scanning).",
    objective: "Avaliar a capacidade de antecipar e responder a mudanças regulatórias.",
    justification: "O ambiente regulatório de IA evolui rapidamente; o monitoramento evita não conformidades por defasagem.",
    marketReference: "EU AI Act; BACEN; ANPD",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 4,
    text: "A organização atende às exigências regulatórias setoriais aplicáveis (ex.: BACEN, CMN, SUSEP) no uso de IA?",
    description: "Avalia a conformidade com regulamentações setoriais específicas do segmento de atuação.",
    objective: "Verificar a aderência às normas setoriais aplicáveis ao uso de IA.",
    justification: "Setores regulados como bancos e seguradoras possuem exigências específicas cujo descumprimento gera severas penalidades.",
    marketReference: "BACEN Res. 4.893; CMN; SUSEP",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 5,
    text: "A organização avalia a aplicabilidade e os impactos do EU AI Act sobre suas operações e produtos?",
    description: "Verifica a consideração das exigências do EU AI Act, especialmente para operações internacionais.",
    objective: "Avaliar a preparação para o marco regulatório europeu de IA.",
    justification: "O EU AI Act tem alcance extraterritorial e classifica sistemas por risco, exigindo controles específicos.",
    marketReference: "EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 6,
    text: "Qual o percentual dos sistemas de IA que possuem avaliação documentada de conformidade regulatória?",
    description: "Mede a cobertura de avaliações de conformidade sobre o portfólio de sistemas de IA.",
    objective: "Quantificar a abrangência da avaliação de conformidade regulatória de IA.",
    justification: "Sistemas sem avaliação de conformidade representam risco jurídico e regulatório não gerenciado.",
    marketReference: "EU AI Act; LGPD",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 7,
    text: "Existe articulação formal entre as áreas de compliance, jurídico e as equipes de IA?",
    description: "Avalia a integração entre as funções de compliance e jurídico e os times técnicos de IA.",
    objective: "Verificar a colaboração entre compliance, jurídico e IA.",
    justification: "A colaboração antecipa questões legais no desenho dos sistemas, reduzindo retrabalho e riscos de não conformidade.",
    marketReference: "COBIT 2019; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 8,
    text: "A organização mantém evidências e trilhas de auditoria suficientes para demonstrar conformidade a reguladores?",
    description: "Verifica a existência de documentação e trilhas de auditoria que sustentem demonstrações de conformidade.",
    objective: "Avaliar a auditabilidade e a capacidade de comprovação de conformidade.",
    justification: "A ausência de evidências dificulta a defesa perante reguladores e pode agravar penalidades em fiscalizações.",
    marketReference: "LGPD Art. 37; ISO/IEC 27001; BACEN Res. 4.893",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 9,
    text: "Como a organização classifica seu nível geral de maturidade em compliance regulatório de IA?",
    description: "Avalia a autopercepção da organização quanto à sua maturidade em conformidade regulatória de IA.",
    objective: "Verificar a percepção da maturidade de compliance de IA.",
    justification: "A autoavaliação ajuda a calibrar expectativas e a identificar lacunas percebidas frente à realidade dos controles.",
    marketReference: "EU AI Act; LGPD; BACEN",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Inexistente ou ad hoc",
      "Reativo, atendendo apenas exigências pontuais",
      "Estruturado, com processos definidos",
      "Proativo e integrado à gestão de riscos",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 10,
    text: "Os contratos com fornecedores de IA contemplam cláusulas de conformidade regulatória e responsabilização?",
    description: "Verifica a presença de cláusulas contratuais que assegurem conformidade e responsabilidade dos fornecedores.",
    objective: "Avaliar a proteção contratual quanto à conformidade regulatória de IA de terceiros.",
    justification: "Cláusulas adequadas transferem e delimitam responsabilidades, protegendo a organização em caso de não conformidade do fornecedor.",
    marketReference: "LGPD Art. 39; BACEN Res. 4.893",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 11,
    text: "A organização realiza Relatório de Impacto à Proteção de Dados (RIPD/DPIA) para sistemas de IA que tratam dados pessoais?",
    description: "Verifica a elaboração de RIPD para sistemas de IA com tratamento de dados pessoais sensíveis ou em larga escala.",
    objective: "Avaliar a adoção de RIPD em sistemas de IA sob a LGPD.",
    justification: "O RIPD é instrumento previsto na LGPD e demonstra diligência no tratamento de dados de alto risco.",
    marketReference: "LGPD Art. 38; ANPD",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 12,
    text: "Em que grau a organização está preparada para responder a fiscalizações e requisições de reguladores sobre IA?",
    description: "Avalia a prontidão para atender demandas de reguladores relacionadas a sistemas de IA.",
    objective: "Verificar a capacidade de resposta a fiscalizações regulatórias sobre IA.",
    justification: "A prontidão reduz o risco de sanções e demonstra maturidade e cooperação com os órgãos reguladores.",
    marketReference: "ANPD; BACEN; SUSEP",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 13,
    text: "A organização considera exigências de conformidade sobre decisões automatizadas e direito à revisão pelo titular?",
    description: "Avalia o atendimento ao direito de revisão de decisões automatizadas previsto na LGPD.",
    objective: "Verificar a conformidade quanto a decisões automatizadas e direitos dos titulares.",
    justification: "A LGPD assegura ao titular a revisão de decisões automatizadas; o não atendimento gera risco legal e reputacional.",
    marketReference: "LGPD Art. 20; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 14,
    text: "Existe um responsável formalmente designado pela conformidade regulatória das iniciativas de IA?",
    description: "Verifica a designação de accountability específica para conformidade regulatória de IA.",
    objective: "Avaliar a responsabilização formal pela conformidade de IA.",
    justification: "Uma responsabilidade clara evita lacunas de conformidade e assegura acompanhamento contínuo das obrigações.",
    marketReference: "LGPD Art. 41; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "compliance-regulatorio",
    order: 15,
    text: "Descreva as principais lacunas de conformidade regulatória de IA identificadas pela organização.",
    description: "Coleta qualitativa das lacunas de conformidade regulatória percebidas pela organização.",
    objective: "Mapear as lacunas de conformidade regulatória de IA conhecidas.",
    justification: "A identificação das lacunas evidencia maturidade de compliance e orienta os planos de remediação.",
    marketReference: "LGPD; EU AI Act; BACEN",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Ética e IA Responsável ──────────────────────────────────────────────────
  {
    domainSlug: "etica-ia",
    order: 1,
    text: "A organização possui princípios éticos formalmente definidos para o desenvolvimento e uso de IA?",
    description: "Verifica a existência de princípios éticos documentados que orientem as práticas de IA.",
    objective: "Avaliar a formalização de princípios de IA responsável.",
    justification: "Princípios éticos formais orientam decisões, previnem danos e sustentam a confiança de clientes e da sociedade.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; OCDE AI Principles; ISO/IEC 42001",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "etica-ia",
    order: 2,
    text: "Existe um processo formal para identificação e mitigação de viés em modelos de IA?",
    description: "Avalia a existência de processos para detectar e mitigar vieses discriminatórios em modelos.",
    objective: "Verificar a maturidade da gestão de viés e equidade em IA.",
    justification: "Vieses não tratados podem gerar decisões discriminatórias, danos a clientes e responsabilização legal.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 24027",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 3,
    text: "Os sistemas de IA que apoiam decisões relevantes mantêm supervisão humana significativa (human-in-the-loop)?",
    description: "Verifica a presença de supervisão humana em decisões de IA com impacto sobre pessoas.",
    objective: "Avaliar a existência de supervisão humana em decisões críticas de IA.",
    justification: "A supervisão humana previne danos por decisões automatizadas equivocadas e atende exigências regulatórias.",
    marketReference: "EU AI Act; NIST AI RMF 1.0 — GOVERN; LGPD Art. 20",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 4,
    text: "A organização avalia métricas de equidade (fairness) entre grupos demográficos nos modelos que afetam pessoas?",
    description: "Avalia o uso de métricas quantitativas de equidade para monitorar impactos entre grupos.",
    objective: "Verificar a mensuração de equidade nos modelos de IA.",
    justification: "Métricas de equidade permitem detectar tratamento desigual e comprovar diligência quanto à não discriminação.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 24027",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 5,
    text: "Existe um fórum ou comitê de ética para deliberar sobre dilemas e casos sensíveis de uso de IA?",
    description: "Verifica a existência de uma instância para avaliar dilemas éticos de casos de uso de IA.",
    objective: "Avaliar a estrutura de deliberação ética sobre IA.",
    justification: "Um fórum de ética assegura análise estruturada de casos sensíveis e reduz riscos reputacionais e sociais.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 6,
    text: "Os princípios éticos de IA são traduzidos em critérios práticos aplicados no ciclo de desenvolvimento?",
    description: "Avalia se os princípios éticos são operacionalizados em requisitos e critérios concretos no desenvolvimento.",
    objective: "Verificar a operacionalização prática dos princípios éticos de IA.",
    justification: "Princípios que não se traduzem em práticas concretas tornam-se declarações sem efeito real sobre os sistemas.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 7,
    text: "Qual o percentual de modelos que afetam clientes que passaram por avaliação formal de viés e equidade?",
    description: "Mede a cobertura de avaliações de viés e equidade sobre modelos que impactam clientes.",
    objective: "Quantificar a abrangência da avaliação de viés em modelos sensíveis.",
    justification: "Modelos sem avaliação de viés podem produzir discriminação sistemática não detectada, com alto risco associado.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 24027",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 8,
    text: "Qual o nível de maturidade da organização na abordagem de IA responsável?",
    description: "Avalia a autopercepção sobre a maturidade das práticas de IA responsável.",
    objective: "Verificar o estágio de maturidade percebido em IA responsável.",
    justification: "A autoavaliação orienta o planejamento de evolução e a priorização de investimentos em IA responsável.",
    marketReference: "NIST AI RMF 1.0; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Não há práticas de IA responsável",
      "Iniciativas isoladas e informais",
      "Práticas definidas e aplicadas em projetos-chave",
      "IA responsável integrada e monitorada em toda a organização",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 9,
    text: "A organização considera o impacto social e sobre grupos vulneráveis ao desenvolver sistemas de IA?",
    description: "Avalia a consideração de impactos sociais e sobre populações vulneráveis no desenho de IA.",
    objective: "Verificar a sensibilidade a impactos sociais nos sistemas de IA.",
    justification: "Ignorar impactos sobre grupos vulneráveis pode gerar danos sociais, reputacionais e questionamentos regulatórios.",
    marketReference: "OCDE AI Principles; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 10,
    text: "Existem diretrizes éticas específicas para o uso de IA generativa (autoria, desinformação, deepfakes)?",
    description: "Verifica a existência de diretrizes éticas voltadas a riscos específicos da IA generativa.",
    objective: "Avaliar a cobertura ética sobre riscos de IA generativa.",
    justification: "A IA generativa amplia riscos de desinformação e uso indevido, exigindo diretrizes éticas próprias.",
    marketReference: "OWASP Top 10 for LLM; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 11,
    text: "Colaboradores envolvidos em IA recebem treinamento sobre ética e IA responsável?",
    description: "Avalia a existência de capacitação em ética de IA para as equipes envolvidas.",
    objective: "Verificar a disseminação de competências em ética de IA.",
    justification: "O treinamento capacita as equipes a identificar e tratar dilemas éticos no dia a dia do desenvolvimento.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 12,
    text: "Existe um canal para que clientes ou colaboradores reportem preocupações éticas relacionadas a sistemas de IA?",
    description: "Verifica a existência de mecanismos de reporte de preocupações éticas sobre IA.",
    objective: "Avaliar a existência de canais de feedback sobre questões éticas de IA.",
    justification: "Canais de reporte permitem detectar e corrigir problemas éticos precocemente, reforçando a confiança dos stakeholders.",
    marketReference: "NIST AI RMF 1.0 — MANAGE; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 13,
    text: "Em que grau a diversidade das equipes é considerada para reduzir vieses no desenvolvimento de IA?",
    description: "Avalia a atenção à diversidade das equipes como fator de mitigação de viés.",
    objective: "Verificar a consideração da diversidade na composição de equipes de IA.",
    justification: "Equipes diversas ajudam a identificar vieses e pontos cegos que equipes homogêneas tendem a ignorar.",
    marketReference: "NIST AI RMF 1.0 — GOVERN",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 14,
    text: "A organização define limites claros para casos de uso de IA considerados eticamente inaceitáveis?",
    description: "Verifica a existência de vedações explícitas a usos de IA eticamente inaceitáveis.",
    objective: "Avaliar a definição de fronteiras éticas para o uso de IA.",
    justification: "Fronteiras éticas claras previnem usos que gerem danos significativos e protegem a reputação da organização.",
    marketReference: "EU AI Act; OCDE AI Principles",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "etica-ia",
    order: 15,
    text: "As decisões do comitê de ética de IA são documentadas e utilizadas para aprimorar práticas futuras?",
    description: "Avalia o registro e o aproveitamento das deliberações éticas para melhoria contínua.",
    objective: "Verificar a incorporação do aprendizado ético às práticas de IA.",
    justification: "Documentar e reaproveitar deliberações fortalece a consistência ética e a maturidade organizacional ao longo do tempo.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MANAGE",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Transparência e Explicabilidade ─────────────────────────────────────────
  {
    domainSlug: "transparencia-explicabilidade",
    order: 1,
    text: "A organização possui capacidade técnica de explicar as decisões geradas por seus modelos de IA?",
    description: "Verifica a existência de recursos e técnicas de explicabilidade (XAI) para interpretar decisões de modelos.",
    objective: "Avaliar a capacidade de explicabilidade dos modelos de IA.",
    justification: "A explicabilidade é essencial para auditar decisões, atender titulares e cumprir exigências regulatórias.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 42001; LGPD Art. 20",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 2,
    text: "Em que grau a organização informa clientes e usuários quando estão interagindo com um sistema de IA?",
    description: "Mede a transparência quanto ao uso de IA na interação com clientes e usuários.",
    objective: "Avaliar a transparência sobre o uso de IA junto aos usuários.",
    justification: "A comunicação clara sobre o uso de IA atende exigências regulatórias e preserva a confiança dos clientes.",
    marketReference: "EU AI Act; LGPD Art. 9",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 3,
    text: "Os modelos de IA possuem documentação padronizada (model cards) descrevendo finalidade, dados e limitações?",
    description: "Verifica a existência de documentação estruturada dos modelos, como model cards e fichas técnicas.",
    objective: "Avaliar a padronização da documentação de transparência dos modelos.",
    justification: "A documentação estruturada sustenta transparência, auditabilidade e continuidade do conhecimento sobre os modelos.",
    marketReference: "NIST AI RMF 1.0 — MAP; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 4,
    text: "A organização adota técnicas de explicabilidade (ex.: SHAP, LIME) para modelos complexos em produção?",
    description: "Avalia o uso de técnicas específicas de explicabilidade em modelos de alta complexidade.",
    objective: "Verificar a maturidade técnica na aplicação de métodos de XAI.",
    justification: "Técnicas de XAI tornam interpretáveis modelos complexos, viabilizando revisão e detecção de comportamentos indevidos.",
    marketReference: "NIST AI RMF 1.0 — MEASURE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 5,
    text: "A organização consegue fornecer justificativas compreensíveis a titulares que solicitem revisão de decisões automatizadas?",
    description: "Verifica a capacidade de explicar decisões automatizadas de forma acessível aos titulares.",
    objective: "Avaliar o atendimento ao direito de explicação de decisões automatizadas.",
    justification: "A LGPD assegura ao titular o direito à explicação; a incapacidade de atendê-lo gera risco legal e reputacional.",
    marketReference: "LGPD Art. 20; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 6,
    text: "Qual o percentual dos modelos de IA em produção que possuem documentação de transparência atualizada?",
    description: "Mede a cobertura de documentação de transparência sobre os modelos em operação.",
    objective: "Quantificar a abrangência da documentação de transparência de modelos.",
    justification: "Modelos sem documentação atualizada comprometem auditabilidade, conformidade e resposta a incidentes.",
    marketReference: "NIST AI RMF 1.0 — MAP; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 7,
    text: "Qual o nível de explicabilidade exigido pela organização ao selecionar ou desenvolver modelos de IA?",
    description: "Avalia se a explicabilidade é um critério considerado na escolha de abordagens e modelos de IA.",
    objective: "Verificar a priorização da explicabilidade nas decisões de arquitetura de modelos.",
    justification: "Equilibrar desempenho e explicabilidade é essencial em contextos regulados e de decisões sensíveis.",
    marketReference: "NIST AI RMF 1.0 — MAP; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: [
      "Explicabilidade não é considerada",
      "Considerada apenas em casos críticos",
      "Critério recomendado no desenvolvimento",
      "Requisito obrigatório e priorizado por nível de risco",
    ],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 8,
    text: "A organização mantém rastreabilidade da origem e do versionamento dos dados e modelos usados nas decisões?",
    description: "Avalia a capacidade de rastrear dados, versões de modelos e parâmetros associados a cada decisão.",
    objective: "Verificar a rastreabilidade que sustenta a transparência das decisões de IA.",
    justification: "A rastreabilidade permite reconstruir e auditar decisões, essencial para conformidade e investigação de incidentes.",
    marketReference: "ISO/IEC 42001; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 9,
    text: "A comunicação sobre o uso de IA é adaptada à compreensão de diferentes públicos (clientes, reguladores, auditores)?",
    description: "Avalia a adequação da comunicação de transparência aos diferentes stakeholders.",
    objective: "Verificar a efetividade da comunicação de transparência conforme o público.",
    justification: "Comunicação adequada ao público aumenta a compreensão real e a confiança nos sistemas de IA.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; EU AI Act",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 10,
    text: "Para sistemas de IA generativa, a organização sinaliza conteúdos gerados por IA aos usuários?",
    description: "Verifica a sinalização de conteúdos produzidos por IA generativa (labeling/watermarking).",
    objective: "Avaliar a transparência sobre conteúdo gerado por IA.",
    justification: "A sinalização de conteúdo gerado por IA combate desinformação e atende exigências regulatórias emergentes.",
    marketReference: "EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 11,
    text: "Existe um processo para documentar as limitações conhecidas e os cenários de falha de cada modelo?",
    description: "Avalia o registro das limitações e condições de falha dos modelos de IA.",
    objective: "Verificar a transparência sobre limitações e riscos residuais dos modelos.",
    justification: "Documentar limitações previne uso inadequado e apoia decisões conscientes sobre a confiança nos modelos.",
    marketReference: "NIST AI RMF 1.0 — MAP; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 12,
    text: "As áreas de negócio compreendem como os modelos que utilizam chegam às suas recomendações?",
    description: "Avalia o grau de compreensão das áreas de negócio sobre o funcionamento dos modelos que operam.",
    objective: "Verificar a transparência interna dos modelos junto às áreas usuárias.",
    justification: "A compreensão pelas áreas de negócio reduz o uso indevido e melhora a supervisão humana das decisões.",
    marketReference: "NIST AI RMF 1.0 — GOVERN",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 13,
    text: "A organização publica ou disponibiliza informações sobre suas práticas de uso responsável de IA?",
    description: "Verifica a transparência externa por meio da divulgação de práticas e princípios de IA.",
    objective: "Avaliar a transparência externa das práticas de IA.",
    justification: "A divulgação de práticas reforça a confiança de clientes, investidores e reguladores na organização.",
    marketReference: "OCDE AI Principles; EU AI Act",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 14,
    text: "Em que grau os relatórios de explicabilidade são incorporados aos processos de validação e aprovação de modelos?",
    description: "Avalia a integração da explicabilidade aos gates de validação e aprovação de modelos.",
    objective: "Verificar o uso da explicabilidade na governança do ciclo de vida dos modelos.",
    justification: "Incorporar explicabilidade à validação assegura que apenas modelos compreensíveis e confiáveis avancem para produção.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "transparencia-explicabilidade",
    order: 15,
    text: "Descreva as principais técnicas e práticas de explicabilidade adotadas pela organização atualmente.",
    description: "Coleta qualitativa das técnicas e práticas de explicabilidade em uso.",
    objective: "Mapear as práticas de explicabilidade adotadas pela organização.",
    justification: "O mapeamento evidencia a maturidade técnica e orienta a evolução das capacidades de explicabilidade.",
    marketReference: "NIST AI RMF 1.0 — MEASURE",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },
];
