import type { CorpQuestionSeed } from "./types";

export const QUESTIONS_P3: CorpQuestionSeed[] = [
  // ── Infraestrutura Computacional ────────────────────────────────────────────
  {
    domainSlug: "infraestrutura-computacional",
    order: 1,
    text: "A organização dispõe de capacidade computacional acelerada (GPU/TPU) dimensionada para as cargas de treinamento e inferência de IA planejadas?",
    description: "Avalia a existência e o dimensionamento de aceleradores dedicados a workloads de IA, próprios ou em nuvem.",
    objective: "Verificar se a capacidade computacional é suficiente e planejada frente à demanda das iniciativas de IA.",
    justification: "A falta de capacidade acelerada limita a viabilidade de projetos de IA, gera filas e compromete prazos e custos.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019 — BAI04",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 2,
    text: "A infraestrutura de IA é elástica, permitindo escalar recursos automaticamente conforme a demanda de treinamento e inferência?",
    description: "Cobre a existência de autoscaling e provisionamento dinâmico para cargas variáveis de IA.",
    objective: "Avaliar a elasticidade e a capacidade de escalar recursos de forma automatizada.",
    justification: "A elasticidade evita superprovisionamento e garante desempenho em picos, otimizando custo e disponibilidade.",
    marketReference: "FinOps Foundation; ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 3,
    text: "Qual o principal modelo de provisionamento da infraestrutura computacional para IA na organização?",
    description: "Identifica se a estratégia de infraestrutura é on-premises, nuvem pública, híbrida ou multicloud.",
    objective: "Compreender o modelo de infraestrutura adotado e sua adequação estratégica.",
    justification: "O modelo de provisionamento impacta custo, soberania de dados, escalabilidade e dependência de fornecedores.",
    marketReference: "TOGAF; COBIT 2019 — APO09",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Totalmente on-premises", "Nuvem pública única", "Híbrido (on-premises + nuvem)", "Multicloud", "Não estruturado"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 4,
    text: "A infraestrutura de IA está provisionada como código (IaC), garantindo reprodutibilidade e versionamento dos ambientes?",
    description: "Avalia o uso de ferramentas de Infrastructure as Code para padronizar ambientes de IA.",
    objective: "Verificar a maturidade na automação e reprodutibilidade do provisionamento de infraestrutura.",
    justification: "IaC reduz erros manuais, acelera provisionamento e assegura consistência entre ambientes.",
    marketReference: "ITIL 4; COBIT 2019 — BAI06",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 5,
    text: "Existem políticas de governança e controle de acesso segregado para os ambientes de infraestrutura de IA?",
    description: "Cobre a segregação de ambientes (dev, homologação, produção) e o controle de acesso privilegiado.",
    objective: "Avaliar os controles de acesso e a segregação de ambientes de infraestrutura.",
    justification: "Acessos inadequados a recursos computacionais elevam riscos de segurança e vazamento de dados sensíveis.",
    marketReference: "ISO/IEC 27001 — A.9; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 6,
    text: "A organização monitora a utilização e a eficiência dos recursos computacionais (taxa de ocupação de GPU, custo por job)?",
    description: "Avalia o acompanhamento de métricas de utilização e eficiência da infraestrutura de IA.",
    objective: "Verificar a existência de observabilidade sobre o uso e eficiência dos recursos.",
    justification: "Sem visibilidade de utilização, há desperdício de recursos caros e dificuldade de planejamento de capacidade.",
    marketReference: "FinOps Foundation; COBIT 2019 — MEA01",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 7,
    text: "Qual o percentual médio de ocupação (utilização) dos recursos de GPU/aceleradores da organização?",
    description: "Quantifica a eficiência de uso dos aceleradores computacionais dedicados a IA.",
    objective: "Medir a eficiência de aproveitamento dos recursos acelerados disponíveis.",
    justification: "Ocupação muito baixa indica desperdício de investimento; muito alta pode indicar gargalos de capacidade.",
    marketReference: "FinOps Foundation",
    criticality: "baixa",
    weight: 2,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 8,
    text: "Existe um processo formal de planejamento de capacidade computacional para as iniciativas de IA?",
    description: "Cobre a projeção de demanda e o planejamento antecipado de capacidade para IA.",
    objective: "Avaliar a maturidade do planejamento de capacidade frente ao crescimento das cargas de IA.",
    justification: "O planejamento de capacidade evita indisponibilidade e sobrecustos por aquisições emergenciais.",
    marketReference: "ITIL 4 — Capacity and Performance Management; COBIT 2019 — BAI04",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 9,
    text: "A infraestrutura de IA possui redundância e alta disponibilidade adequadas à criticidade das aplicações servidas?",
    description: "Avalia mecanismos de tolerância a falhas e continuidade da infraestrutura de inferência.",
    objective: "Verificar a resiliência e disponibilidade da infraestrutura de IA em produção.",
    justification: "Aplicações de IA críticas ao negócio exigem alta disponibilidade para evitar impacto operacional e financeiro.",
    marketReference: "ISO/IEC 27001 — A.17; ITIL 4",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 10,
    text: "A organização utiliza containers e orquestração (ex.: Kubernetes) para padronizar o deployment de cargas de IA?",
    description: "Cobre a adoção de conteinerização e orquestração para portabilidade e escalabilidade de workloads.",
    objective: "Avaliar a padronização e portabilidade dos ambientes de execução de IA.",
    justification: "Containers e orquestração aceleram deployment, isolam dependências e facilitam a escalabilidade.",
    marketReference: "TOGAF; COBIT 2019 — BAI03",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 11,
    text: "Há controles de sustentabilidade e eficiência energética considerados na operação da infraestrutura de IA?",
    description: "Avalia a incorporação de critérios de eficiência energética e sustentabilidade (Green IT) nas cargas de IA.",
    objective: "Verificar a consideração de aspectos ambientais na operação de infraestrutura.",
    justification: "Cargas de IA são intensivas em energia; a eficiência impacta custos e metas ESG corporativas.",
    marketReference: "ISO/IEC 42001; FinOps Foundation",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 12,
    text: "A infraestrutura de IA está localizada e configurada em conformidade com requisitos de soberania e residência de dados aplicáveis?",
    description: "Cobre a aderência a exigências regulatórias de localização de dados em cargas de IA.",
    objective: "Avaliar a conformidade da infraestrutura com requisitos de residência e soberania de dados.",
    justification: "O processamento de dados sensíveis fora da jurisdição pode violar a LGPD e normas do setor financeiro.",
    marketReference: "LGPD Art. 46; BACEN Res. 4.893",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 13,
    text: "Existe estratégia de otimização de custos de infraestrutura de IA (instâncias spot, reservas, rightsizing)?",
    description: "Avalia práticas de otimização financeira aplicadas aos recursos computacionais de IA.",
    objective: "Verificar a maturidade na gestão e otimização de custos de infraestrutura.",
    justification: "Sem otimização, os custos de computação de IA crescem descontroladamente e comprometem o ROI.",
    marketReference: "FinOps Foundation; COBIT 2019 — APO06",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 14,
    text: "A infraestrutura de IA está integrada ao plano de continuidade de negócios e recuperação de desastres da organização?",
    description: "Cobre a inclusão de recursos de IA nos planos de DR/BCP corporativos.",
    objective: "Avaliar a resiliência da infraestrutura de IA em cenários de desastre.",
    justification: "A ausência de DR para IA pode paralisar processos críticos dependentes de modelos em produção.",
    marketReference: "ISO/IEC 27001 — A.17; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "infraestrutura-computacional",
    order: 15,
    text: "Descreva os principais gargalos e limitações atuais da infraestrutura computacional para IA.",
    description: "Coleta qualitativa sobre restrições percebidas na infraestrutura de IA.",
    objective: "Identificar limitações e oportunidades de melhoria na infraestrutura computacional.",
    justification: "Mapear gargalos direciona investimentos e prioriza melhorias com maior impacto no negócio.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── MLOps ───────────────────────────────────────────────────────────────────
  {
    domainSlug: "mlops",
    order: 1,
    text: "A organização possui pipelines de CI/CD automatizados para o ciclo de vida de modelos de machine learning?",
    description: "Avalia a existência de esteiras automatizadas para build, teste e implantação de modelos.",
    objective: "Verificar o grau de automação do ciclo de vida de modelos de ML.",
    justification: "Pipelines automatizados reduzem erros, aceleram entregas e garantem consistência entre versões.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019 — BAI03",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 2,
    text: "Os modelos, dados e código de treinamento são versionados de forma integrada, garantindo reprodutibilidade dos experimentos?",
    description: "Cobre o versionamento conjunto de artefatos (código, dados e modelos) para reprodutibilidade.",
    objective: "Avaliar a capacidade de reproduzir experimentos e rastrear versões de modelos.",
    justification: "A reprodutibilidade é essencial para auditoria, depuração e gestão de risco de modelos.",
    marketReference: "ISO/IEC 42001; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "mlops",
    order: 3,
    text: "Existe um registro central de modelos (model registry) com metadados, versões e estágios de promoção?",
    description: "Avalia a existência de um repositório governado de modelos com controle de estágios.",
    objective: "Verificar a centralização e governança do inventário de modelos.",
    justification: "Um registry evita modelos órfãos, facilita governança e habilita rollback e auditoria.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MAP",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 4,
    text: "Qual estratégia de deployment de modelos é predominantemente utilizada na organização?",
    description: "Identifica a abordagem de implantação de modelos em produção (blue-green, canary, shadow etc.).",
    objective: "Compreender a maturidade das práticas de deployment de modelos.",
    justification: "Estratégias controladas de deployment reduzem risco de degradação de serviço em produção.",
    marketReference: "COBIT 2019 — BAI07; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Deployment manual direto", "Blue-green", "Canary", "Shadow deployment", "Não há estratégia definida"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 5,
    text: "Há testes automatizados de qualidade de dados e de desempenho de modelos integrados aos pipelines de ML?",
    description: "Cobre a validação automática de dados e métricas de modelo antes da promoção para produção.",
    objective: "Avaliar a existência de gates de qualidade automatizados nos pipelines.",
    justification: "Testes automatizados evitam a promoção de modelos degradados ou treinados com dados inadequados.",
    marketReference: "ISO/IEC 23894; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 6,
    text: "A organização utiliza um feature store para padronizar e reutilizar features entre modelos?",
    description: "Avalia a adoção de repositório de features compartilhadas entre treinamento e inferência.",
    objective: "Verificar a padronização e reutilização de features de ML.",
    justification: "Feature stores reduzem inconsistências entre treino e produção (training-serving skew) e retrabalho.",
    marketReference: "DAMA-DMBOK; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 7,
    text: "Existe processo automatizado de retreinamento de modelos acionado por gatilhos de desempenho ou drift?",
    description: "Cobre a automação do retreinamento com base em degradação de métricas ou mudança de dados.",
    objective: "Avaliar a maturidade do retreinamento contínuo de modelos.",
    justification: "O retreinamento oportuno mantém a acurácia e evita decisões baseadas em modelos desatualizados.",
    marketReference: "ISO/IEC 23894; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 8,
    text: "Os experimentos de ML são rastreados de forma sistemática (parâmetros, métricas, artefatos)?",
    description: "Avalia o uso de ferramentas de experiment tracking para comparação e rastreabilidade.",
    objective: "Verificar a disciplina de rastreamento de experimentos de ML.",
    justification: "O rastreamento de experimentos acelera a seleção de modelos e sustenta auditorias.",
    marketReference: "ISO/IEC 42001; COBIT 2019 — BAI03",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 9,
    text: "Qual o percentual de modelos em produção que possuem pipeline de deployment totalmente automatizado?",
    description: "Quantifica a cobertura de automação de deployment no portfólio de modelos.",
    objective: "Medir a abrangência da automação de MLOps no portfólio de modelos.",
    justification: "Baixa cobertura de automação indica processos manuais que elevam risco operacional e custo.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 10,
    text: "Existe rastreabilidade de linhagem de ponta a ponta (dados de origem até predições em produção) para os modelos?",
    description: "Cobre a capacidade de rastrear a origem dos dados e o fluxo até as predições servidas.",
    objective: "Avaliar a rastreabilidade e a linhagem completa dos modelos.",
    justification: "A linhagem é fundamental para auditoria regulatória, investigação de incidentes e conformidade.",
    marketReference: "DAMA-DMBOK; BACEN Res. 4.893",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 11,
    text: "As práticas de MLOps são padronizadas e documentadas em toda a organização, e não apenas em equipes isoladas?",
    description: "Avalia a abrangência corporativa e a padronização das práticas de MLOps.",
    objective: "Verificar o nível de institucionalização das práticas de MLOps.",
    justification: "Práticas fragmentadas geram inconsistências, retrabalho e dificuldade de governança em escala.",
    marketReference: "COBIT 2019; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 12,
    text: "Há mecanismos automatizados de rollback para reverter modelos com desempenho degradado em produção?",
    description: "Cobre a capacidade de reverter rapidamente para versões estáveis de modelos.",
    objective: "Avaliar a resiliência operacional dos deployments de modelos.",
    justification: "O rollback rápido limita o impacto de modelos defeituosos sobre clientes e operações.",
    marketReference: "ITIL 4; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 13,
    text: "A documentação técnica dos modelos (model cards) é gerada e mantida como parte do pipeline de MLOps?",
    description: "Avalia a produção sistemática de documentação padronizada de modelos.",
    objective: "Verificar a disciplina de documentação de modelos integrada ao ciclo de vida.",
    justification: "Model cards apoiam transparência, governança e conformidade regulatória.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MAP",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 14,
    text: "Existe segregação de ambientes (desenvolvimento, homologação e produção) com controles de promoção formais para modelos?",
    description: "Cobre a separação de ambientes e o processo de aprovação para promoção de modelos.",
    objective: "Avaliar os controles de promoção e a segregação de ambientes de ML.",
    justification: "A segregação e a aprovação formal reduzem riscos de deployment não autorizado ou instável.",
    marketReference: "ISO/IEC 27001 — A.12; COBIT 2019 — BAI07",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "mlops",
    order: 15,
    text: "A organização mede indicadores de eficiência de MLOps, como lead time para produção e frequência de deployment?",
    description: "Avalia o acompanhamento de métricas DORA adaptadas ao ciclo de vida de modelos.",
    objective: "Verificar a mensuração da eficiência e velocidade das entregas de ML.",
    justification: "Métricas de eficiência orientam a melhoria contínua e demonstram maturidade operacional.",
    marketReference: "Gartner AI Maturity Model; ITIL 4",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── LLMOps ──────────────────────────────────────────────────────────────────
  {
    domainSlug: "llmops",
    order: 1,
    text: "A organização possui gestão centralizada e versionada de prompts utilizados em aplicações com LLMs?",
    description: "Avalia a existência de repositório governado e versionado de prompts.",
    objective: "Verificar a maturidade na gestão do ciclo de vida de prompts.",
    justification: "Prompts não versionados geram comportamento inconsistente e dificultam auditoria e depuração.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 2,
    text: "Existem guardrails implementados para filtrar entradas e saídas dos LLMs (conteúdo tóxico, PII, prompt injection)?",
    description: "Cobre a existência de controles de segurança e conformidade nas interações com LLMs.",
    objective: "Avaliar os controles de segurança aplicados às entradas e saídas dos LLMs.",
    justification: "Guardrails mitigam vazamento de dados, prompt injection e geração de conteúdo indevido.",
    marketReference: "OWASP Top 10 for LLM; MITRE ATLAS; LGPD Art. 46",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "llmops",
    order: 3,
    text: "A organização realiza avaliação sistemática da qualidade das respostas dos LLMs (evals) antes e após a produção?",
    description: "Avalia a existência de processos de evaluation contínua da qualidade dos LLMs.",
    objective: "Verificar a disciplina de avaliação de qualidade e regressão de LLMs.",
    justification: "Sem evals, mudanças em prompts ou modelos podem degradar a qualidade sem detecção.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MEASURE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 4,
    text: "Há monitoramento de custos de tokens e uso de LLMs com atribuição por aplicação ou área de negócio?",
    description: "Cobre a observabilidade e o chargeback de custos de consumo de LLMs.",
    objective: "Avaliar o controle e a atribuição de custos de LLMs.",
    justification: "O consumo de tokens pode escalar rapidamente; a falta de controle compromete o ROI e o orçamento.",
    marketReference: "FinOps Foundation; COBIT 2019 — APO06",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 5,
    text: "Existe processo de detecção e mitigação de alucinações nas respostas geradas pelos LLMs?",
    description: "Avalia mecanismos para identificar e reduzir respostas factualmente incorretas.",
    objective: "Verificar a existência de controles contra alucinações dos LLMs.",
    justification: "Alucinações em contextos financeiros podem gerar decisões erradas, riscos legais e perda de confiança.",
    marketReference: "OWASP Top 10 for LLM; NIST AI RMF 1.0 — MEASURE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 6,
    text: "Qual a abordagem predominante de utilização de LLMs na organização?",
    description: "Identifica se a organização usa APIs de terceiros, modelos open-source auto-hospedados ou modelos próprios.",
    objective: "Compreender a estratégia de sourcing e hospedagem de LLMs.",
    justification: "A abordagem escolhida impacta custo, privacidade, controle e dependência de fornecedores.",
    marketReference: "Gartner AI Maturity Model; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["APIs de provedores externos", "Modelos open-source auto-hospedados", "Modelos proprietários fine-tuned", "Abordagem híbrida", "Ainda em experimentação"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 7,
    text: "Os registros de interações com LLMs (prompts, respostas, metadados) são armazenados para auditoria e melhoria?",
    description: "Cobre o logging governado das interações com LLMs, respeitando privacidade.",
    objective: "Avaliar a rastreabilidade e o registro das interações com LLMs.",
    justification: "O logging habilita auditoria, investigação de incidentes e melhoria contínua dos prompts.",
    marketReference: "ISO/IEC 27001 — A.12; LGPD Art. 46",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 8,
    text: "Existe estratégia de fallback e degradação graciosa quando o provedor de LLM está indisponível ou lento?",
    description: "Avalia a resiliência das aplicações frente a indisponibilidade de LLMs.",
    objective: "Verificar mecanismos de continuidade em falhas de provedores de LLM.",
    justification: "A dependência de LLMs externos torna a resiliência essencial para a continuidade do serviço.",
    marketReference: "ITIL 4; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 9,
    text: "Qual o percentual das aplicações com LLM que possuem guardrails de segurança implementados?",
    description: "Quantifica a cobertura de controles de segurança nas aplicações com LLMs.",
    objective: "Medir a abrangência da aplicação de guardrails no portfólio de LLMs.",
    justification: "Cobertura parcial deixa aplicações expostas a prompt injection e vazamento de dados.",
    marketReference: "OWASP Top 10 for LLM; MITRE ATLAS",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 10,
    text: "A organização controla e aprova formalmente os modelos e versões de LLM utilizados em produção?",
    description: "Cobre a governança sobre quais modelos/versões são autorizados em produção.",
    objective: "Avaliar a governança de aprovação de modelos de LLM.",
    justification: "Mudanças de versão de LLM sem governança podem alterar comportamento e violar conformidade.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 11,
    text: "Há políticas e controles para proteger informações sensíveis enviadas a LLMs de terceiros?",
    description: "Avalia controles de mascaramento, anonimização e restrição de dados enviados a LLMs externos.",
    objective: "Verificar a proteção de dados sensíveis nas interações com LLMs externos.",
    justification: "O envio de dados sensíveis a provedores externos pode violar a LGPD e sigilo bancário.",
    marketReference: "LGPD Art. 46; BACEN Res. 4.893; ISO/IEC 27001",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 12,
    text: "Existe processo de fine-tuning ou adaptação de LLMs com governança sobre dados e avaliação dos resultados?",
    description: "Cobre a governança dos processos de ajuste de modelos de linguagem.",
    objective: "Avaliar a maturidade e a governança das práticas de fine-tuning de LLMs.",
    justification: "Fine-tuning sem governança pode introduzir viés, vazar dados de treino e degradar desempenho.",
    marketReference: "ISO/IEC 42001; ISO/IEC 23894",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 13,
    text: "A latência e a disponibilidade das aplicações com LLMs são monitoradas com SLAs definidos?",
    description: "Avalia o monitoramento de desempenho operacional das aplicações com LLMs.",
    objective: "Verificar a gestão de desempenho e SLAs das aplicações de LLM.",
    justification: "A experiência do usuário depende de latência e disponibilidade consistentes das respostas.",
    marketReference: "ITIL 4 — Service Level Management",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 14,
    text: "Existe um framework de testes de regressão para validar prompts e configurações antes de mudanças em produção?",
    description: "Cobre a validação automatizada de mudanças em prompts e parâmetros de LLM.",
    objective: "Avaliar a disciplina de testes de regressão em LLMOps.",
    justification: "Mudanças aparentemente simples em prompts podem causar regressões significativas de qualidade.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MEASURE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "llmops",
    order: 15,
    text: "A organização coleta feedback dos usuários sobre as respostas dos LLMs para melhoria contínua?",
    description: "Avalia mecanismos de captura de feedback (thumbs up/down, avaliações) integrados ao ciclo de melhoria.",
    objective: "Verificar a existência de loops de feedback para aprimoramento dos LLMs.",
    justification: "O feedback dos usuários é insumo essencial para melhorar qualidade e alinhamento das respostas.",
    marketReference: "Gartner AI Maturity Model; NIST AI RMF 1.0 — MEASURE",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── AI Agents ───────────────────────────────────────────────────────────────
  {
    domainSlug: "ai-agents",
    order: 1,
    text: "A organização define limites de ação e níveis de autonomia claros para agentes de IA em produção?",
    description: "Avalia a existência de fronteiras explícitas para o que os agentes autônomos podem executar.",
    objective: "Verificar o controle sobre a autonomia e o escopo de ação dos agentes de IA.",
    justification: "Agentes com autonomia irrestrita podem executar ações danosas ou não autorizadas com alto impacto.",
    marketReference: "OWASP Top 10 for LLM; NIST AI RMF 1.0 — GOVERN",
    criticality: "critica",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "ai-agents",
    order: 2,
    text: "Existe supervisão humana (human-in-the-loop) para aprovação de ações críticas executadas por agentes de IA?",
    description: "Cobre a exigência de aprovação humana para ações sensíveis ou de alto impacto.",
    objective: "Avaliar a presença de supervisão humana sobre ações críticas dos agentes.",
    justification: "A supervisão humana é essencial para prevenir ações irreversíveis e atender exigências regulatórias.",
    marketReference: "EU AI Act; NIST AI RMF 1.0 — MANAGE",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 3,
    text: "As ações executadas por agentes de IA são registradas de forma auditável (trilha de decisões e ferramentas acionadas)?",
    description: "Avalia o logging detalhado das decisões e chamadas de ferramentas realizadas pelos agentes.",
    objective: "Verificar a rastreabilidade e auditabilidade das ações dos agentes.",
    justification: "Sem trilha auditável, é impossível investigar incidentes ou comprovar conformidade.",
    marketReference: "ISO/IEC 42001; MITRE ATLAS",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 4,
    text: "Há controle de acesso e privilégios mínimos aplicados às ferramentas e sistemas que os agentes podem acionar?",
    description: "Cobre a aplicação do princípio de menor privilégio às integrações dos agentes.",
    objective: "Avaliar os controles de acesso concedidos aos agentes de IA.",
    justification: "Agentes com privilégios excessivos ampliam a superfície de ataque e o impacto de comprometimentos.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001 — A.9",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 5,
    text: "A organização utiliza uma plataforma ou framework padronizado para orquestração de agentes de IA?",
    description: "Avalia a padronização das ferramentas de construção e orquestração de agentes.",
    objective: "Verificar a padronização tecnológica no desenvolvimento de agentes.",
    justification: "A padronização reduz risco, facilita governança e evita proliferação de soluções não controladas.",
    marketReference: "TOGAF; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 6,
    text: "Existem kill switches ou mecanismos de interrupção imediata para deter agentes de IA em caso de comportamento indevido?",
    description: "Cobre a capacidade de interromper rapidamente a execução de agentes autônomos.",
    objective: "Avaliar a existência de mecanismos de contenção emergencial de agentes.",
    justification: "A capacidade de interromper agentes limita danos em cenários de falha ou comportamento inesperado.",
    marketReference: "NIST AI RMF 1.0 — MANAGE; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 7,
    text: "Qual o nível de autonomia predominante dos agentes de IA atualmente em uso na organização?",
    description: "Identifica o grau de autonomia dos agentes, de assistivo a totalmente autônomo.",
    objective: "Compreender o nível de autonomia dos agentes em operação.",
    justification: "O nível de autonomia determina o risco associado e os controles necessários.",
    marketReference: "Gartner AI Maturity Model; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Assistivo (sugere, humano executa)", "Semi-autônomo com aprovação", "Autônomo com supervisão", "Totalmente autônomo", "Não utiliza agentes"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 8,
    text: "Os agentes de IA passam por testes adversariais e de segurança antes de entrarem em produção?",
    description: "Avalia a realização de red teaming e testes de segurança específicos para agentes.",
    objective: "Verificar a validação de segurança dos agentes antes do deployment.",
    justification: "Agentes podem ser manipulados via prompt injection para executar ações maliciosas.",
    marketReference: "MITRE ATLAS; OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 9,
    text: "Existe um inventário atualizado de todos os agentes de IA em operação, com responsáveis e finalidade definidos?",
    description: "Cobre a existência de registro governado dos agentes ativos na organização.",
    objective: "Avaliar a governança e visibilidade sobre o parque de agentes.",
    justification: "Agentes não inventariados (shadow AI) representam riscos ocultos de segurança e conformidade.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — MAP",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 10,
    text: "Há limites de custo e de número de operações (rate limiting) configurados para prevenir loops ou consumo descontrolado por agentes?",
    description: "Avalia controles que impedem execução em loop e gastos excessivos por agentes.",
    objective: "Verificar a existência de controles de contenção de custo e recursão dos agentes.",
    justification: "Agentes em loop podem gerar custos elevados e sobrecarregar sistemas em minutos.",
    marketReference: "FinOps Foundation; OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 11,
    text: "Qual o percentual de agentes de IA em produção que operam com supervisão humana para ações de alto impacto?",
    description: "Quantifica a cobertura de human-in-the-loop no parque de agentes.",
    objective: "Medir a abrangência da supervisão humana sobre agentes autônomos.",
    justification: "Baixa cobertura de supervisão eleva o risco de ações não autorizadas com impacto ao negócio.",
    marketReference: "EU AI Act; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 12,
    text: "A comunicação entre múltiplos agentes (sistemas multiagentes) é governada com protocolos e limites definidos?",
    description: "Cobre a governança de arquiteturas multiagentes e suas interações.",
    objective: "Avaliar o controle sobre interações em sistemas multiagentes.",
    justification: "Interações não governadas entre agentes podem produzir comportamentos emergentes imprevisíveis.",
    marketReference: "ISO/IEC 42001; TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 13,
    text: "Os agentes de IA possuem avaliação contínua de desempenho e taxa de sucesso de suas tarefas?",
    description: "Avalia o monitoramento de eficácia e confiabilidade dos agentes em operação.",
    objective: "Verificar a mensuração de desempenho e confiabilidade dos agentes.",
    justification: "Sem medição de eficácia, é difícil justificar o uso de agentes e identificar degradações.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 14,
    text: "Existe política corporativa que define casos de uso permitidos e proibidos para agentes de IA?",
    description: "Cobre a existência de diretrizes formais sobre onde agentes podem ou não ser aplicados.",
    objective: "Avaliar a existência de política de uso aceitável para agentes de IA.",
    justification: "Políticas claras evitam o uso de agentes em contextos de alto risco sem os devidos controles.",
    marketReference: "ISO/IEC 42001; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ai-agents",
    order: 15,
    text: "Descreva os principais casos de uso de agentes de IA em produção e os controles de segurança associados.",
    description: "Coleta qualitativa sobre a aplicação prática e os controles dos agentes.",
    objective: "Mapear os casos de uso reais e a maturidade dos controles adotados.",
    justification: "Compreender os casos concretos permite avaliar a adequação dos controles ao risco real.",
    marketReference: "NIST AI RMF 1.0 — MAP",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── RAG e Gestão de Conhecimento ────────────────────────────────────────────
  {
    domainSlug: "rag",
    order: 1,
    text: "A organização possui arquitetura de RAG (Retrieval-Augmented Generation) estruturada para fundamentar respostas em conhecimento corporativo?",
    description: "Avalia a existência de uma arquitetura de RAG que ancora as respostas em fontes confiáveis.",
    objective: "Verificar a maturidade da arquitetura de RAG implementada.",
    justification: "O RAG reduz alucinações e aumenta a precisão ao ancorar respostas em conhecimento verificado.",
    marketReference: "Gartner AI Maturity Model; OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 2,
    text: "Existe processo de curadoria e atualização contínua da base de conhecimento utilizada pelo RAG?",
    description: "Cobre a governança sobre a qualidade, relevância e atualidade do conteúdo indexado.",
    objective: "Avaliar a governança de curadoria da base de conhecimento de RAG.",
    justification: "Bases desatualizadas ou incorretas propagam informações erradas nas respostas geradas.",
    marketReference: "DAMA-DMBOK; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 3,
    text: "Os controles de acesso a documentos são preservados na recuperação do RAG, respeitando as permissões do usuário?",
    description: "Avalia se o RAG respeita as permissões originais dos documentos indexados.",
    objective: "Verificar a aplicação de controles de acesso na camada de recuperação.",
    justification: "Sem controle de acesso, o RAG pode expor informações confidenciais a usuários não autorizados.",
    marketReference: "ISO/IEC 27001 — A.9; LGPD Art. 46",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "rag",
    order: 4,
    text: "A qualidade da recuperação (precisão e recall dos documentos retornados) é avaliada sistematicamente?",
    description: "Cobre a mensuração da eficácia do componente de retrieval do RAG.",
    objective: "Avaliar a mensuração da qualidade da recuperação de informações.",
    justification: "Recuperação de baixa qualidade compromete diretamente a precisão das respostas finais.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 5,
    text: "As respostas geradas via RAG incluem citações ou referências às fontes utilizadas?",
    description: "Avalia a rastreabilidade das respostas às fontes de conhecimento originais.",
    objective: "Verificar a transparência e a rastreabilidade das respostas do RAG.",
    justification: "Citações permitem verificação humana, aumentam a confiança e apoiam a conformidade.",
    marketReference: "EU AI Act; NIST AI RMF 1.0 — MAP",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 6,
    text: "Qual tipo de banco de dados vetorial é utilizado para a indexação de embeddings no RAG?",
    description: "Identifica a tecnologia de armazenamento vetorial adotada na arquitetura de RAG.",
    objective: "Compreender a escolha tecnológica da camada de armazenamento vetorial.",
    justification: "A escolha do banco vetorial impacta escalabilidade, desempenho e custo da solução de RAG.",
    marketReference: "TOGAF; Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "multiple_choice",
    options: ["Banco vetorial dedicado", "Extensão vetorial em banco relacional", "Índice em memória", "Serviço gerenciado de nuvem", "Não utiliza base vetorial"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 7,
    text: "Há estratégia definida de chunking (segmentação) e geração de embeddings otimizada para os documentos corporativos?",
    description: "Avalia a maturidade das estratégias de segmentação e vetorização do conteúdo.",
    objective: "Verificar a otimização das estratégias de chunking e embeddings.",
    justification: "Estratégias inadequadas de chunking degradam a relevância da recuperação e a qualidade das respostas.",
    marketReference: "Gartner AI Maturity Model; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 8,
    text: "Existem controles para evitar a indexação de dados pessoais ou sensíveis sem base legal na base de conhecimento?",
    description: "Cobre a proteção de dados pessoais no pipeline de ingestão do RAG.",
    objective: "Avaliar os controles de privacidade na indexação de conteúdo.",
    justification: "A indexação indevida de dados pessoais pode violar a LGPD e expor informações sensíveis.",
    marketReference: "LGPD Art. 46; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 9,
    text: "A base de conhecimento é sincronizada automaticamente com as fontes de origem quando há atualizações?",
    description: "Avalia a automação da atualização do índice frente a mudanças nas fontes.",
    objective: "Verificar a automação da sincronização da base de conhecimento.",
    justification: "A sincronização manual gera defasagem e risco de respostas baseadas em conteúdo obsoleto.",
    marketReference: "DAMA-DMBOK; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 10,
    text: "Qual o percentual da base de conhecimento corporativa relevante que está efetivamente indexada e disponível para RAG?",
    description: "Quantifica a cobertura do conhecimento corporativo na solução de RAG.",
    objective: "Medir a abrangência da base de conhecimento disponível para RAG.",
    justification: "Cobertura limitada reduz a utilidade do RAG e leva a respostas incompletas ou genéricas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 11,
    text: "A organização mede a taxa de fundamentação (groundedness) das respostas em relação às fontes recuperadas?",
    description: "Cobre a avaliação de quão fiéis as respostas são ao conteúdo recuperado.",
    objective: "Avaliar a mensuração da fidelidade das respostas às fontes.",
    justification: "Baixa fundamentação indica que o modelo está alucinando apesar do contexto fornecido.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 12,
    text: "Existe governança formal sobre a propriedade e a responsabilidade pelo conteúdo da base de conhecimento?",
    description: "Avalia a definição de data owners e responsáveis pela qualidade do conhecimento.",
    objective: "Verificar a atribuição de responsabilidades sobre o conhecimento corporativo.",
    justification: "Sem responsáveis definidos, a base de conhecimento degrada e perde confiabilidade ao longo do tempo.",
    marketReference: "DAMA-DMBOK; COBIT 2019 — APO14",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 13,
    text: "Há mecanismos de reranking ou filtragem para melhorar a relevância dos documentos recuperados?",
    description: "Cobre técnicas avançadas de refinamento da recuperação (reranking, filtros de metadados).",
    objective: "Avaliar a sofisticação das técnicas de otimização de relevância.",
    justification: "O reranking eleva a qualidade do contexto e, consequentemente, a precisão das respostas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 14,
    text: "As soluções de RAG são testadas contra tentativas de exfiltração de dados via manipulação de contexto?",
    description: "Avalia testes de segurança específicos para vazamento de dados através do RAG.",
    objective: "Verificar a resiliência do RAG a ataques de exfiltração de informações.",
    justification: "Atacantes podem manipular prompts para extrair documentos sensíveis indevidamente do índice.",
    marketReference: "OWASP Top 10 for LLM; MITRE ATLAS",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "rag",
    order: 15,
    text: "O desempenho (latência) da recuperação e geração do RAG atende aos requisitos das aplicações de negócio?",
    description: "Avalia se a latência da solução de RAG é adequada às necessidades operacionais.",
    objective: "Verificar a adequação do desempenho do RAG aos requisitos de negócio.",
    justification: "Latência elevada compromete a experiência do usuário e a adoção da solução.",
    marketReference: "ITIL 4 — Service Level Management",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Arquitetura e Integração ────────────────────────────────────────────────
  {
    domainSlug: "arquitetura-integracao",
    order: 1,
    text: "A organização possui padrões de arquitetura de referência definidos para soluções de IA?",
    description: "Avalia a existência de arquitetura de referência que padronize as soluções de IA.",
    objective: "Verificar a existência de padrões arquiteturais para IA.",
    justification: "Padrões de referência reduzem retrabalho, riscos e inconsistências entre soluções de IA.",
    marketReference: "TOGAF; COBIT 2019 — APO03",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 2,
    text: "As soluções de IA são expostas e consumidas por meio de APIs padronizadas e governadas?",
    description: "Cobre a padronização e a governança das interfaces de integração das soluções de IA.",
    objective: "Avaliar a padronização e governança das APIs de IA.",
    justification: "APIs governadas facilitam a integração, o versionamento e o controle de acesso às soluções de IA.",
    marketReference: "TOGAF; ISO/IEC 27001 — A.14",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 3,
    text: "Existe integração estruturada das soluções de IA com os sistemas core e legados da organização?",
    description: "Avalia a maturidade da integração da IA com sistemas centrais de negócio.",
    objective: "Verificar a integração das soluções de IA com o ecossistema de sistemas existente.",
    justification: "Integração deficiente limita o valor da IA e cria silos operacionais e de dados.",
    marketReference: "TOGAF; COBIT 2019 — BAI03",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 4,
    text: "A arquitetura de IA adota princípios de desacoplamento e modularidade que facilitam a evolução e a substituição de componentes?",
    description: "Cobre o uso de padrões que reduzem acoplamento e dependência de fornecedores.",
    objective: "Avaliar a modularidade e o desacoplamento da arquitetura de IA.",
    justification: "Arquiteturas acopladas dificultam a evolução e aumentam a dependência de fornecedores específicos.",
    marketReference: "TOGAF; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 5,
    text: "Qual o estilo de integração predominante utilizado para conectar as soluções de IA aos demais sistemas?",
    description: "Identifica o padrão de integração adotado (APIs REST, eventos, mensageria, batch etc.).",
    objective: "Compreender o padrão de integração predominante para IA.",
    justification: "O estilo de integração impacta escalabilidade, latência e resiliência das soluções de IA.",
    marketReference: "TOGAF; COBIT 2019 — APO03",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["APIs REST/gRPC síncronas", "Arquitetura orientada a eventos", "Mensageria assíncrona", "Processamento em batch", "Integrações ponto a ponto ad hoc"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 6,
    text: "As decisões arquiteturais de IA são revisadas e aprovadas por um comitê ou processo de governança de arquitetura?",
    description: "Cobre a governança sobre as decisões arquiteturais das soluções de IA.",
    objective: "Avaliar a governança das decisões de arquitetura de IA.",
    justification: "A ausência de governança arquitetural leva a soluções fragmentadas e dívida técnica crescente.",
    marketReference: "TOGAF — Architecture Board; COBIT 2019 — APO03",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 7,
    text: "Existe um gateway de API ou camada de gestão que controle acesso, throttling e observabilidade das APIs de IA?",
    description: "Avalia o uso de API gateway para governar as interfaces de IA.",
    objective: "Verificar a existência de camada de gestão e controle das APIs de IA.",
    justification: "Um gateway centraliza segurança, controle de consumo e monitoramento das APIs de IA.",
    marketReference: "ISO/IEC 27001 — A.13; TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 8,
    text: "A arquitetura de IA considera requisitos de escalabilidade horizontal para atender ao crescimento de demanda?",
    description: "Cobre o desenho arquitetural para escalar soluções conforme a demanda cresce.",
    objective: "Avaliar a preparação da arquitetura para escalar horizontalmente.",
    justification: "Arquiteturas não escaláveis tornam-se gargalos à medida que a adoção de IA cresce.",
    marketReference: "TOGAF; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 9,
    text: "As integrações de IA possuem tratamento de erros, retries e circuit breakers para garantir resiliência?",
    description: "Avalia os padrões de resiliência aplicados às integrações das soluções de IA.",
    objective: "Verificar a resiliência das integrações de IA a falhas.",
    justification: "Falhas em integrações podem propagar-se e derrubar processos de negócio dependentes de IA.",
    marketReference: "ITIL 4; ISO/IEC 27001 — A.17",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 10,
    text: "A documentação de arquitetura das soluções de IA é mantida atualizada e acessível às equipes técnicas?",
    description: "Cobre a manutenção de documentação arquitetural viva e acessível.",
    objective: "Avaliar a qualidade e atualidade da documentação de arquitetura de IA.",
    justification: "Documentação desatualizada aumenta risco operacional e dificulta manutenção e onboarding.",
    marketReference: "TOGAF; COBIT 2019 — BAI08",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 11,
    text: "Qual o percentual de soluções de IA integradas via APIs padronizadas em vez de integrações ad hoc?",
    description: "Quantifica o grau de padronização das integrações de IA.",
    objective: "Medir a adoção de padrões de integração no portfólio de IA.",
    justification: "Integrações ad hoc geram dívida técnica e dificultam manutenção e governança em escala.",
    marketReference: "TOGAF; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 12,
    text: "A arquitetura de IA incorpora requisitos de segurança desde a concepção (security by design)?",
    description: "Avalia a incorporação de controles de segurança na fase de desenho arquitetural.",
    objective: "Verificar a adoção de security by design na arquitetura de IA.",
    justification: "Segurança incorporada desde o desenho reduz vulnerabilidades e custos de correção posteriores.",
    marketReference: "ISO/IEC 27001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 13,
    text: "Existe estratégia para evitar aprisionamento tecnológico (vendor lock-in) na arquitetura de IA?",
    description: "Cobre a mitigação da dependência excessiva de fornecedores ou plataformas específicas.",
    objective: "Avaliar a mitigação de riscos de dependência de fornecedores.",
    justification: "O lock-in reduz poder de negociação e aumenta custos e riscos de continuidade.",
    marketReference: "TOGAF; COBIT 2019 — APO10",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 14,
    text: "A arquitetura contempla ambientes segregados de dados e processamento para atender a requisitos regulatórios do setor financeiro?",
    description: "Avalia a segregação arquitetural exigida por regulações do setor financeiro.",
    objective: "Verificar a conformidade arquitetural com requisitos regulatórios setoriais.",
    justification: "Regulações do BACEN e CMN exigem segregação e controles específicos em soluções financeiras.",
    marketReference: "BACEN Res. 4.893; CMN; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-integracao",
    order: 15,
    text: "As soluções de IA seguem padrões de interoperabilidade que permitem reutilização entre diferentes áreas de negócio?",
    description: "Cobre a promoção de reutilização e interoperabilidade das soluções de IA.",
    objective: "Avaliar a interoperabilidade e reutilização das soluções de IA.",
    justification: "A interoperabilidade maximiza o retorno dos investimentos e evita duplicação de esforços.",
    marketReference: "TOGAF; Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Ferramentas e Plataformas de IA ─────────────────────────────────────────
  {
    domainSlug: "ferramentas-plataformas",
    order: 1,
    text: "A organização possui uma plataforma de IA padronizada e homologada para desenvolvimento e implantação de soluções?",
    description: "Avalia a existência de uma plataforma corporativa padrão para o trabalho com IA.",
    objective: "Verificar a padronização das ferramentas e plataformas de IA.",
    justification: "A padronização reduz custos, riscos de segurança e fragmentação entre equipes.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019 — BAI03",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 2,
    text: "Existe um processo formal de homologação e aprovação de novas ferramentas de IA antes de sua adoção?",
    description: "Cobre a governança sobre a entrada de novas ferramentas no ambiente corporativo.",
    objective: "Avaliar a governança na seleção e homologação de ferramentas de IA.",
    justification: "A adoção descontrolada de ferramentas (shadow AI) cria riscos de segurança e conformidade.",
    marketReference: "COBIT 2019 — APO10; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 3,
    text: "As ferramentas de IA utilizadas possuem controle de licenciamento e gestão de acessos centralizada?",
    description: "Avalia a gestão de licenças e acessos às ferramentas de IA.",
    objective: "Verificar o controle de licenciamento e acesso às ferramentas.",
    justification: "A falta de gestão de licenças gera custos ocultos e riscos de conformidade contratual.",
    marketReference: "COBIT 2019 — APO06; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 4,
    text: "A organização disponibiliza ambientes self-service para cientistas de dados e engenheiros trabalharem com IA?",
    description: "Cobre a oferta de ambientes ágeis e autoatendimento para as equipes de IA.",
    objective: "Avaliar a maturidade dos ambientes self-service para IA.",
    justification: "Ambientes self-service aceleram a experimentação mantendo governança e padronização.",
    marketReference: "Gartner AI Maturity Model; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 5,
    text: "As ferramentas de IA adotadas passam por avaliação de segurança e conformidade antes da homologação?",
    description: "Avalia a inclusão de critérios de segurança na avaliação de ferramentas.",
    objective: "Verificar a análise de segurança das ferramentas de IA.",
    justification: "Ferramentas inseguras podem introduzir vulnerabilidades e vazamento de dados corporativos.",
    marketReference: "ISO/IEC 27001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 6,
    text: "Qual o grau de consolidação das ferramentas de IA na organização?",
    description: "Identifica se as ferramentas estão consolidadas ou dispersas entre equipes.",
    objective: "Compreender o nível de consolidação do portfólio de ferramentas de IA.",
    justification: "A dispersão de ferramentas eleva custos, riscos e complexidade de suporte e governança.",
    marketReference: "COBIT 2019; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Plataforma única consolidada", "Poucas plataformas padronizadas", "Muitas ferramentas por área", "Adoção descontrolada", "Não mapeado"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 7,
    text: "Existe um catálogo corporativo de ferramentas e plataformas de IA aprovadas e disponíveis?",
    description: "Cobre a existência de catálogo governado das soluções tecnológicas de IA.",
    objective: "Avaliar a existência e a manutenção de um catálogo de ferramentas.",
    justification: "Um catálogo orienta as equipes e reduz a adoção de ferramentas não homologadas.",
    marketReference: "ITIL 4 — Service Catalogue; COBIT 2019",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 8,
    text: "As plataformas de IA oferecem recursos integrados de governança (controle de versões, auditoria, linhagem)?",
    description: "Avalia se as plataformas incorporam capacidades nativas de governança.",
    objective: "Verificar a presença de recursos de governança nas plataformas de IA.",
    justification: "Plataformas com governança nativa facilitam conformidade e reduzem esforço manual.",
    marketReference: "ISO/IEC 42001; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 9,
    text: "Qual o percentual de projetos de IA que utilizam as ferramentas e plataformas corporativas homologadas?",
    description: "Quantifica a adesão às ferramentas padronizadas no portfólio de IA.",
    objective: "Medir a taxa de adoção das ferramentas homologadas.",
    justification: "Baixa adesão indica shadow AI e risco de governança fora de controle.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 10,
    text: "Há suporte técnico e capacitação estruturados para as ferramentas de IA adotadas?",
    description: "Cobre a oferta de suporte e treinamento para maximizar o uso das ferramentas.",
    objective: "Avaliar o suporte e a capacitação associados às ferramentas de IA.",
    justification: "A falta de suporte e capacitação reduz a adoção e o valor extraído das ferramentas.",
    marketReference: "ITIL 4; COBIT 2019 — APO07",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 11,
    text: "As ferramentas de IA de código aberto adotadas têm sua procedência e vulnerabilidades gerenciadas (SBOM, scanning)?",
    description: "Avalia a gestão de risco de componentes open-source usados em IA.",
    objective: "Verificar a gestão de segurança da cadeia de suprimentos de software de IA.",
    justification: "Componentes open-source vulneráveis podem comprometer toda a solução de IA.",
    marketReference: "ISO/IEC 27001; MITRE ATLAS",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 12,
    text: "A organização avalia periodicamente a adequação e a evolução das ferramentas de IA frente ao mercado?",
    description: "Cobre a revisão periódica do portfólio tecnológico frente à evolução do mercado.",
    objective: "Avaliar a gestão do ciclo de vida das ferramentas de IA.",
    justification: "Ferramentas obsoletas comprometem competitividade e podem deixar de receber suporte de segurança.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019 — APO04",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 13,
    text: "As plataformas de IA suportam colaboração entre equipes multidisciplinares (dados, engenharia, negócio)?",
    description: "Avalia se as plataformas habilitam trabalho colaborativo entre perfis diversos.",
    objective: "Verificar o suporte à colaboração multidisciplinar nas plataformas.",
    justification: "A colaboração eficaz acelera a entrega de valor e reduz silos entre áreas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 14,
    text: "Existe integração das ferramentas de IA com a esteira de segurança e conformidade corporativa (SSO, DLP, SIEM)?",
    description: "Cobre a integração das ferramentas de IA com controles corporativos de segurança.",
    objective: "Avaliar a integração das ferramentas com a infraestrutura de segurança.",
    justification: "A integração com controles corporativos garante visibilidade e conformidade consistentes.",
    marketReference: "ISO/IEC 27001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "ferramentas-plataformas",
    order: 15,
    text: "Descreva as principais ferramentas e plataformas de IA em uso e eventuais lacunas percebidas.",
    description: "Coleta qualitativa sobre o cenário atual de ferramentas e lacunas.",
    objective: "Mapear o cenário de ferramentas e identificar lacunas tecnológicas.",
    justification: "O mapeamento apoia decisões de investimento e racionalização do portfólio tecnológico.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Monitoramento e Observabilidade ─────────────────────────────────────────
  {
    domainSlug: "monitoramento-observabilidade",
    order: 1,
    text: "Os modelos de IA em produção são monitorados continuamente quanto ao desempenho e à acurácia?",
    description: "Avalia o monitoramento contínuo de métricas de desempenho dos modelos em produção.",
    objective: "Verificar a existência de monitoramento contínuo de desempenho dos modelos.",
    justification: "Sem monitoramento, a degradação de modelos passa despercebida e afeta decisões de negócio.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; ISO/IEC 23894",
    criticality: "critica",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 2,
    text: "Existe detecção automatizada de drift de dados e de conceito nos modelos em produção?",
    description: "Cobre a identificação automática de mudanças na distribuição de dados e no comportamento dos modelos.",
    objective: "Avaliar a capacidade de detectar drift de dados e de conceito.",
    justification: "O drift degrada silenciosamente a acurácia; sua detecção precoce evita perdas e decisões erradas.",
    marketReference: "ISO/IEC 23894; NIST AI RMF 1.0 — MEASURE",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 3,
    text: "Há alertas automatizados configurados para anomalias de desempenho, disponibilidade ou comportamento dos modelos?",
    description: "Avalia a existência de alertas proativos sobre problemas nos modelos em produção.",
    objective: "Verificar a existência de alertas proativos de observabilidade.",
    justification: "Alertas oportunos permitem resposta rápida antes que problemas impactem o negócio.",
    marketReference: "ITIL 4 — Monitoring and Event Management; NIST AI RMF 1.0 — MANAGE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 4,
    text: "A observabilidade dos modelos cobre a stack completa (infraestrutura, dados, modelo e negócio)?",
    description: "Cobre a abrangência do monitoramento em todas as camadas das soluções de IA.",
    objective: "Avaliar a abrangência da observabilidade das soluções de IA.",
    justification: "A observabilidade fragmentada dificulta o diagnóstico de causa raiz de incidentes.",
    marketReference: "ITIL 4; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 5,
    text: "Existem dashboards que traduzem métricas técnicas de IA em indicadores de negócio para stakeholders?",
    description: "Avalia a comunicação de métricas de IA em termos de impacto de negócio.",
    objective: "Verificar a existência de visibilidade de negócio sobre o desempenho da IA.",
    justification: "Conectar métricas técnicas ao negócio sustenta decisões de investimento e priorização.",
    marketReference: "COBIT 2019 — MEA01; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 6,
    text: "O comportamento dos modelos é monitorado quanto a viés e equidade ao longo do tempo em produção?",
    description: "Cobre o monitoramento contínuo de indicadores de viés e equidade dos modelos.",
    objective: "Avaliar o monitoramento de viés e equidade em produção.",
    justification: "O viés pode emergir ou intensificar-se em produção, gerando riscos legais e reputacionais.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 7,
    text: "Qual o percentual de modelos em produção que possuem monitoramento ativo de desempenho e drift?",
    description: "Quantifica a cobertura de monitoramento no portfólio de modelos em produção.",
    objective: "Medir a abrangência do monitoramento sobre os modelos produtivos.",
    justification: "Modelos sem monitoramento representam risco oculto de degradação e não conformidade.",
    marketReference: "NIST AI RMF 1.0 — MEASURE",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 8,
    text: "Os logs e métricas de modelos são retidos pelo período exigido por requisitos regulatórios e de auditoria?",
    description: "Avalia a política de retenção de logs de observabilidade de IA.",
    objective: "Verificar a conformidade da retenção de logs de monitoramento.",
    justification: "A retenção adequada é essencial para auditorias regulatórias e investigação de incidentes.",
    marketReference: "BACEN Res. 4.893; ISO/IEC 27001 — A.12",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 9,
    text: "Existem SLAs e SLIs definidos para as soluções de IA em produção, com acompanhamento sistemático?",
    description: "Cobre a definição e o acompanhamento de níveis de serviço para soluções de IA.",
    objective: "Avaliar a gestão de níveis de serviço das soluções de IA.",
    justification: "SLAs claros alinham expectativas e disciplinam a operação e a melhoria contínua.",
    marketReference: "ITIL 4 — Service Level Management",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 10,
    text: "Qual a abordagem predominante para a resposta a alertas de degradação de modelos?",
    description: "Identifica o nível de automação e estruturação da resposta a incidentes de modelos.",
    objective: "Compreender a maturidade da resposta a alertas de observabilidade.",
    justification: "Respostas manuais e reativas ampliam o tempo de exposição a riscos e impactos.",
    marketReference: "ITIL 4; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Resposta manual reativa", "Runbooks documentados", "Resposta parcialmente automatizada", "Remediação automatizada", "Não há processo definido"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 11,
    text: "A observabilidade abrange métricas de qualidade e custo das aplicações baseadas em LLMs (latência, tokens, qualidade)?",
    description: "Cobre o monitoramento específico das dimensões operacionais de aplicações com LLMs.",
    objective: "Avaliar a observabilidade específica das aplicações de LLM.",
    justification: "Aplicações de LLM exigem monitoramento próprio de custo, latência e qualidade das respostas.",
    marketReference: "OWASP Top 10 for LLM; FinOps Foundation",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 12,
    text: "Os dados de monitoramento realimentam o ciclo de melhoria contínua e retreinamento dos modelos?",
    description: "Avalia a integração da observabilidade ao ciclo de vida e melhoria dos modelos.",
    objective: "Verificar o fechamento do loop entre monitoramento e melhoria de modelos.",
    justification: "Monitorar sem realimentar o ciclo de melhoria desperdiça informação valiosa e perpetua problemas.",
    marketReference: "ISO/IEC 23894; NIST AI RMF 1.0 — MANAGE",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 13,
    text: "Existe monitoramento de segurança específico para detectar ataques adversariais e comportamentos anômalos em IA?",
    description: "Cobre a detecção de ameaças de segurança direcionadas a modelos em produção.",
    objective: "Avaliar o monitoramento de segurança dos modelos de IA.",
    justification: "Ataques como evasão e extração de modelos exigem detecção específica além do monitoramento tradicional.",
    marketReference: "MITRE ATLAS; OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 14,
    text: "A organização utiliza uma plataforma centralizada de observabilidade para consolidar métricas e logs de IA?",
    description: "Avalia a centralização das ferramentas de observabilidade de IA.",
    objective: "Verificar a consolidação das capacidades de observabilidade.",
    justification: "A centralização facilita correlação, diagnóstico e visão unificada da saúde das soluções.",
    marketReference: "ITIL 4; COBIT 2019 — MEA01",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "monitoramento-observabilidade",
    order: 15,
    text: "As métricas de observabilidade de IA são reportadas periodicamente às instâncias de governança e risco?",
    description: "Cobre o reporte estruturado de métricas de IA aos órgãos de governança.",
    objective: "Avaliar o reporte de observabilidade à governança e gestão de risco.",
    justification: "O reporte estruturado sustenta a supervisão executiva e a tomada de decisão baseada em evidências.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; COBIT 2019 — EDM05",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
];
