import type { CorpQuestionSeed } from "./types";

export const QUESTIONS_P2: CorpQuestionSeed[] = [
  // ── Governança de Dados ─────────────────────────────────────────────────────
  {
    domainSlug: "governanca-dados",
    order: 1,
    text: "A organização possui um programa formal de governança de dados com patrocínio executivo e papéis definidos (CDO, data owners, data stewards)?",
    description: "Avalia a existência de uma estrutura formal de governança de dados com responsabilidades atribuídas.",
    objective: "Verificar a maturidade da estrutura organizacional que governa os dados que alimentam a IA.",
    justification: "Sem papéis claros de propriedade e curadoria, os dados usados em IA carecem de accountability, comprometendo qualidade e conformidade.",
    marketReference: "DAMA-DMBOK; COBIT 2019",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "governanca-dados",
    order: 2,
    text: "Em que nível a organização mantém um catálogo de dados corporativo atualizado e acessível às equipes de IA?",
    description: "Avalia a existência e a maturidade de um catálogo de dados que documenta os ativos de dados disponíveis.",
    objective: "Medir a capacidade de descoberta e reuso de ativos de dados para iniciativas de IA.",
    justification: "Um catálogo de dados reduz retrabalho, acelera projetos de IA e evita o uso de fontes não confiáveis.",
    marketReference: "DAMA-DMBOK; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 3,
    text: "A linhagem (data lineage) dos dados que alimentam modelos de IA é rastreável de ponta a ponta?",
    description: "Verifica a capacidade de rastrear a origem, transformações e destino dos dados usados em modelos.",
    objective: "Avaliar a rastreabilidade dos dados desde a fonte até o consumo pelos modelos.",
    justification: "A linhagem é essencial para auditoria, reprodutibilidade e resposta a incidentes regulatórios de IA.",
    marketReference: "DAMA-DMBOK; BACEN Res. 4.893",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 4,
    text: "Existe uma classificação de dados (público, interno, confidencial, restrito) aplicada aos conjuntos de dados usados em IA?",
    description: "Avalia se os dados são classificados quanto à sensibilidade e criticidade.",
    objective: "Verificar a aplicação de esquemas de classificação para orientar controles de proteção.",
    justification: "A classificação orienta controles de acesso, criptografia e conformidade, mitigando riscos de exposição.",
    marketReference: "ISO/IEC 27001; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 5,
    text: "Como a organização gerencia o ciclo de vida dos dados (criação, uso, arquivamento e descarte) para dados usados em IA?",
    description: "Avalia a existência de políticas de retenção e descarte seguro de dados.",
    objective: "Medir a maturidade da gestão do ciclo de vida dos dados.",
    justification: "A gestão adequada de retenção reduz custos, riscos de conformidade e exposição de dados obsoletos.",
    marketReference: "DAMA-DMBOK; LGPD Art. 15",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 6,
    text: "Qual é o modelo predominante de governança de dados adotado pela organização?",
    description: "Identifica a abordagem organizacional de governança de dados.",
    objective: "Caracterizar o modelo operacional de governança de dados vigente.",
    justification: "O modelo de governança influencia a escalabilidade e a consistência do uso de dados em IA.",
    marketReference: "DAMA-DMBOK; TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Centralizado", "Descentralizado", "Federado / híbrido", "Inexistente"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 7,
    text: "Existem definições de dados e glossário de negócio padronizados e compartilhados entre as áreas?",
    description: "Avalia a existência de um vocabulário de negócio comum para os dados.",
    objective: "Verificar a padronização semântica dos dados na organização.",
    justification: "Definições inconsistentes geram erros de interpretação em modelos e relatórios de negócio.",
    marketReference: "DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 8,
    text: "As políticas de governança de dados são revisadas e auditadas periodicamente?",
    description: "Avalia a frequência de revisão e auditoria das políticas de dados.",
    objective: "Medir a manutenção contínua da governança de dados.",
    justification: "Políticas desatualizadas perdem aderência a novos requisitos regulatórios e tecnológicos.",
    marketReference: "COBIT 2019; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 9,
    text: "Qual o percentual dos conjuntos de dados críticos para IA que possuem um data owner formalmente designado?",
    description: "Mede a cobertura de propriedade formal sobre ativos de dados críticos.",
    objective: "Quantificar a atribuição de responsabilidade sobre dados críticos.",
    justification: "A ausência de propriedade formal enfraquece a accountability sobre qualidade e conformidade dos dados.",
    marketReference: "DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 10,
    text: "Existe um comitê ou fórum de governança de dados que delibera sobre políticas, prioridades e conflitos?",
    description: "Avalia a existência de instância deliberativa de governança de dados.",
    objective: "Verificar a estrutura de tomada de decisão sobre dados.",
    justification: "Fóruns deliberativos garantem alinhamento entre áreas e resolução de conflitos de dados.",
    marketReference: "COBIT 2019; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 11,
    text: "Em que grau os metadados técnicos e de negócio são capturados e mantidos automaticamente?",
    description: "Avalia a automação da gestão de metadados.",
    objective: "Medir a maturidade da gestão de metadados na organização.",
    justification: "Metadados automatizados aumentam a confiabilidade do catálogo e a governança em escala.",
    marketReference: "DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 12,
    text: "A organização controla e governa o compartilhamento de dados com terceiros e parceiros para uso em IA?",
    description: "Avalia os controles sobre compartilhamento externo de dados.",
    objective: "Verificar a governança sobre fluxos de dados para fora da organização.",
    justification: "O compartilhamento inadequado de dados expõe a organização a riscos legais e de reputação.",
    marketReference: "LGPD Art. 46; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 13,
    text: "Há indicadores (KPIs) de governança de dados monitorados pela liderança?",
    description: "Avalia a existência de métricas de governança de dados reportadas à gestão.",
    objective: "Medir a orientação por dados da própria governança de dados.",
    justification: "KPIs permitem gestão proativa e demonstram valor da governança à alta gestão.",
    marketReference: "COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 14,
    text: "Descreva como a governança de dados está integrada ao ciclo de desenvolvimento de modelos de IA.",
    description: "Coleta descrição qualitativa da integração entre governança de dados e MLOps.",
    objective: "Compreender o grau de integração prática entre governança de dados e IA.",
    justification: "A integração garante que dados governados sejam efetivamente utilizados no desenvolvimento de modelos.",
    marketReference: "ISO/IEC 42001; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "text",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "governanca-dados",
    order: 15,
    text: "Em que nível a organização assegura conformidade de residência e soberania de dados para cargas de IA?",
    description: "Avalia controles sobre onde os dados são armazenados e processados.",
    objective: "Verificar a aderência a requisitos de localização e soberania de dados.",
    justification: "Requisitos de residência de dados impactam a conformidade regulatória e contratual em IA na nuvem.",
    marketReference: "LGPD; BACEN Res. 4.893",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Qualidade de Dados ──────────────────────────────────────────────────────
  {
    domainSlug: "qualidade-dados",
    order: 1,
    text: "A organização define e monitora dimensões de qualidade de dados (acurácia, completude, consistência, atualidade) para dados usados em IA?",
    description: "Avalia a existência de métricas formais de qualidade de dados.",
    objective: "Verificar a mensuração sistemática da qualidade dos dados.",
    justification: "Dados de baixa qualidade degradam o desempenho dos modelos e produzem decisões incorretas.",
    marketReference: "DAMA-DMBOK; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "qualidade-dados",
    order: 2,
    text: "Em que nível existem regras de qualidade de dados automatizadas e aplicadas nos pipelines de dados?",
    description: "Avalia a automação de validações de qualidade nos fluxos de dados.",
    objective: "Medir o grau de automação dos controles de qualidade de dados.",
    justification: "Validações automatizadas detectam problemas antes que impactem modelos em produção.",
    marketReference: "DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 3,
    text: "Qual o percentual dos conjuntos de dados críticos para IA que possuem perfis de qualidade (data profiling) documentados?",
    description: "Mede a cobertura de profiling sobre dados críticos.",
    objective: "Quantificar o conhecimento estrutural sobre os dados críticos.",
    justification: "O profiling revela anomalias, valores ausentes e outliers que afetam o treinamento de modelos.",
    marketReference: "DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 4,
    text: "Existe um processo formal de tratamento de incidentes e não conformidades de qualidade de dados?",
    description: "Avalia a existência de fluxo de correção de problemas de qualidade.",
    objective: "Verificar a capacidade de remediar problemas de qualidade identificados.",
    justification: "Sem um processo de remediação, problemas de qualidade se acumulam e comprometem a confiança nos dados.",
    marketReference: "DAMA-DMBOK; ITIL",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 5,
    text: "A qualidade dos dados de entrada dos modelos em produção é monitorada continuamente para detectar degradação?",
    description: "Avalia o monitoramento contínuo de qualidade em produção.",
    objective: "Medir a detecção de degradação de qualidade de dados em tempo de execução.",
    justification: "Mudanças na qualidade dos dados de entrada causam drift e queda de desempenho dos modelos.",
    marketReference: "NIST AI RMF 1.0 — MEASURE; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 6,
    text: "Qual abordagem a organização utiliza predominantemente para medir a qualidade de dados?",
    description: "Identifica a abordagem de mensuração de qualidade de dados.",
    objective: "Caracterizar a maturidade dos métodos de medição de qualidade.",
    justification: "Métodos manuais e reativos limitam a escalabilidade e a confiabilidade da qualidade de dados.",
    marketReference: "DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Manual e ad hoc", "Verificações periódicas", "Automatizada em pipelines", "Contínua com observabilidade de dados"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 7,
    text: "Existem SLAs de qualidade de dados acordados entre produtores e consumidores de dados?",
    description: "Avalia a formalização de acordos de nível de serviço para dados.",
    objective: "Verificar a existência de compromissos formais de qualidade entre áreas.",
    justification: "SLAs de dados criam accountability e expectativas claras entre produtores e consumidores.",
    marketReference: "DAMA-DMBOK; ITIL",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 8,
    text: "Em que grau a organização identifica e trata dados duplicados e realiza deduplicação (master data)?",
    description: "Avalia a gestão de dados mestres e deduplicação.",
    objective: "Medir a maturidade da gestão de dados mestres.",
    justification: "Duplicações e inconsistências de entidades geram vieses e erros em modelos de IA.",
    marketReference: "DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 9,
    text: "A organização avalia a representatividade e o balanceamento dos dados usados no treinamento de modelos?",
    description: "Avalia a análise de representatividade dos dados de treinamento.",
    objective: "Verificar a atenção a vieses de amostragem nos dados.",
    justification: "Dados não representativos introduzem viés e prejudicam a equidade das decisões de IA.",
    marketReference: "ISO/IEC 23894; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 10,
    text: "Há relatórios de qualidade de dados divulgados regularmente às áreas de negócio?",
    description: "Avalia a transparência sobre o estado da qualidade dos dados.",
    objective: "Medir a comunicação de indicadores de qualidade às partes interessadas.",
    justification: "A transparência sobre qualidade aumenta a confiança e o engajamento das áreas de negócio.",
    marketReference: "DAMA-DMBOK",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 11,
    text: "Existe rastreabilidade entre problemas de desempenho de modelos e a causa raiz na qualidade dos dados?",
    description: "Avalia a capacidade de correlacionar falhas de modelos a problemas de dados.",
    objective: "Verificar a análise de causa raiz orientada a dados.",
    justification: "Correlacionar falhas à qualidade dos dados acelera a remediação e melhora a confiabilidade dos modelos.",
    marketReference: "DAMA-DMBOK; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 12,
    text: "A organização utiliza ferramentas de observabilidade de dados para detectar anomalias automaticamente?",
    description: "Avalia a adoção de ferramentas de data observability.",
    objective: "Medir a maturidade tecnológica na detecção de anomalias de dados.",
    justification: "A observabilidade de dados permite detecção proativa de anomalias antes do impacto no negócio.",
    marketReference: "DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 13,
    text: "Em que nível os requisitos de qualidade de dados são definidos já na concepção dos casos de uso de IA?",
    description: "Avalia a incorporação de requisitos de qualidade desde o design.",
    objective: "Verificar a abordagem quality-by-design nos projetos de IA.",
    justification: "Definir qualidade desde o início reduz custos de correção e riscos de projetos de IA.",
    marketReference: "ISO/IEC 42001; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 14,
    text: "A organização mede o custo do negócio associado à má qualidade de dados (cost of poor quality)?",
    description: "Avalia a quantificação do impacto financeiro da baixa qualidade de dados.",
    objective: "Verificar a consciência sobre o impacto econômico da qualidade de dados.",
    justification: "Quantificar o custo justifica investimentos em qualidade e prioriza correções de maior impacto.",
    marketReference: "DAMA-DMBOK",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "qualidade-dados",
    order: 15,
    text: "Descreva os principais desafios de qualidade de dados que impactam as iniciativas de IA da organização.",
    description: "Coleta percepção qualitativa sobre os principais gargalos de qualidade de dados.",
    objective: "Identificar os desafios prioritários de qualidade de dados.",
    justification: "Mapear desafios orienta o roadmap de melhorias de qualidade de dados.",
    marketReference: "DAMA-DMBOK",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Arquitetura e Plataforma de Dados ───────────────────────────────────────
  {
    domainSlug: "arquitetura-dados",
    order: 1,
    text: "A organização possui uma plataforma de dados centralizada (data lake, lakehouse ou data warehouse) que suporta iniciativas de IA?",
    description: "Avalia a existência de uma plataforma de dados consolidada para IA.",
    objective: "Verificar a base tecnológica de armazenamento e processamento de dados para IA.",
    justification: "Uma plataforma consolidada evita silos e viabiliza a escala de projetos de IA.",
    marketReference: "TOGAF; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 2,
    text: "Em que nível os pipelines de dados são automatizados, versionados e orquestrados?",
    description: "Avalia a maturidade da automação e orquestração de pipelines de dados.",
    objective: "Medir a industrialização dos fluxos de dados que abastecem a IA.",
    justification: "Pipelines automatizados e versionados garantem reprodutibilidade e confiabilidade dos dados.",
    marketReference: "TOGAF; DAMA-DMBOK",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 3,
    text: "A organização utiliza um feature store para reutilização e consistência de features entre modelos?",
    description: "Avalia a adoção de repositórios de features para IA.",
    objective: "Verificar a padronização e reuso de features de machine learning.",
    justification: "Feature stores reduzem retrabalho e evitam divergência entre features de treino e produção.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 4,
    text: "Qual o paradigma arquitetural predominante da plataforma de dados da organização?",
    description: "Identifica o estilo arquitetural adotado para a plataforma de dados.",
    objective: "Caracterizar a arquitetura de dados vigente.",
    justification: "O paradigma arquitetural impacta escalabilidade, governança e agilidade das iniciativas de IA.",
    marketReference: "TOGAF; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Data warehouse tradicional", "Data lake", "Lakehouse", "Data mesh", "Arquitetura fragmentada / silos"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 5,
    text: "A arquitetura de dados suporta processamento em tempo real (streaming) para casos de uso de IA?",
    description: "Avalia a capacidade de processamento de dados em tempo real.",
    objective: "Verificar o suporte a cargas de trabalho de IA em tempo real.",
    justification: "Casos de uso como detecção de fraude e recomendação dependem de dados em tempo real.",
    marketReference: "TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 6,
    text: "Em que grau a plataforma de dados é escalável elasticamente para atender picos de cargas de IA?",
    description: "Avalia a elasticidade e escalabilidade da infraestrutura de dados.",
    objective: "Medir a capacidade de escalar recursos conforme a demanda.",
    justification: "A escalabilidade elástica evita gargalos e otimiza custos em treinamento e inferência.",
    marketReference: "TOGAF; FinOps Foundation",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 7,
    text: "A organização adota padrões de integração de dados (APIs, CDC, ETL/ELT) documentados e reutilizáveis?",
    description: "Avalia a padronização dos mecanismos de integração de dados.",
    objective: "Verificar a consistência e reuso dos padrões de integração.",
    justification: "Padrões de integração reduzem complexidade e aceleram a entrega de dados para IA.",
    marketReference: "TOGAF; DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 8,
    text: "Qual o percentual das fontes de dados críticas já integradas à plataforma de dados corporativa?",
    description: "Mede a cobertura de integração das fontes de dados críticas.",
    objective: "Quantificar o grau de consolidação das fontes de dados.",
    justification: "Fontes não integradas geram silos e limitam a abrangência dos modelos de IA.",
    marketReference: "DAMA-DMBOK",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 9,
    text: "A arquitetura de dados incorpora ambientes segregados de desenvolvimento, homologação e produção?",
    description: "Avalia a segregação de ambientes na plataforma de dados.",
    objective: "Verificar o isolamento adequado entre ambientes.",
    justification: "A segregação de ambientes reduz riscos operacionais e protege dados de produção.",
    marketReference: "ISO/IEC 27001; TOGAF",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 10,
    text: "Em que nível a plataforma de dados oferece observabilidade sobre custos, desempenho e disponibilidade?",
    description: "Avalia a observabilidade operacional da plataforma de dados.",
    objective: "Medir a capacidade de monitorar a saúde da plataforma de dados.",
    justification: "A observabilidade permite gestão proativa de desempenho, custos e disponibilidade.",
    marketReference: "FinOps Foundation; TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 11,
    text: "A arquitetura de dados está documentada em blueprints e diagramas mantidos atualizados?",
    description: "Avalia a documentação arquitetural da plataforma de dados.",
    objective: "Verificar a existência e manutenção de artefatos de arquitetura.",
    justification: "Documentação atualizada facilita evolução, auditoria e onboarding de equipes.",
    marketReference: "TOGAF",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 12,
    text: "A plataforma de dados suporta cargas de trabalho de GenAI, incluindo bancos vetoriais e embeddings?",
    description: "Avalia o suporte da arquitetura a workloads de IA generativa.",
    objective: "Verificar a preparação da plataforma para casos de uso de GenAI.",
    justification: "Casos de uso de GenAI e RAG exigem armazenamento vetorial e pipelines específicos.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 13,
    text: "Existe uma estratégia de nuvem (cloud, híbrida ou multicloud) definida para as cargas de dados e IA?",
    description: "Avalia a definição da estratégia de infraestrutura em nuvem para dados.",
    objective: "Verificar o alinhamento da arquitetura de dados à estratégia de nuvem.",
    justification: "Uma estratégia de nuvem clara evita lock-in indesejado e otimiza custos e resiliência.",
    marketReference: "TOGAF; FinOps Foundation",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 14,
    text: "Em que grau a arquitetura de dados incorpora princípios de segurança e privacidade desde o design?",
    description: "Avalia a incorporação de security e privacy by design na arquitetura.",
    objective: "Verificar a integração de controles de segurança na arquitetura de dados.",
    justification: "Segurança e privacidade embutidas na arquitetura reduzem riscos e custos de retrofit.",
    marketReference: "ISO/IEC 27001; LGPD Art. 46",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "arquitetura-dados",
    order: 15,
    text: "A organização possui uma função de arquitetura de dados que governa padrões e decisões arquiteturais?",
    description: "Avalia a existência de governança arquitetural de dados.",
    objective: "Verificar a estrutura que assegura consistência arquitetural.",
    justification: "A governança arquitetural evita proliferação de soluções inconsistentes e dívida técnica.",
    marketReference: "TOGAF; COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── Privacidade e LGPD ──────────────────────────────────────────────────────
  {
    domainSlug: "privacidade-lgpd",
    order: 1,
    text: "A organização mantém registro das operações de tratamento de dados pessoais (RoPA) que envolvem sistemas de IA?",
    description: "Avalia a existência de registro das atividades de tratamento conforme a LGPD.",
    objective: "Verificar a documentação das operações de tratamento em IA.",
    justification: "O registro de tratamento é exigência legal e base para demonstração de conformidade à ANPD.",
    marketReference: "LGPD Art. 37; ISO/IEC 27701",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 2,
    text: "É realizado Relatório de Impacto à Proteção de Dados (RIPD/DPIA) para projetos de IA de alto risco?",
    description: "Avalia a realização de avaliações de impacto à privacidade em IA.",
    objective: "Verificar a análise de riscos de privacidade em projetos de IA sensíveis.",
    justification: "O RIPD identifica e mitiga riscos à privacidade antes da implantação de sistemas de IA.",
    marketReference: "LGPD Art. 38; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 3,
    text: "A organização define e documenta a base legal para cada tratamento de dados pessoais em iniciativas de IA?",
    description: "Avalia a definição de bases legais para o tratamento em IA.",
    objective: "Verificar a fundamentação legal dos tratamentos de dados em IA.",
    justification: "Tratamentos sem base legal adequada expõem a organização a sanções e nulidade de decisões.",
    marketReference: "LGPD Art. 7; LGPD Art. 11",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 4,
    text: "Existem mecanismos para atender aos direitos dos titulares (acesso, correção, eliminação, oposição) em sistemas de IA?",
    description: "Avalia a capacidade de atender às solicitações dos titulares de dados.",
    objective: "Verificar a operacionalização dos direitos dos titulares em contextos de IA.",
    justification: "A LGPD garante direitos aos titulares e a incapacidade de atendê-los gera não conformidade.",
    marketReference: "LGPD Art. 18",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 5,
    text: "Em que grau a organização aplica minimização de dados pessoais no treinamento e operação de modelos?",
    description: "Avalia a aplicação do princípio da minimização de dados.",
    objective: "Verificar a limitação do uso de dados pessoais ao estritamente necessário.",
    justification: "A minimização reduz a superfície de risco e é princípio fundamental da LGPD.",
    marketReference: "LGPD Art. 6; ISO/IEC 27701",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 6,
    text: "A organização utiliza técnicas de anonimização ou pseudonimização em dados pessoais usados em IA?",
    description: "Avalia o uso de técnicas de descaracterização de dados pessoais.",
    objective: "Verificar a adoção de técnicas que reduzem a identificabilidade dos dados.",
    justification: "Anonimização e pseudonimização mitigam riscos de reidentificação e vazamento.",
    marketReference: "LGPD Art. 12; ISO/IEC 27701",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 7,
    text: "Qual o percentual dos sistemas de IA que tratam dados pessoais e já passaram por avaliação de privacidade?",
    description: "Mede a cobertura de avaliações de privacidade sobre sistemas de IA.",
    objective: "Quantificar a abrangência das avaliações de privacidade.",
    justification: "Sistemas não avaliados representam risco desconhecido de não conformidade à LGPD.",
    marketReference: "LGPD Art. 38",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 8,
    text: "A organização possui um Encarregado de Dados (DPO) atuante envolvido nas iniciativas de IA?",
    description: "Avalia a existência e atuação do DPO em projetos de IA.",
    objective: "Verificar o envolvimento do Encarregado nas decisões de IA.",
    justification: "O DPO é exigência da LGPD e ponto focal para conformidade em privacidade de IA.",
    marketReference: "LGPD Art. 41",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 9,
    text: "Como a organização obtém e gerencia o consentimento quando essa é a base legal aplicável em IA?",
    description: "Avalia a gestão de consentimento dos titulares.",
    objective: "Caracterizar a maturidade da gestão de consentimento.",
    justification: "O consentimento inadequado invalida o tratamento e expõe a organização a sanções.",
    marketReference: "LGPD Art. 8",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Não gerenciado", "Consentimento manual/papel", "Plataforma de consentimento parcial", "Plataforma centralizada de consentimento", "Não aplicável (outras bases legais)"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 10,
    text: "Em que nível a privacidade é considerada desde a concepção (privacy by design) nos projetos de IA?",
    description: "Avalia a incorporação de privacy by design no ciclo de vida de IA.",
    objective: "Verificar a integração da privacidade desde o design dos sistemas de IA.",
    justification: "Privacy by design reduz riscos e custos de adequação posterior à LGPD.",
    marketReference: "LGPD Art. 46; ISO/IEC 27701",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 11,
    text: "Há controles específicos para o tratamento de dados pessoais sensíveis em modelos de IA?",
    description: "Avalia controles reforçados para dados sensíveis.",
    objective: "Verificar a proteção diferenciada de dados sensíveis.",
    justification: "Dados sensíveis têm regime jurídico mais restritivo e maior potencial de dano.",
    marketReference: "LGPD Art. 11",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 12,
    text: "As transferências internacionais de dados pessoais para serviços de IA seguem os requisitos da LGPD?",
    description: "Avalia a conformidade das transferências internacionais de dados.",
    objective: "Verificar a adequação de transferências transfronteiriças em IA.",
    justification: "O uso de provedores de IA no exterior exige salvaguardas legais para transferência de dados.",
    marketReference: "LGPD Art. 33",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 13,
    text: "A organização avalia o risco de reidentificação de titulares a partir das saídas de modelos de IA?",
    description: "Avalia a atenção ao risco de reidentificação via inferência de modelos.",
    objective: "Verificar a análise de riscos de reidentificação em IA.",
    justification: "Modelos podem inferir ou memorizar dados pessoais, expondo titulares a reidentificação.",
    marketReference: "LGPD; ISO/IEC 27701",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 14,
    text: "Existe governança sobre o uso de dados pessoais de clientes em ferramentas de IA generativa de terceiros?",
    description: "Avalia controles sobre inserção de dados pessoais em serviços de GenAI.",
    objective: "Verificar a governança sobre GenAI e privacidade.",
    justification: "O uso descontrolado de GenAI pode vazar dados pessoais a provedores externos.",
    marketReference: "LGPD Art. 46; OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "privacidade-lgpd",
    order: 15,
    text: "Descreva como a organização integra os requisitos de privacidade ao ciclo de vida de desenvolvimento de IA.",
    description: "Coleta descrição qualitativa da integração entre privacidade e desenvolvimento de IA.",
    objective: "Compreender a operacionalização da privacidade no desenvolvimento de IA.",
    justification: "A integração prática assegura conformidade contínua e reduz riscos regulatórios.",
    marketReference: "LGPD; ISO/IEC 42001",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Segurança de Dados ──────────────────────────────────────────────────────
  {
    domainSlug: "seguranca-dados",
    order: 1,
    text: "Os dados usados em IA são criptografados em repouso e em trânsito com padrões corporativos?",
    description: "Avalia a aplicação de criptografia aos dados de IA.",
    objective: "Verificar a proteção criptográfica dos dados em todos os estados.",
    justification: "A criptografia protege contra acesso não autorizado e é requisito básico de segurança e conformidade.",
    marketReference: "ISO/IEC 27001; LGPD Art. 46",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "seguranca-dados",
    order: 2,
    text: "Em que nível o controle de acesso aos dados segue o princípio do menor privilégio e é baseado em papéis (RBAC/ABAC)?",
    description: "Avalia a maturidade dos controles de acesso a dados.",
    objective: "Verificar a granularidade e o rigor dos controles de acesso.",
    justification: "O menor privilégio reduz a superfície de exposição e o risco de acesso indevido a dados sensíveis.",
    marketReference: "ISO/IEC 27001; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 3,
    text: "A organização aplica mascaramento ou tokenização de dados sensíveis em ambientes não produtivos?",
    description: "Avalia a proteção de dados sensíveis em desenvolvimento e testes.",
    objective: "Verificar a descaracterização de dados fora de produção.",
    justification: "Dados reais em ambientes de teste ampliam a superfície de vazamento e risco de conformidade.",
    marketReference: "ISO/IEC 27001; LGPD",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 4,
    text: "Existem controles de prevenção de vazamento de dados (DLP) aplicados aos fluxos de dados de IA?",
    description: "Avalia a adoção de soluções de DLP nos fluxos de dados.",
    objective: "Verificar a capacidade de prevenir exfiltração de dados.",
    justification: "O DLP detecta e bloqueia transferências não autorizadas de dados sensíveis.",
    marketReference: "ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 5,
    text: "Os acessos a dados sensíveis são registrados em logs auditáveis e monitorados?",
    description: "Avalia o registro e monitoramento de acessos a dados.",
    objective: "Verificar a auditabilidade dos acessos a dados sensíveis.",
    justification: "Logs de acesso permitem detecção de anomalias e apoiam investigações de incidentes.",
    marketReference: "ISO/IEC 27001; BACEN Res. 4.893",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 6,
    text: "Como a organização gerencia chaves criptográficas (KMS) usadas na proteção de dados de IA?",
    description: "Identifica a abordagem de gestão de chaves criptográficas.",
    objective: "Caracterizar a maturidade da gestão de chaves.",
    justification: "A gestão inadequada de chaves compromete toda a proteção criptográfica dos dados.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Sem gestão formal de chaves", "Gestão manual", "KMS gerenciado por provedor", "KMS com HSM e rotação automática"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 7,
    text: "Qual o percentual dos repositórios de dados sensíveis com controles de acesso revisados periodicamente?",
    description: "Mede a cobertura de revisões de acesso sobre dados sensíveis.",
    objective: "Quantificar a manutenção dos controles de acesso.",
    justification: "Acessos não revisados acumulam privilégios excessivos e aumentam o risco de vazamento.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 8,
    text: "Em que grau a organização protege dados durante o treinamento de modelos contra acesso de equipes não autorizadas?",
    description: "Avalia a segurança dos dados durante o processo de treinamento.",
    objective: "Verificar os controles de acesso no ambiente de treinamento.",
    justification: "Ambientes de treinamento concentram grandes volumes de dados e são alvos atrativos.",
    marketReference: "ISO/IEC 27001; MITRE ATLAS",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 9,
    text: "Existem controles para proteção de dados em bancos vetoriais e embeddings usados em RAG/GenAI?",
    description: "Avalia a segurança de armazenamentos vetoriais.",
    objective: "Verificar a proteção de dados em arquiteturas de GenAI.",
    justification: "Embeddings podem revelar informações sensíveis e exigem controles de segurança específicos.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 10,
    text: "A organização realiza backups seguros e testa a restauração dos dados críticos de IA?",
    description: "Avalia a estratégia de backup e recuperação de dados.",
    objective: "Verificar a resiliência dos dados críticos a perdas.",
    justification: "Backups testados garantem recuperação após incidentes de ransomware ou falhas.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 11,
    text: "Há segregação de rede e isolamento dos ambientes que processam dados sensíveis de IA?",
    description: "Avalia o isolamento de rede dos ambientes de dados.",
    objective: "Verificar a segmentação de rede para proteção de dados.",
    justification: "A segmentação limita o movimento lateral de atacantes e contém incidentes.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 12,
    text: "A organização monitora e controla o uso de dados por contas de serviço e credenciais de aplicações de IA?",
    description: "Avalia a gestão de identidades não humanas com acesso a dados.",
    objective: "Verificar o controle sobre credenciais de máquina.",
    justification: "Contas de serviço com privilégios excessivos são vetores frequentes de vazamento de dados.",
    marketReference: "ISO/IEC 27001; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 13,
    text: "Em que nível a política de descarte seguro de dados é aplicada a mídias e ambientes de IA?",
    description: "Avalia a aplicação de descarte seguro de dados.",
    objective: "Verificar a eliminação segura de dados obsoletos.",
    justification: "O descarte inadequado pode expor dados sensíveis armazenados em mídias descomissionadas.",
    marketReference: "ISO/IEC 27001; LGPD Art. 15",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 14,
    text: "A organização classifica e protege dados conforme sua sensibilidade em todo o pipeline de IA?",
    description: "Avalia a aplicação consistente de controles por nível de sensibilidade.",
    objective: "Verificar a proteção proporcional à sensibilidade dos dados.",
    justification: "Controles proporcionais à sensibilidade otimizam segurança e custo.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-dados",
    order: 15,
    text: "Os controles de segurança de dados são auditados por área independente ou avaliação externa?",
    description: "Avalia a verificação independente dos controles de segurança de dados.",
    objective: "Verificar a validação externa/independente da segurança de dados.",
    justification: "Auditorias independentes aumentam a confiança e identificam lacunas não percebidas internamente.",
    marketReference: "ISO/IEC 27001; COBIT 2019",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },

  // ── Segurança de IA ─────────────────────────────────────────────────────────
  {
    domainSlug: "seguranca-ia",
    order: 1,
    text: "A organização possui controles para detectar e mitigar ataques de prompt injection em aplicações de LLM?",
    description: "Avalia a proteção contra injeção de prompts maliciosos.",
    objective: "Verificar a defesa contra manipulação de instruções de LLMs.",
    justification: "Prompt injection pode levar a vazamento de dados, execução de ações não autorizadas e bypass de guardrails.",
    marketReference: "OWASP Top 10 for LLM; MITRE ATLAS",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "seguranca-ia",
    order: 2,
    text: "Em que nível a organização protege modelos contra envenenamento de dados (data poisoning) no treinamento?",
    description: "Avalia a proteção contra manipulação maliciosa dos dados de treinamento.",
    objective: "Verificar controles de integridade dos dados de treinamento.",
    justification: "O envenenamento de dados compromete a integridade dos modelos e pode inserir backdoors.",
    marketReference: "MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 3,
    text: "Existem controles para prevenir extração de modelos (model extraction) e roubo de propriedade intelectual?",
    description: "Avalia a proteção contra reconstrução não autorizada de modelos.",
    objective: "Verificar defesas contra roubo de modelos via consultas.",
    justification: "A extração de modelos expõe propriedade intelectual e viabiliza ataques adversariais posteriores.",
    marketReference: "MITRE ATLAS",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 4,
    text: "A organização avalia a robustez dos modelos contra exemplos adversariais (adversarial evasion)?",
    description: "Avalia testes de robustez adversarial dos modelos.",
    objective: "Verificar a resistência dos modelos a entradas manipuladas.",
    justification: "Ataques de evasão podem enganar modelos críticos, como detecção de fraude e biometria.",
    marketReference: "MITRE ATLAS; ISO/IEC 23894",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 5,
    text: "Existem guardrails e filtros de conteúdo aplicados às entradas e saídas de modelos generativos?",
    description: "Avalia a existência de guardrails em aplicações de GenAI.",
    objective: "Verificar controles sobre entradas e saídas de LLMs.",
    justification: "Guardrails previnem geração de conteúdo tóxico, vazamento de dados e uso indevido.",
    marketReference: "OWASP Top 10 for LLM; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 6,
    text: "Qual framework de ameaças de IA a organização utiliza como referência para modelagem de ameaças?",
    description: "Identifica o framework de ameaças de IA adotado.",
    objective: "Caracterizar a abordagem de modelagem de ameaças de IA.",
    justification: "Frameworks padronizados garantem cobertura abrangente das ameaças específicas de IA.",
    marketReference: "MITRE ATLAS; OWASP Top 10 for LLM; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Nenhum", "MITRE ATLAS", "OWASP Top 10 for LLM", "NIST AI RMF", "Framework próprio"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 7,
    text: "A organização protege-se contra ataques de inferência de associação (membership inference) que expõem dados de treinamento?",
    description: "Avalia a proteção contra inferência sobre dados de treinamento.",
    objective: "Verificar defesas contra vazamento de dados via inferência.",
    justification: "Ataques de membership inference podem revelar se um indivíduo estava nos dados de treinamento.",
    marketReference: "MITRE ATLAS; LGPD",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 8,
    text: "Em que grau a integridade e a proveniência dos modelos de terceiros e open source são verificadas antes do uso?",
    description: "Avalia a verificação de modelos externos quanto a riscos de supply chain.",
    objective: "Verificar controles sobre a cadeia de suprimentos de modelos.",
    justification: "Modelos externos podem conter backdoors e vulnerabilidades que comprometem a organização.",
    marketReference: "MITRE ATLAS; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 9,
    text: "Qual o percentual dos modelos em produção que passaram por avaliação de segurança específica de IA?",
    description: "Mede a cobertura de avaliações de segurança sobre os modelos.",
    objective: "Quantificar a abrangência das avaliações de segurança de IA.",
    justification: "Modelos não avaliados representam riscos de segurança desconhecidos em produção.",
    marketReference: "MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 10,
    text: "A organização monitora as saídas dos modelos em produção para detectar comportamentos anômalos ou maliciosos?",
    description: "Avalia o monitoramento de segurança das saídas dos modelos.",
    objective: "Verificar a detecção de comportamentos suspeitos em tempo de execução.",
    justification: "O monitoramento detecta abusos e ataques em andamento contra os modelos.",
    marketReference: "MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 11,
    text: "Existem controles contra ataques de negação de serviço específicos de IA (model DoS, consumo excessivo de recursos)?",
    description: "Avalia a proteção contra sobrecarga e consumo excessivo de modelos.",
    objective: "Verificar defesas contra exaustão de recursos de IA.",
    justification: "Ataques de DoS a modelos elevam custos e degradam a disponibilidade de serviços críticos.",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 12,
    text: "A segurança de IA é integrada à estratégia corporativa de cibersegurança e ao SOC?",
    description: "Avalia a integração da segurança de IA à função de cibersegurança.",
    objective: "Verificar o alinhamento entre segurança de IA e cibersegurança corporativa.",
    justification: "A integração evita lacunas de cobertura e aproveita capacidades existentes de segurança.",
    marketReference: "ISO/IEC 27001; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 13,
    text: "Em que nível a organização controla o acesso e o uso de modelos por meio de autenticação e autorização robustas?",
    description: "Avalia os controles de acesso às APIs e endpoints de modelos.",
    objective: "Verificar a proteção de acesso aos modelos.",
    justification: "O acesso não controlado a modelos facilita abuso, extração e ataques adversariais.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 14,
    text: "A organização realiza exercícios de red team focados em ameaças específicas de IA?",
    description: "Avalia a realização de red teaming direcionado a IA.",
    objective: "Verificar a validação ofensiva da segurança dos sistemas de IA.",
    justification: "O red teaming revela vulnerabilidades reais antes que sejam exploradas por atacantes.",
    marketReference: "MITRE ATLAS; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-ia",
    order: 15,
    text: "Descreva as principais ameaças de segurança de IA priorizadas pela organização e as respectivas mitigações.",
    description: "Coleta descrição qualitativa das ameaças e mitigações de segurança de IA.",
    objective: "Compreender a priorização e o tratamento de ameaças de IA.",
    justification: "Mapear ameaças e mitigações demonstra maturidade e orienta investimentos em segurança de IA.",
    marketReference: "MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Segurança de Aplicações de IA ───────────────────────────────────────────
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 1,
    text: "A organização adota práticas de desenvolvimento seguro (Secure SDLC) para aplicações que incorporam IA?",
    description: "Avalia a integração de segurança ao ciclo de desenvolvimento de aplicações de IA.",
    objective: "Verificar a maturidade do SDLC seguro em aplicações de IA.",
    justification: "Aplicações de IA herdam riscos de software tradicional somados a riscos específicos de IA.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 2,
    text: "Em que nível as APIs que expõem modelos de IA possuem autenticação, autorização e rate limiting?",
    description: "Avalia os controles de segurança das APIs de modelos.",
    objective: "Verificar a proteção das interfaces de acesso aos modelos.",
    justification: "APIs desprotegidas expõem modelos a abuso, extração e consumo excessivo de recursos.",
    marketReference: "OWASP Top 10 for LLM; OWASP API Security",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 3,
    text: "As entradas fornecidas pelos usuários às aplicações de IA são validadas e sanitizadas?",
    description: "Avalia a validação de entradas em aplicações de IA.",
    objective: "Verificar a proteção contra entradas maliciosas.",
    justification: "A validação de entradas mitiga injeções, prompt injection e outros ataques de aplicação.",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 4,
    text: "As saídas dos modelos são tratadas de forma segura antes de serem consumidas por sistemas downstream?",
    description: "Avalia o tratamento seguro das saídas de modelos.",
    objective: "Verificar a prevenção de exploração via saídas de modelos.",
    justification: "Saídas não tratadas podem conter payloads que comprometem sistemas consumidores (insecure output handling).",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 5,
    text: "A organização gerencia com segurança segredos, chaves de API e credenciais usados por aplicações de IA?",
    description: "Avalia a gestão de segredos em aplicações de IA.",
    objective: "Verificar a proteção de credenciais e segredos.",
    justification: "Segredos expostos em código ou logs permitem acesso não autorizado a modelos e dados.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 6,
    text: "Quais práticas de teste de segurança são aplicadas às aplicações de IA antes da implantação?",
    description: "Identifica as práticas de teste de segurança adotadas.",
    objective: "Caracterizar a cobertura de testes de segurança de aplicações de IA.",
    justification: "Testes de segurança revelam vulnerabilidades antes da exposição em produção.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Nenhum teste específico", "Análise estática (SAST)", "Análise dinâmica (DAST)", "SAST + DAST + testes de IA", "Red teaming de aplicações de IA"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 7,
    text: "A organização gerencia a segurança das dependências e componentes open source usados em aplicações de IA?",
    description: "Avalia a gestão de riscos da cadeia de suprimentos de software.",
    objective: "Verificar o controle sobre dependências de terceiros.",
    justification: "Dependências vulneráveis são vetor comum de comprometimento de aplicações.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 8,
    text: "Existem controles sobre a excessiva agência (excessive agency) de aplicações de IA que executam ações automatizadas?",
    description: "Avalia os limites de ação de aplicações de IA autônomas.",
    objective: "Verificar controles sobre permissões e autonomia de aplicações de IA.",
    justification: "Aplicações com autonomia excessiva podem executar ações danosas sem supervisão adequada.",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 9,
    text: "Qual o percentual das aplicações de IA em produção com testes de segurança executados no pipeline de CI/CD?",
    description: "Mede a cobertura de testes de segurança automatizados.",
    objective: "Quantificar a automação de segurança no pipeline de entrega.",
    justification: "Testes integrados ao CI/CD garantem verificação contínua de segurança em cada release.",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 10,
    text: "A organização registra logs de segurança das aplicações de IA de forma auditável e monitorada?",
    description: "Avalia o logging de segurança das aplicações de IA.",
    objective: "Verificar a auditabilidade e o monitoramento das aplicações.",
    justification: "Logs de segurança permitem detecção de ataques e apoiam a resposta a incidentes.",
    marketReference: "ISO/IEC 27001; OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 11,
    text: "Há segregação de ambientes e controles de acesso ao código-fonte das aplicações de IA?",
    description: "Avalia a proteção do código-fonte e dos ambientes de desenvolvimento.",
    objective: "Verificar controles sobre o repositório e os ambientes de aplicações de IA.",
    justification: "O acesso indevido ao código pode expor segredos e viabilizar sabotagem.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 12,
    text: "As equipes de desenvolvimento recebem treinamento em segurança de aplicações de IA?",
    description: "Avalia a capacitação em segurança das equipes de desenvolvimento.",
    objective: "Verificar a conscientização e competência em segurança de IA.",
    justification: "Desenvolvedores treinados previnem vulnerabilidades desde o código.",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 13,
    text: "A organização aplica princípios de zero trust na arquitetura das aplicações de IA?",
    description: "Avalia a adoção de arquitetura zero trust.",
    objective: "Verificar a maturidade dos princípios de zero trust nas aplicações de IA.",
    justification: "Zero trust reduz a superfície de ataque e limita o impacto de comprometimentos.",
    marketReference: "NIST SP 800-207; ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 14,
    text: "Existem controles para plugins, ferramentas e integrações externas acionadas por aplicações de IA?",
    description: "Avalia a segurança de plugins e integrações de agentes de IA.",
    objective: "Verificar controles sobre extensões e integrações de IA.",
    justification: "Plugins e integrações inseguros ampliam a superfície de ataque das aplicações de IA.",
    marketReference: "OWASP Top 10 for LLM",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "seguranca-aplicacoes-ia",
    order: 15,
    text: "A organização mantém inventário atualizado de todas as aplicações e componentes de IA em produção?",
    description: "Avalia a existência de inventário de aplicações de IA.",
    objective: "Verificar a visibilidade sobre o parque de aplicações de IA.",
    justification: "Sem inventário, aplicações não gerenciadas (shadow AI) escapam dos controles de segurança.",
    marketReference: "ISO/IEC 42001; ISO/IEC 27001",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },

  // ── Gestão de Vulnerabilidades e Testes ─────────────────────────────────────
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 1,
    text: "A organização possui um processo formal de gestão de vulnerabilidades que abrange sistemas de IA?",
    description: "Avalia a existência de processo estruturado de gestão de vulnerabilidades para IA.",
    objective: "Verificar a maturidade do processo de gestão de vulnerabilidades de IA.",
    justification: "Sem um processo formal, vulnerabilidades de IA permanecem desconhecidas e não tratadas.",
    marketReference: "ISO/IEC 27001; MITRE ATLAS",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 2,
    text: "Em que nível a organização realiza testes adversariais estruturados contra seus modelos de IA?",
    description: "Avalia a maturidade dos testes adversariais.",
    objective: "Verificar a prática de testes adversariais sistemáticos.",
    justification: "Testes adversariais revelam fragilidades exploráveis antes que sejam usadas por atacantes.",
    marketReference: "MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 3,
    text: "A organização conduz exercícios de red teaming específicos para sistemas de IA de forma periódica?",
    description: "Avalia a periodicidade e o escopo do red teaming de IA.",
    objective: "Verificar a validação ofensiva contínua dos sistemas de IA.",
    justification: "O red teaming periódico acompanha a evolução das ameaças e das mudanças nos sistemas.",
    marketReference: "MITRE ATLAS; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 4,
    text: "Existe um processo de priorização e tratamento de vulnerabilidades baseado em risco (severidade e impacto)?",
    description: "Avalia a priorização baseada em risco no tratamento de vulnerabilidades.",
    objective: "Verificar a racionalidade da priorização das correções.",
    justification: "A priorização por risco garante que as vulnerabilidades mais críticas sejam tratadas primeiro.",
    marketReference: "ISO/IEC 27001; ISO/IEC 23894",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 5,
    text: "A organização define SLAs de remediação para vulnerabilidades identificadas em sistemas de IA?",
    description: "Avalia a existência de prazos formais de remediação.",
    objective: "Verificar o compromisso com prazos de correção.",
    justification: "SLAs de remediação limitam a janela de exposição a vulnerabilidades conhecidas.",
    marketReference: "ISO/IEC 27001; ITIL",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 6,
    text: "Qual a frequência com que a organização realiza avaliações de vulnerabilidades em seus sistemas de IA?",
    description: "Identifica a periodicidade das avaliações de vulnerabilidades.",
    objective: "Caracterizar a cadência das avaliações de segurança de IA.",
    justification: "Avaliações frequentes reduzem o tempo de exposição a novas vulnerabilidades.",
    marketReference: "ISO/IEC 27001; MITRE ATLAS",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Nunca ou ad hoc", "Anual", "Semestral", "Trimestral", "Contínua"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 7,
    text: "Qual o percentual das vulnerabilidades críticas de IA remediadas dentro do SLA definido?",
    description: "Mede a eficácia da remediação de vulnerabilidades críticas.",
    objective: "Quantificar o cumprimento dos prazos de remediação.",
    justification: "O cumprimento dos SLAs demonstra a efetividade operacional da gestão de vulnerabilidades.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 8,
    text: "A organização mantém testes automatizados de segurança de IA integrados aos pipelines de desenvolvimento?",
    description: "Avalia a automação de testes de segurança no ciclo de desenvolvimento.",
    objective: "Verificar a integração de testes de segurança de IA ao CI/CD.",
    justification: "Testes automatizados detectam regressões de segurança de forma contínua e escalável.",
    marketReference: "OWASP Top 10 for LLM; ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 9,
    text: "Existe monitoramento de novas vulnerabilidades e ameaças emergentes específicas de IA (threat intelligence)?",
    description: "Avalia a inteligência de ameaças aplicada a IA.",
    objective: "Verificar o acompanhamento de ameaças emergentes de IA.",
    justification: "O cenário de ameaças de IA evolui rapidamente, exigindo vigilância contínua.",
    marketReference: "MITRE ATLAS",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 10,
    text: "A organização documenta e rastreia as vulnerabilidades de IA em um repositório centralizado?",
    description: "Avalia a centralização do registro de vulnerabilidades.",
    objective: "Verificar a rastreabilidade das vulnerabilidades ao longo do ciclo de vida.",
    justification: "Um repositório centralizado garante acompanhamento e evita perda de vulnerabilidades em aberto.",
    marketReference: "ISO/IEC 27001; ITIL",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 11,
    text: "Os testes de segurança de IA cobrem cenários de viés, toxicidade e alucinação além de vulnerabilidades técnicas?",
    description: "Avalia a abrangência dos testes para riscos de IA responsável.",
    objective: "Verificar a cobertura de riscos comportamentais dos modelos.",
    justification: "Vieses, toxicidade e alucinações geram riscos legais e reputacionais além das ameaças técnicas.",
    marketReference: "NIST AI RMF 1.0; ISO/IEC 23894",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 12,
    text: "A organização engaja especialistas externos ou bug bounty para testar seus sistemas de IA?",
    description: "Avalia o uso de terceiros e programas de recompensa para descoberta de vulnerabilidades.",
    objective: "Verificar a diversificação das fontes de descoberta de vulnerabilidades.",
    justification: "Perspectivas externas ampliam a cobertura e revelam vulnerabilidades não identificadas internamente.",
    marketReference: "MITRE ATLAS",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 13,
    text: "Os resultados dos testes de vulnerabilidades de IA são reportados à liderança e aos comitês de risco?",
    description: "Avalia a comunicação dos resultados de testes à governança.",
    objective: "Verificar a visibilidade da gestão de vulnerabilidades pela liderança.",
    justification: "O reporte à liderança assegura suporte para remediação e decisões informadas de risco.",
    marketReference: "COBIT 2019; ISO/IEC 23894",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 14,
    text: "A organização valida a eficácia das remediações por meio de reteste após a correção?",
    description: "Avalia a verificação das correções aplicadas.",
    objective: "Verificar a confirmação da efetividade das remediações.",
    justification: "O reteste garante que as vulnerabilidades foram efetivamente eliminadas.",
    marketReference: "ISO/IEC 27001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-vulnerabilidades-ia",
    order: 15,
    text: "Descreva a abordagem da organização para testes contínuos de segurança e robustez dos modelos de IA.",
    description: "Coleta descrição qualitativa da estratégia de testes contínuos de IA.",
    objective: "Compreender a maturidade da estratégia de testes de segurança de IA.",
    justification: "Uma abordagem estruturada de testes contínuos sustenta a resiliência dos sistemas de IA.",
    marketReference: "MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "baixa",
    weight: 2,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── Resposta a Incidentes e Continuidade ────────────────────────────────────
  {
    domainSlug: "resposta-incidentes-ia",
    order: 1,
    text: "A organização possui um plano de resposta a incidentes que contempla especificamente incidentes de IA?",
    description: "Avalia a existência de plano de resposta a incidentes de IA.",
    objective: "Verificar a preparação formal para incidentes de IA.",
    justification: "Incidentes de IA têm particularidades que exigem procedimentos de resposta específicos.",
    marketReference: "NIST AI RMF 1.0 — MANAGE; ISO/IEC 27035",
    criticality: "critica",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 2,
    text: "Existem mecanismos de kill switch para desativar rapidamente modelos ou agentes de IA em caso de incidente?",
    description: "Avalia a capacidade de interromper sistemas de IA em emergências.",
    objective: "Verificar a existência de mecanismos de desligamento de emergência.",
    justification: "Kill switches contêm danos rapidamente quando modelos apresentam comportamento perigoso.",
    marketReference: "EU AI Act; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 3,
    text: "A organização possui capacidade de rollback para versões anteriores estáveis de modelos em produção?",
    description: "Avalia a capacidade de reverter modelos para versões estáveis.",
    objective: "Verificar a resiliência operacional por meio de rollback de modelos.",
    justification: "O rollback restaura rapidamente a operação após falhas ou degradações de modelos.",
    marketReference: "NIST AI RMF 1.0; ITIL",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 4,
    text: "Os papéis e responsabilidades para resposta a incidentes de IA estão claramente definidos e comunicados?",
    description: "Avalia a definição de papéis na resposta a incidentes de IA.",
    objective: "Verificar a clareza das responsabilidades durante incidentes.",
    justification: "Papéis definidos aceleram a resposta e evitam confusão em situações de crise.",
    marketReference: "ISO/IEC 27035; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 5,
    text: "A organização classifica e prioriza incidentes de IA por severidade e impacto no negócio?",
    description: "Avalia a categorização de incidentes de IA.",
    objective: "Verificar a existência de critérios de severidade para incidentes de IA.",
    justification: "A classificação orienta a mobilização de recursos e o acionamento de escalonamentos.",
    marketReference: "ISO/IEC 27035; ITIL",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 6,
    text: "Como a organização realiza a detecção de incidentes envolvendo sistemas de IA?",
    description: "Identifica os mecanismos de detecção de incidentes de IA.",
    objective: "Caracterizar a maturidade da detecção de incidentes de IA.",
    justification: "A detecção rápida reduz o tempo de resposta e o impacto dos incidentes de IA.",
    marketReference: "NIST AI RMF 1.0; ISO/IEC 27035",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Reativa (reclamações de usuários)", "Monitoramento manual", "Alertas automatizados parciais", "Monitoramento contínuo integrado ao SOC"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 7,
    text: "Os planos de continuidade de negócio (BCP) contemplam a indisponibilidade de sistemas críticos de IA?",
    description: "Avalia a inclusão de IA nos planos de continuidade de negócio.",
    objective: "Verificar a resiliência de negócio diante de falhas de IA.",
    justification: "A dependência de IA em processos críticos exige planos de continuidade específicos.",
    marketReference: "ISO 22301; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 8,
    text: "A organização realiza exercícios e simulações (tabletop) de resposta a incidentes de IA?",
    description: "Avalia a prática de simulações de incidentes de IA.",
    objective: "Verificar a validação prática dos planos de resposta.",
    justification: "Simulações preparam as equipes e revelam lacunas nos planos antes de incidentes reais.",
    marketReference: "ISO/IEC 27035",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 9,
    text: "Existe processo para comunicação a reguladores e titulares em incidentes de IA que envolvam dados pessoais?",
    description: "Avalia a capacidade de notificação regulatória de incidentes.",
    objective: "Verificar a conformidade dos procedimentos de comunicação de incidentes.",
    justification: "A LGPD exige comunicação de incidentes à ANPD e aos titulares em prazos definidos.",
    marketReference: "LGPD Art. 48; ISO/IEC 27035",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 10,
    text: "A organização realiza análise pós-incidente (lições aprendidas) para incidentes de IA?",
    description: "Avalia a prática de revisão pós-incidente.",
    objective: "Verificar a melhoria contínua a partir dos incidentes.",
    justification: "Lições aprendidas previnem a recorrência e fortalecem os controles de IA.",
    marketReference: "ISO/IEC 27035; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 11,
    text: "Qual o percentual dos sistemas de IA críticos com objetivos de recuperação (RTO/RPO) definidos e testados?",
    description: "Mede a cobertura de metas de recuperação sobre sistemas críticos.",
    objective: "Quantificar a preparação de recuperação dos sistemas de IA.",
    justification: "RTO e RPO definidos e testados asseguram recuperação dentro de limites aceitáveis para o negócio.",
    marketReference: "ISO 22301",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 12,
    text: "A organização preserva evidências forenses de incidentes de IA para investigação e conformidade?",
    description: "Avalia a capacidade forense na resposta a incidentes de IA.",
    objective: "Verificar a preservação de evidências para análise e conformidade.",
    justification: "Evidências forenses são essenciais para investigação, responsabilização e defesa legal.",
    marketReference: "ISO/IEC 27035; ISO/IEC 27037",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 13,
    text: "Existe integração entre a resposta a incidentes de IA e a função corporativa de gestão de crises?",
    description: "Avalia a integração entre resposta a incidentes de IA e gestão de crises.",
    objective: "Verificar a coordenação em incidentes de IA de grande impacto.",
    justification: "Incidentes graves de IA podem escalar para crises corporativas exigindo coordenação ampla.",
    marketReference: "ISO 22301; ISO/IEC 27035",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 14,
    text: "A organização mantém canais para reporte de incidentes e comportamentos anômalos de IA por colaboradores e usuários?",
    description: "Avalia a existência de canais de reporte de incidentes de IA.",
    objective: "Verificar a capacidade de captação de incidentes reportados.",
    justification: "Canais de reporte ampliam a detecção precoce de problemas de IA em produção.",
    marketReference: "NIST AI RMF 1.0; ISO/IEC 42001",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "resposta-incidentes-ia",
    order: 15,
    text: "Os planos de resposta a incidentes de IA são revisados e atualizados periodicamente conforme mudanças nos sistemas?",
    description: "Avalia a manutenção contínua dos planos de resposta a incidentes de IA.",
    objective: "Verificar a atualidade dos planos frente à evolução dos sistemas de IA.",
    justification: "Planos desatualizados falham diante de novos sistemas, arquiteturas e ameaças de IA.",
    marketReference: "ISO/IEC 27035; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
];
