import type { CorpQuestionSeed } from "./types";

export const QUESTIONS_P4: CorpQuestionSeed[] = [
  // ── cultura-ia ──────────────────────────────────────────────────────────────
  {
    domainSlug: "cultura-ia",
    order: 1,
    text: "A alta liderança comunica de forma consistente uma visão que posiciona a IA como prioridade estratégica da organização?",
    description: "Avalia se existe patrocínio visível e mensagens recorrentes da liderança sobre o papel da IA no negócio.",
    objective: "Verificar o grau de patrocínio executivo e a clareza da narrativa cultural em torno da IA.",
    justification: "Sem uma visão comunicada pela liderança, iniciativas de IA permanecem isoladas e a adoção pelas áreas de negócio estagna.",
    marketReference: "Gartner AI Maturity Model; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 2,
    text: "Existe uma cultura orientada a dados em que decisões de negócio são fundamentadas em evidências e análises em vez de intuição?",
    description: "Mede o quanto a tomada de decisão baseada em dados está enraizada nas rotinas das áreas.",
    objective: "Avaliar a maturidade da cultura data-driven como base para a adoção de IA.",
    justification: "Uma cultura data-driven é pré-condição para que soluções de IA sejam confiadas e efetivamente utilizadas.",
    marketReference: "DAMA-DMBOK; Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 3,
    text: "A organização promove a experimentação com IA tolerando falhas controladas como parte do aprendizado?",
    description: "Avalia se há segurança psicológica e apetite para pilotos e provas de conceito com IA.",
    objective: "Verificar se a cultura incentiva a experimentação responsável com IA.",
    justification: "Ambientes que punem falhas inibem a inovação e reduzem a velocidade de aprendizado com IA.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 4,
    text: "Os colaboradores compreendem os conceitos básicos de IA e seus impactos no próprio trabalho?",
    description: "Mede o nível de alfabetização em IA (AI literacy) na força de trabalho.",
    objective: "Avaliar o grau de letramento em IA entre os colaboradores.",
    justification: "A alfabetização em IA é exigência crescente de regulações e habilita uso responsável e adoção em escala.",
    marketReference: "EU AI Act — AI literacy (Art. 4); ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 5,
    text: "Existem canais formais para que colaboradores proponham ideias e casos de uso de IA?",
    description: "Verifica a existência de mecanismos de captação de ideias vindas da base.",
    objective: "Avaliar a abertura organizacional para contribuições bottom-up em IA.",
    justification: "Canais de ideação ampliam o funil de casos de uso e aumentam o engajamento cultural com IA.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 6,
    text: "Como você caracteriza a atitude predominante das áreas de negócio em relação à adoção de IA?",
    description: "Classifica a postura cultural das áreas frente à IA.",
    objective: "Mapear a percepção dominante sobre IA na organização.",
    justification: "A postura cultural determina o ritmo de adoção e o nível de resistência às iniciativas de IA.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Resistência ativa", "Ceticismo cauteloso", "Curiosidade e interesse", "Entusiasmo e adoção proativa"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 7,
    text: "A organização reconhece e celebra publicamente sucessos alcançados com iniciativas de IA?",
    description: "Avalia se há reconhecimento formal e divulgação de casos de sucesso com IA.",
    objective: "Verificar mecanismos de reforço cultural positivo em torno da IA.",
    justification: "O reconhecimento de sucessos reforça comportamentos desejados e acelera a difusão cultural da IA.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 8,
    text: "Qual o percentual de áreas de negócio que já utilizam ativamente alguma solução de IA em suas rotinas?",
    description: "Quantifica a penetração da IA nas diferentes áreas da organização.",
    objective: "Medir a amplitude da adoção de IA entre as áreas.",
    justification: "A dispersão da adoção indica o quanto a IA está culturalmente incorporada além de bolsões isolados.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 9,
    text: "Existe uma narrativa clara sobre como a IA complementa o trabalho humano em vez de simplesmente substituí-lo?",
    description: "Avalia como a organização enquadra a relação entre IA e força de trabalho.",
    objective: "Verificar se a comunicação reduz o medo de substituição e favorece a colaboração humano-IA.",
    justification: "Uma narrativa de aumento (augmentation) reduz resistência e melhora a adoção sustentável de IA.",
    marketReference: "OECD AI Principles; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 10,
    text: "Os princípios de IA responsável fazem parte dos valores culturais praticados no dia a dia?",
    description: "Mede se ética e responsabilidade em IA são vividas culturalmente, não apenas documentadas.",
    objective: "Avaliar a internalização cultural dos princípios de IA responsável.",
    justification: "A cultura de IA responsável é a primeira linha de defesa contra usos inadequados e riscos reputacionais.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 11,
    text: "A organização mede periodicamente o nível de maturidade cultural e engajamento com IA?",
    description: "Verifica a existência de pesquisas ou indicadores de cultura de IA.",
    objective: "Avaliar se a cultura de IA é acompanhada por métricas ao longo do tempo.",
    justification: "Medir a cultura permite direcionar investimentos de mudança e demonstrar progresso à liderança.",
    marketReference: "Gartner AI Maturity Model; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 12,
    text: "Lideranças intermediárias atuam como multiplicadores e patrocinadores da IA em suas equipes?",
    description: "Avalia o engajamento da média gerência na disseminação da cultura de IA.",
    objective: "Verificar o papel das lideranças intermediárias como agentes de mudança.",
    justification: "A média gerência é decisiva para converter a visão executiva em adoção real nas equipes.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 13,
    text: "Há espaços colaborativos (comunidades de prática, fóruns) para troca de experiências sobre IA?",
    description: "Verifica a existência de comunidades internas voltadas ao tema de IA.",
    objective: "Avaliar mecanismos de disseminação horizontal de conhecimento em IA.",
    justification: "Comunidades de prática aceleram o aprendizado coletivo e reduzem a dependência de silos.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 14,
    text: "A organização enfrenta resistência significativa à adoção de IA por parte de colaboradores ou áreas?",
    description: "Identifica barreiras culturais e focos de resistência à IA.",
    objective: "Mapear a intensidade e a origem da resistência cultural à IA.",
    justification: "Identificar resistências é essencial para desenhar intervenções de gestão de mudança eficazes.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "cultura-ia",
    order: 15,
    text: "Descreva as principais barreiras culturais percebidas para a adoção de IA na organização.",
    description: "Campo aberto para caracterizar qualitativamente os obstáculos culturais.",
    objective: "Coletar percepções qualitativas sobre entraves culturais à IA.",
    justification: "O entendimento qualitativo das barreiras orienta o plano de mudança e comunicação.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── talentos-capacitacao ────────────────────────────────────────────────────
  {
    domainSlug: "talentos-capacitacao",
    order: 1,
    text: "A organização possui um plano estruturado de desenvolvimento de competências em IA para diferentes perfis?",
    description: "Avalia a existência de trilhas de capacitação segmentadas por papel (técnico, negócio, liderança).",
    objective: "Verificar a maturidade do planejamento de capacitação em IA.",
    justification: "A ausência de trilhas estruturadas cria lacunas de competência que limitam a escala das iniciativas de IA.",
    marketReference: "ISO/IEC 42001; EU AI Act — AI literacy (Art. 4)",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 2,
    text: "A organização consegue atrair profissionais qualificados em IA (cientistas de dados, engenheiros de ML)?",
    description: "Mede a capacidade competitiva de atração de talentos técnicos de IA no mercado.",
    objective: "Avaliar a atratividade da organização para talentos escassos de IA.",
    justification: "A escassez de talentos de IA é um dos principais gargalos para execução da estratégia.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 3,
    text: "Existem estratégias formais de retenção para profissionais-chave de IA?",
    description: "Verifica planos de carreira, remuneração e engajamento para reter talentos de IA.",
    objective: "Avaliar a robustez das estratégias de retenção de talentos críticos.",
    justification: "A rotatividade de talentos de IA gera perda de conhecimento e interrompe iniciativas estratégicas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 4,
    text: "Qual o percentual da força de trabalho que passou por capacitação formal em IA nos últimos 12 meses?",
    description: "Quantifica o alcance efetivo dos programas de capacitação em IA.",
    objective: "Medir a cobertura dos programas de capacitação.",
    justification: "A cobertura de treinamento indica o quão democratizado está o conhecimento de IA na organização.",
    marketReference: "EU AI Act — AI literacy (Art. 4)",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 5,
    text: "A organização mapeia formalmente as lacunas de competências (skills gap) em IA?",
    description: "Avalia se há inventário de competências e identificação de gaps frente às necessidades.",
    objective: "Verificar a existência de gestão de competências baseada em dados.",
    justification: "O mapeamento de gaps permite priorizar investimentos de capacitação e contratação de forma eficaz.",
    marketReference: "COBIT 2019 — APO07 (Managed Human Resources)",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 6,
    text: "Os líderes e executivos recebem capacitação específica sobre IA e seus impactos estratégicos?",
    description: "Verifica se há programas de letramento em IA voltados à alta liderança.",
    objective: "Avaliar o preparo da liderança para decisões sobre IA.",
    justification: "Líderes despreparados tomam decisões inadequadas de investimento e risco em IA.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 7,
    text: "Como a organização predominantemente supre suas necessidades de competências em IA?",
    description: "Classifica a estratégia dominante de aquisição de competências (build, buy, borrow).",
    objective: "Mapear o modelo de sourcing de talentos de IA.",
    justification: "O modelo de sourcing impacta custo, dependência de terceiros e sustentabilidade das capacidades internas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Desenvolvimento interno (reskilling/upskilling)", "Contratação no mercado", "Consultorias e terceiros", "Parcerias com academia", "Combinação equilibrada"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 8,
    text: "Existem trilhas de carreira definidas para profissionais de IA e dados na organização?",
    description: "Avalia a existência de progressão de carreira específica para papéis de IA.",
    objective: "Verificar a estruturação de carreiras técnicas de IA.",
    justification: "Trilhas de carreira claras aumentam a retenção e a atratividade de talentos técnicos.",
    marketReference: "COBIT 2019 — APO07",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 9,
    text: "A capacitação em IA inclui aspectos de ética, viés e uso responsável, além de temas técnicos?",
    description: "Verifica se os programas cobrem dimensões de responsabilidade, não apenas técnicas.",
    objective: "Avaliar a abrangência dos conteúdos de capacitação em IA responsável.",
    justification: "Competências em IA responsável são exigidas por regulações e reduzem riscos de uso inadequado.",
    marketReference: "EU AI Act; ISO/IEC 42001; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 10,
    text: "A organização oferece programas de reskilling para colaboradores cujas funções são impactadas por IA?",
    description: "Avalia iniciativas de requalificação frente à automação de tarefas.",
    objective: "Verificar o compromisso com a requalificação da força de trabalho.",
    justification: "Programas de reskilling mitigam impactos sociais e preservam conhecimento institucional.",
    marketReference: "OECD AI Principles; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 11,
    text: "Existe orçamento dedicado e recorrente para capacitação e desenvolvimento em IA?",
    description: "Verifica a existência de recursos financeiros formalmente alocados para capacitação.",
    objective: "Avaliar a sustentabilidade financeira dos programas de capacitação.",
    justification: "Sem orçamento dedicado, a capacitação torna-se pontual e insuficiente para a escala necessária.",
    marketReference: "COBIT 2019 — APO07",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 12,
    text: "A eficácia dos programas de capacitação em IA é avaliada por meio de indicadores de aprendizagem e aplicação?",
    description: "Mede se há avaliação de resultados dos treinamentos além da mera participação.",
    objective: "Verificar a gestão baseada em resultados da capacitação.",
    justification: "Avaliar eficácia garante que o investimento em capacitação gere competências aplicáveis.",
    marketReference: "COBIT 2019 — APO07",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 13,
    text: "A organização mantém parcerias com universidades ou instituições de ensino para formação em IA?",
    description: "Verifica alianças acadêmicas para desenvolvimento e captação de talentos.",
    objective: "Avaliar o ecossistema externo de formação de talentos.",
    justification: "Parcerias acadêmicas ampliam o pipeline de talentos e o acesso a conhecimento de fronteira.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 14,
    text: "As equipes de negócio possuem tradutores de IA (AI translators) que conectam necessidades de negócio a soluções técnicas?",
    description: "Avalia a existência de perfis de ponte entre negócio e times técnicos de IA.",
    objective: "Verificar a presença de competências de intermediação negócio-tecnologia.",
    justification: "Tradutores de IA aumentam a taxa de sucesso dos projetos ao alinhar valor de negócio e execução técnica.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "talentos-capacitacao",
    order: 15,
    text: "A organização depende criticamente de poucos indivíduos-chave para suas competências centrais de IA?",
    description: "Identifica riscos de concentração de conhecimento (key person risk) em IA.",
    objective: "Avaliar a vulnerabilidade decorrente da concentração de competências.",
    justification: "A dependência de poucos especialistas expõe a organização a rupturas em caso de saída desses profissionais.",
    marketReference: "COBIT 2019 — APO07; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── gestao-mudanca ──────────────────────────────────────────────────────────
  {
    domainSlug: "gestao-mudanca",
    order: 1,
    text: "A organização aplica uma metodologia estruturada de gestão de mudança nas iniciativas de IA?",
    description: "Avalia o uso de frameworks formais (ex.: ADKAR, Kotter) na adoção de IA.",
    objective: "Verificar a maturidade da abordagem de gestão de mudança em IA.",
    justification: "Iniciativas de IA sem gestão de mudança falham na adoção mesmo quando tecnicamente bem-sucedidas.",
    marketReference: "Prosci ADKAR; Kotter 8-Step; COBIT 2019 — BAI05",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 2,
    text: "Os processos de negócio são redesenhados de forma deliberada ao incorporar soluções de IA?",
    description: "Verifica se a adoção de IA é acompanhada de redesenho de processos e não apenas sobreposta ao existente.",
    objective: "Avaliar a integração da IA ao redesenho de processos.",
    justification: "Aplicar IA sobre processos disfuncionais amplia ineficiências em vez de gerar valor.",
    marketReference: "COBIT 2019 — BAI05; ITIL 4",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 3,
    text: "Existe um plano de comunicação estruturado para as iniciativas de IA junto aos stakeholders impactados?",
    description: "Avalia a existência de estratégia de comunicação ao longo do ciclo de mudança.",
    objective: "Verificar a robustez da comunicação de mudança em IA.",
    justification: "A comunicação inadequada gera incertezas, boatos e resistência às mudanças introduzidas pela IA.",
    marketReference: "Prosci ADKAR; COBIT 2019 — BAI05",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 4,
    text: "A organização identifica e prepara agentes de mudança (change champions) para as iniciativas de IA?",
    description: "Verifica a mobilização de multiplicadores que apoiam a adoção nas áreas.",
    objective: "Avaliar a rede de agentes de mudança em IA.",
    justification: "Agentes de mudança aceleram a adoção e reduzem a resistência em nível local.",
    marketReference: "Prosci ADKAR",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 5,
    text: "Os impactos das iniciativas de IA sobre papéis, responsabilidades e cargas de trabalho são avaliados antecipadamente?",
    description: "Avalia a realização de análise de impacto organizacional das mudanças de IA.",
    objective: "Verificar a antecipação de impactos sobre a força de trabalho.",
    justification: "A análise de impacto permite planejar transições e mitigar disrupções operacionais.",
    marketReference: "COBIT 2019 — BAI05; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 6,
    text: "A adoção efetiva das soluções de IA pelos usuários finais é medida após a implantação?",
    description: "Verifica o acompanhamento de indicadores de adoção pós-go-live.",
    objective: "Avaliar a mensuração da adoção real das soluções de IA.",
    justification: "Medir adoção evita que soluções de IA fiquem subutilizadas e não gerem o valor esperado.",
    marketReference: "Prosci ADKAR; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 7,
    text: "Qual o principal fator de resistência observado nas iniciativas de mudança relacionadas a IA?",
    description: "Classifica a origem predominante da resistência à mudança.",
    objective: "Identificar o vetor dominante de resistência à mudança em IA.",
    justification: "Conhecer o fator predominante de resistência direciona as intervenções de mudança mais adequadas.",
    marketReference: "Prosci ADKAR",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Medo de substituição/perda de emprego", "Falta de competências", "Ceticismo quanto aos resultados", "Falta de patrocínio da liderança", "Sobrecarga de mudanças simultâneas"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 8,
    text: "Qual o percentual de iniciativas de IA que incluem formalmente um plano de gestão de mudança?",
    description: "Quantifica a cobertura da gestão de mudança no portfólio de IA.",
    objective: "Medir a institucionalização da gestão de mudança nas iniciativas de IA.",
    justification: "A cobertura indica o quão sistemática é a prática de gestão de mudança em IA.",
    marketReference: "Prosci ADKAR; COBIT 2019 — BAI05",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 9,
    text: "Existe suporte estruturado (treinamento, help desk, materiais) para usuários durante a transição para soluções de IA?",
    description: "Avalia os mecanismos de apoio à adoção durante a curva de aprendizagem.",
    objective: "Verificar a disponibilidade de suporte à transição.",
    justification: "O suporte adequado reduz a frustração inicial e sustenta a adoção das novas soluções.",
    marketReference: "ITIL 4; Prosci ADKAR",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 10,
    text: "A liderança demonstra patrocínio ativo e visível ao longo das iniciativas de mudança em IA?",
    description: "Mede o engajamento contínuo dos patrocinadores, não apenas no início.",
    objective: "Avaliar a sustentação do patrocínio executivo durante a mudança.",
    justification: "O patrocínio ativo é o fator mais correlacionado ao sucesso de iniciativas de mudança.",
    marketReference: "Prosci ADKAR",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 11,
    text: "As lições aprendidas em iniciativas de mudança de IA são capturadas e reutilizadas em novos projetos?",
    description: "Verifica a existência de aprendizado organizacional sobre gestão de mudança.",
    objective: "Avaliar o ciclo de melhoria contínua da gestão de mudança.",
    justification: "A reutilização de lições aprendidas eleva a taxa de sucesso das mudanças futuras.",
    marketReference: "ITIL 4; COBIT 2019 — BAI05",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 12,
    text: "A organização gerencia o volume e o ritmo de mudanças simultâneas para evitar fadiga de mudança?",
    description: "Avalia a gestão da capacidade de absorção de mudanças pela organização.",
    objective: "Verificar o controle da saturação de mudanças (change fatigue).",
    justification: "O excesso de mudanças simultâneas reduz a capacidade de adoção e aumenta a resistência.",
    marketReference: "Prosci ADKAR",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 13,
    text: "Existe alinhamento entre RH e as áreas de tecnologia na condução das mudanças introduzidas por IA?",
    description: "Verifica a colaboração entre RH e TI/IA na gestão de mudança.",
    objective: "Avaliar a integração entre pessoas e tecnologia na mudança.",
    justification: "O alinhamento entre RH e tecnologia garante coerência entre soluções técnicas e impactos nas pessoas.",
    marketReference: "COBIT 2019 — APO07; BAI05",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 14,
    text: "Os benefícios pretendidos das mudanças em IA são acompanhados após a estabilização (realização de benefícios)?",
    description: "Avalia o acompanhamento da realização de benefícios pós-mudança.",
    objective: "Verificar a gestão de benefícios ao longo do ciclo de mudança.",
    justification: "A realização de benefícios confirma se a mudança gerou o valor que justificou o investimento.",
    marketReference: "COBIT 2019 — BAI05; Managing Successful Programmes (MSP)",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-mudanca",
    order: 15,
    text: "Descreva como a organização trata os colaboradores cujas funções são substancialmente transformadas por IA.",
    description: "Campo aberto sobre a abordagem humana e ética da transição de funções.",
    objective: "Coletar a estratégia qualitativa de tratamento das transições de pessoas.",
    justification: "O tratamento ético das transições impacta reputação, engajamento e conformidade regulatória.",
    marketReference: "OECD AI Principles; ISO/IEC 42001",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── colaboracao-inovacao ────────────────────────────────────────────────────
  {
    domainSlug: "colaboracao-inovacao",
    order: 1,
    text: "A organização possui uma estrutura formal dedicada à inovação em IA (lab, hub ou centro de excelência)?",
    description: "Avalia a existência de estruturas organizacionais voltadas à experimentação e inovação com IA.",
    objective: "Verificar a institucionalização da inovação em IA.",
    justification: "Estruturas dedicadas concentram competências, aceleram experimentos e evitam esforços dispersos.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 2,
    text: "Existe um processo estruturado para transformar experimentos e provas de conceito de IA em produtos em produção?",
    description: "Avalia a capacidade de escalar da experimentação para a produção (scale-up).",
    objective: "Verificar a maturidade do funil de inovação até a produção.",
    justification: "Muitas provas de conceito de IA nunca chegam à produção, desperdiçando investimento e conhecimento.",
    marketReference: "Gartner AI Maturity Model; MLOps (Google MLOps maturity)",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 3,
    text: "As equipes de IA colaboram de forma multidisciplinar com negócio, dados, jurídico e segurança?",
    description: "Avalia o grau de colaboração entre disciplinas na condução de iniciativas de IA.",
    objective: "Verificar a maturidade da colaboração multidisciplinar.",
    justification: "A colaboração multidisciplinar reduz retrabalho e garante que riscos e valor sejam endereçados desde o início.",
    marketReference: "NIST AI RMF 1.0 — GOVERN; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 4,
    text: "A organização mantém parcerias externas de inovação em IA (startups, fornecedores, academia)?",
    description: "Verifica o engajamento com o ecossistema externo de inovação em IA.",
    objective: "Avaliar a abertura ao ecossistema de inovação (open innovation).",
    justification: "Parcerias externas ampliam o acesso a tecnologias emergentes e aceleram a inovação.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 5,
    text: "Existe orçamento protegido para experimentação e inovação em IA, independente das demandas operacionais?",
    description: "Avalia a alocação de recursos específicos para inovação em IA.",
    objective: "Verificar a sustentabilidade financeira da inovação em IA.",
    justification: "Sem orçamento protegido, a inovação é canibalizada por demandas operacionais de curto prazo.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 6,
    text: "Qual o percentual de provas de conceito de IA que evoluem para implantação em produção?",
    description: "Quantifica a taxa de conversão de experimentos em soluções produtivas.",
    objective: "Medir a eficácia do funil de inovação em IA.",
    justification: "Uma taxa de conversão baixa indica gargalos de escalabilidade e desperdício de recursos.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 7,
    text: "Como a organização predominantemente conduz a inovação em IA?",
    description: "Classifica o modelo dominante de inovação (centralizado, distribuído, híbrido).",
    objective: "Mapear o modelo operacional de inovação em IA.",
    justification: "O modelo de inovação impacta velocidade, governança e alinhamento estratégico das iniciativas.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Centralizada em um hub/CoE", "Distribuída nas áreas de negócio", "Modelo híbrido (hub-and-spoke)", "Ad hoc, sem modelo definido"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 8,
    text: "Existem ambientes seguros (sandboxes) para experimentação controlada com IA?",
    description: "Verifica a disponibilidade de ambientes isolados para testar soluções de IA.",
    objective: "Avaliar a infraestrutura de experimentação segura.",
    justification: "Sandboxes permitem inovar rapidamente sem expor dados e sistemas de produção a riscos.",
    marketReference: "ISO/IEC 42001; EU AI Act — regulatory sandboxes",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 9,
    text: "A organização monitora tendências e tecnologias emergentes de IA de forma estruturada (technology radar)?",
    description: "Avalia a vigilância tecnológica sistemática sobre o campo de IA.",
    objective: "Verificar a capacidade de antecipação tecnológica.",
    justification: "O monitoramento de tendências evita obsolescência e identifica oportunidades competitivas.",
    marketReference: "Gartner AI Maturity Model; TOGAF",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 10,
    text: "As iniciativas de inovação em IA são governadas com critérios claros de continuidade ou descontinuação (stage-gate)?",
    description: "Avalia a existência de portões de decisão para gerir o portfólio de inovação.",
    objective: "Verificar a governança do portfólio de experimentos de IA.",
    justification: "Critérios claros de stage-gate evitam a perpetuação de experimentos sem valor comprovado.",
    marketReference: "Gartner AI Maturity Model; COBIT 2019 — APO05",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 11,
    text: "O conhecimento e os ativos gerados em experimentos de IA são compartilhados entre as equipes?",
    description: "Verifica mecanismos de reuso de aprendizados, componentes e ativos de IA.",
    objective: "Avaliar a gestão do conhecimento gerado pela inovação.",
    justification: "O compartilhamento de ativos acelera novos projetos e evita reinvenção de soluções.",
    marketReference: "DAMA-DMBOK; Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 12,
    text: "A colaboração entre áreas de negócio e times técnicos ocorre desde a concepção das iniciativas de IA?",
    description: "Avalia o envolvimento precoce do negócio na definição dos problemas a resolver com IA.",
    objective: "Verificar o alinhamento negócio-técnico na origem das iniciativas.",
    justification: "O envolvimento precoce do negócio aumenta a relevância e a adoção das soluções de IA.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 13,
    text: "A organização participa de consórcios, comunidades ou iniciativas setoriais de IA (ex.: FEBRABAN)?",
    description: "Verifica o engajamento em fóruns colaborativos do setor sobre IA.",
    objective: "Avaliar a colaboração no nível do ecossistema setorial.",
    justification: "A colaboração setorial acelera boas práticas e a construção de padrões comuns de IA responsável.",
    marketReference: "FEBRABAN; Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 14,
    text: "O tempo médio entre a ideação e a entrega de valor de uma iniciativa de IA é acompanhado e otimizado?",
    description: "Avalia a medição e melhoria do time-to-value das iniciativas de IA.",
    objective: "Verificar a eficiência do ciclo de inovação até o valor.",
    justification: "Ciclos longos reduzem a competitividade e desmotivam patrocinadores das iniciativas de IA.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "colaboracao-inovacao",
    order: 15,
    text: "As iniciativas de inovação em IA passam por avaliação de riscos éticos e regulatórios desde a fase experimental?",
    description: "Verifica a integração de governança de risco à inovação (innovation by design).",
    objective: "Avaliar a incorporação de responsabilidade na inovação em IA.",
    justification: "Considerar riscos desde o experimento evita retrabalho e bloqueios em fases avançadas.",
    marketReference: "NIST AI RMF 1.0; ISO/IEC 23894; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── roi-valor ───────────────────────────────────────────────────────────────
  {
    domainSlug: "roi-valor",
    order: 1,
    text: "A organização define business cases com benefícios quantificados antes de aprovar iniciativas de IA?",
    description: "Avalia se há justificativa de valor mensurável na origem dos projetos de IA.",
    objective: "Verificar a disciplina de business case na priorização de IA.",
    justification: "Iniciativas sem business case tendem a consumir recursos sem entregar valor mensurável ao negócio.",
    marketReference: "COBIT 2019 — APO05 (Managed Portfolio); Val IT",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 2,
    text: "Existe um processo formal para medir o ROI das iniciativas de IA após a implantação?",
    description: "Verifica a mensuração de retorno real (realizado) e não apenas projetado.",
    objective: "Avaliar a maturidade da medição de retorno das iniciativas de IA.",
    justification: "A ausência de medição de ROI impede a otimização de investimentos e a prestação de contas.",
    marketReference: "COBIT 2019 — APO05; Val IT",
    criticality: "alta",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "roi-valor",
    order: 3,
    text: "Os benefícios das iniciativas de IA são categorizados entre financeiros e não financeiros (ex.: risco, experiência)?",
    description: "Avalia a abrangência da taxonomia de benefícios considerada.",
    objective: "Verificar a amplitude da avaliação de valor de IA.",
    justification: "Considerar apenas benefícios financeiros subestima o valor real de muitas iniciativas de IA.",
    marketReference: "Val IT; COBIT 2019 — APO05",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 4,
    text: "Existem KPIs claros e acordados com o negócio para cada iniciativa de IA?",
    description: "Verifica a definição de indicadores de sucesso alinhados aos objetivos de negócio.",
    objective: "Avaliar a clareza dos indicadores de valor por iniciativa.",
    justification: "KPIs acordados garantem alinhamento de expectativas e permitem avaliar sucesso objetivamente.",
    marketReference: "COBIT 2019 — APO05; Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 5,
    text: "Qual o percentual das iniciativas de IA em produção que possui benefícios monitorados de forma contínua?",
    description: "Quantifica a cobertura do acompanhamento de benefícios no portfólio.",
    objective: "Medir a abrangência do monitoramento de valor.",
    justification: "A cobertura indica o quão sistemática é a gestão de valor das iniciativas de IA.",
    marketReference: "COBIT 2019 — APO05; Val IT",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 6,
    text: "A organização utiliza uma linha de base (baseline) confiável para comparar resultados antes e depois da IA?",
    description: "Avalia a existência de medições de referência para atribuição de valor.",
    objective: "Verificar a robustez da atribuição de valor às iniciativas de IA.",
    justification: "Sem baseline confiável, não é possível atribuir ganhos à IA de forma defensável.",
    marketReference: "Val IT; COBIT 2019 — APO05",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 7,
    text: "Como a organização predominantemente demonstra o valor de suas iniciativas de IA à alta gestão?",
    description: "Classifica a abordagem dominante de comunicação de valor.",
    objective: "Mapear a forma como o valor de IA é comunicado à liderança.",
    justification: "A forma de demonstrar valor influencia a continuidade do patrocínio e do investimento em IA.",
    marketReference: "COBIT 2019 — APO05; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Métricas financeiras (ROI, VPL, payback)", "Indicadores operacionais e de eficiência", "Indicadores de risco e conformidade", "Narrativas e casos qualitativos", "Não há demonstração estruturada"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 8,
    text: "Os resultados de valor das iniciativas de IA são revisados periodicamente por um fórum de governança?",
    description: "Verifica a revisão recorrente de valor por instância de governança.",
    objective: "Avaliar a governança da gestão de valor de IA.",
    justification: "A revisão periódica permite realocar recursos de iniciativas de baixo retorno para as de alto valor.",
    marketReference: "COBIT 2019 — APO05; EDM02 (Ensured Benefits Delivery)",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 9,
    text: "A organização considera o custo total de propriedade (TCO) das soluções de IA na avaliação de valor?",
    description: "Avalia a inclusão de custos de operação, manutenção e infraestrutura no cálculo de valor.",
    objective: "Verificar a abrangência da análise de custos no valor de IA.",
    justification: "Ignorar o TCO leva a superestimar o ROI e a decisões de investimento equivocadas.",
    marketReference: "FinOps Foundation; COBIT 2019 — APO05",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 10,
    text: "Iniciativas de IA que não entregam o valor esperado são descontinuadas de forma estruturada?",
    description: "Avalia a disciplina de encerrar iniciativas de baixo retorno.",
    objective: "Verificar a gestão ativa do portfólio com base em valor.",
    justification: "A relutância em descontinuar iniciativas fracassadas imobiliza recursos e prejudica o portfólio.",
    marketReference: "COBIT 2019 — APO05",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 11,
    text: "Existe responsabilização clara (ownership) pela realização dos benefícios de cada iniciativa de IA?",
    description: "Verifica a atribuição de responsáveis pela entrega de valor.",
    objective: "Avaliar a accountability sobre benefícios de IA.",
    justification: "Sem responsáveis claros, os benefícios projetados raramente se concretizam.",
    marketReference: "COBIT 2019 — EDM02; Val IT",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 12,
    text: "A organização compara o valor gerado por IA com benchmarks de mercado ou do setor?",
    description: "Avalia o uso de referências externas para contextualizar o desempenho.",
    objective: "Verificar a contextualização competitiva do valor de IA.",
    justification: "O benchmarking evita complacência e revela oportunidades de melhoria de retorno.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 13,
    text: "Os benefícios intangíveis de IA (ex.: reputação, satisfação do cliente) são estimados com métodos consistentes?",
    description: "Avalia a metodologia para valorar benefícios difíceis de quantificar.",
    objective: "Verificar a consistência na valoração de benefícios intangíveis.",
    justification: "Métodos consistentes evitam sub ou superestimação de benefícios intangíveis relevantes.",
    marketReference: "Val IT",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 14,
    text: "A gestão de valor de IA está integrada ao ciclo de planejamento orçamentário da organização?",
    description: "Verifica a integração entre valor de IA e o processo orçamentário.",
    objective: "Avaliar a integração da gestão de valor ao planejamento financeiro.",
    justification: "A integração ao orçamento garante que decisões de investimento sejam guiadas por valor comprovado.",
    marketReference: "COBIT 2019 — APO05; APO06 (Managed Budget and Costs)",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "roi-valor",
    order: 15,
    text: "Descreva as principais dificuldades enfrentadas pela organização para medir o valor gerado pela IA.",
    description: "Campo aberto para caracterizar barreiras à mensuração de valor.",
    objective: "Coletar percepções qualitativas sobre obstáculos à medição de valor.",
    justification: "Entender as dificuldades orienta melhorias no processo de gestão de valor de IA.",
    marketReference: "COBIT 2019 — APO05",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── finops-ia ───────────────────────────────────────────────────────────────
  {
    domainSlug: "finops-ia",
    order: 1,
    text: "A organização possui visibilidade detalhada e atualizada dos custos de IA (computação, tokens, licenças, armazenamento)?",
    description: "Avalia a granularidade e a atualidade da visibilidade de custos de IA.",
    objective: "Verificar a maturidade da visibilidade de custos de IA.",
    justification: "Sem visibilidade de custos, é impossível otimizar gastos e controlar o crescimento descontrolado de IA.",
    marketReference: "FinOps Foundation — Inform Phase",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 2,
    text: "Os custos de IA são alocados (chargeback/showback) às áreas ou produtos que os consomem?",
    description: "Verifica a existência de mecanismos de alocação de custos aos consumidores.",
    objective: "Avaliar a maturidade de chargeback/showback de custos de IA.",
    justification: "A alocação de custos cria responsabilização e incentiva o consumo eficiente de recursos de IA.",
    marketReference: "FinOps Foundation; COBIT 2019 — APO06",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 3,
    text: "Existem mecanismos de alerta e controle para gastos anômalos com serviços de IA (ex.: uso excessivo de tokens)?",
    description: "Avalia controles automáticos de detecção e contenção de gastos anômalos.",
    objective: "Verificar a existência de guardrails financeiros para IA.",
    justification: "Gastos anômalos com LLMs e computação podem escalar rapidamente sem controles automáticos.",
    marketReference: "FinOps Foundation — Operate Phase",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 4,
    text: "A organização otimiza ativamente os custos de IA (ex.: escolha de modelos, caching, batches, dimensionamento)?",
    description: "Avalia práticas de otimização de custos ao longo da operação de IA.",
    objective: "Verificar a maturidade das práticas de otimização (Optimize Phase).",
    justification: "A otimização contínua evita desperdício e melhora a relação custo-benefício das soluções de IA.",
    marketReference: "FinOps Foundation — Optimize Phase",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 5,
    text: "Existem previsões (forecast) e orçamentos específicos para os custos de IA?",
    description: "Verifica a existência de planejamento financeiro dedicado à IA.",
    objective: "Avaliar a maturidade do forecasting e orçamentação de IA.",
    justification: "Previsões e orçamentos dedicados evitam surpresas financeiras e apoiam decisões de escala.",
    marketReference: "FinOps Foundation; COBIT 2019 — APO06",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 6,
    text: "Qual o percentual dos custos de IA que pode ser atribuído a casos de uso ou produtos específicos?",
    description: "Quantifica a rastreabilidade dos custos de IA aos seus geradores.",
    objective: "Medir a granularidade da atribuição de custos.",
    justification: "Custos não atribuíveis dificultam decisões de valor e controle financeiro sobre a IA.",
    marketReference: "FinOps Foundation — Inform Phase",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 7,
    text: "Qual o modelo predominante de contratação de recursos de computação para IA na organização?",
    description: "Classifica o modelo de consumo de infraestrutura de IA.",
    objective: "Mapear o modelo de sourcing de computação de IA.",
    justification: "O modelo de contratação impacta custo, flexibilidade e previsibilidade financeira das cargas de IA.",
    marketReference: "FinOps Foundation",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Sob demanda (pay-as-you-go)", "Instâncias reservadas/compromissos de uso", "Infraestrutura própria (on-premise)", "Modelo híbrido", "Não há estratégia definida"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 8,
    text: "Existe uma função ou papel dedicado a FinOps para IA na organização?",
    description: "Verifica a existência de responsáveis formais pela gestão financeira de IA.",
    objective: "Avaliar a institucionalização da prática de FinOps para IA.",
    justification: "A responsabilização formal por FinOps garante disciplina contínua na gestão de custos.",
    marketReference: "FinOps Foundation",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 9,
    text: "Os custos de IA são acompanhados em relação ao valor gerado (unit economics, ex.: custo por inferência ou por transação)?",
    description: "Avalia a correlação entre custo e valor por unidade de negócio.",
    objective: "Verificar a maturidade de unit economics em IA.",
    justification: "Compreender o custo por unidade de valor é essencial para escalar soluções de IA de forma sustentável.",
    marketReference: "FinOps Foundation — Unit Economics",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 10,
    text: "As equipes técnicas têm consciência de custos (cost awareness) ao projetar e operar soluções de IA?",
    description: "Avalia a cultura de responsabilidade financeira entre engenheiros e cientistas de dados.",
    objective: "Verificar a disseminação da cultura de FinOps nas equipes técnicas.",
    justification: "A consciência de custos nas equipes técnicas é a base para a otimização sustentável de gastos de IA.",
    marketReference: "FinOps Foundation — Culture",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 11,
    text: "A organização compara periodicamente o custo-benefício entre modelos próprios e serviços de IA de terceiros?",
    description: "Avalia decisões de build vs. buy baseadas em custo e valor.",
    objective: "Verificar a racionalidade econômica das decisões de sourcing de modelos.",
    justification: "A escolha inadequada entre modelos próprios e de terceiros pode elevar substancialmente os custos.",
    marketReference: "FinOps Foundation; COBIT 2019 — APO06",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 12,
    text: "Existem políticas para desligar ou reduzir recursos de IA ociosos (ex.: ambientes de desenvolvimento não utilizados)?",
    description: "Verifica práticas de gestão de recursos ociosos e desperdício.",
    objective: "Avaliar o controle sobre desperdício de recursos de IA.",
    justification: "Recursos ociosos representam custo direto sem geração de valor associado.",
    marketReference: "FinOps Foundation — Optimize Phase",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 13,
    text: "Os relatórios de custos de IA são acessíveis e compreensíveis para stakeholders financeiros e de negócio?",
    description: "Avalia a transparência e a usabilidade das informações de custo.",
    objective: "Verificar a democratização das informações de custo de IA.",
    justification: "Relatórios acessíveis habilitam decisões descentralizadas e responsáveis sobre gastos de IA.",
    marketReference: "FinOps Foundation — Inform Phase",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 14,
    text: "A organização estabelece metas de eficiência de custos de IA e acompanha seu progresso?",
    description: "Verifica a definição e o acompanhamento de metas de eficiência financeira.",
    objective: "Avaliar a gestão por metas de eficiência de custos.",
    justification: "Metas de eficiência direcionam esforços de otimização e demonstram maturidade financeira em IA.",
    marketReference: "FinOps Foundation",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "finops-ia",
    order: 15,
    text: "Os custos de sustentabilidade e consumo energético das cargas de IA são considerados na gestão financeira?",
    description: "Avalia a inclusão de custos e impactos ambientais (GreenOps) na gestão.",
    objective: "Verificar a consideração de sustentabilidade nos custos de IA.",
    justification: "O consumo energético de IA impacta custos e obrigações crescentes de reporte ESG.",
    marketReference: "FinOps Foundation — Sustainability; ISO/IEC 42001",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── portfolio-casos-uso ─────────────────────────────────────────────────────
  {
    domainSlug: "portfolio-casos-uso",
    order: 1,
    text: "A organização mantém um inventário centralizado e atualizado dos casos de uso de IA (em ideação, desenvolvimento e produção)?",
    description: "Avalia a existência de um repositório único e vivo do portfólio de IA.",
    objective: "Verificar a existência de um inventário abrangente de casos de uso.",
    justification: "Sem inventário centralizado, há duplicação de esforços, perda de visibilidade e riscos de shadow AI.",
    marketReference: "COBIT 2019 — APO05; ISO/IEC 42001 (AI system inventory)",
    criticality: "alta",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 2,
    text: "Existe um processo estruturado de priorização de casos de uso de IA com critérios definidos (valor, risco, viabilidade)?",
    description: "Avalia a metodologia de priorização de iniciativas do portfólio.",
    objective: "Verificar a maturidade do processo de priorização.",
    justification: "A priorização baseada em critérios evita alocação de recursos em iniciativas de baixo valor ou alto risco.",
    marketReference: "COBIT 2019 — APO05; Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 3,
    text: "Os casos de uso de IA são classificados por nível de risco (ex.: alinhado às categorias do EU AI Act)?",
    description: "Avalia a categorização de risco dos casos de uso do portfólio.",
    objective: "Verificar a classificação de risco integrada à gestão de portfólio.",
    justification: "A classificação de risco orienta controles proporcionais e o cumprimento regulatório.",
    marketReference: "EU AI Act — risk categories; NIST AI RMF 1.0 — MAP",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 4,
    text: "Existe alinhamento explícito entre os casos de uso priorizados e os objetivos estratégicos da organização?",
    description: "Verifica se o portfólio está ancorado na estratégia corporativa.",
    objective: "Avaliar o alinhamento estratégico do portfólio de IA.",
    justification: "Um portfólio desalinhado da estratégia dispersa recursos e reduz o impacto competitivo da IA.",
    marketReference: "COBIT 2019 — APO05; TOGAF",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 5,
    text: "A organização balanceia o portfólio entre ganhos rápidos e apostas estratégicas de maior prazo?",
    description: "Avalia o equilíbrio entre iniciativas de curto e longo prazo no portfólio.",
    objective: "Verificar o balanceamento de horizontes no portfólio de IA.",
    justification: "Um portfólio desbalanceado compromete a geração de valor sustentável ou a credibilidade de curto prazo.",
    marketReference: "COBIT 2019 — APO05; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 6,
    text: "Qual o percentual dos casos de uso do portfólio que já estão em produção gerando valor?",
    description: "Quantifica a taxa de conversão do portfólio em soluções produtivas.",
    objective: "Medir a efetividade de entrega do portfólio de IA.",
    justification: "Uma baixa proporção em produção indica gargalos de execução e portfólio inflado de ideias.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 7,
    text: "Existe um comitê ou fórum responsável por decidir sobre a entrada, continuidade e saída de casos de uso do portfólio?",
    description: "Verifica a governança formal do portfólio de IA.",
    objective: "Avaliar a governança de decisões sobre o portfólio.",
    justification: "A governança formal garante decisões consistentes e transparentes sobre recursos e prioridades.",
    marketReference: "COBIT 2019 — APO05; EDM02",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 8,
    text: "Qual método a organização utiliza predominantemente para avaliar a viabilidade de novos casos de uso de IA?",
    description: "Classifica a abordagem dominante de avaliação de viabilidade.",
    objective: "Mapear o método de avaliação de viabilidade de casos de uso.",
    justification: "O método de avaliação impacta a qualidade das decisões de investimento em novos casos de uso.",
    marketReference: "COBIT 2019 — APO05; Gartner AI Maturity Model",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Matriz valor x esforço", "Análise de business case financeiro", "Scoring multicritério (valor, risco, viabilidade)", "Avaliação ad hoc/qualitativa", "Não há método definido"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 9,
    text: "A organização identifica e controla iniciativas de IA não oficiais (shadow AI) fora do portfólio gerenciado?",
    description: "Avalia a capacidade de detectar e integrar o uso não governado de IA.",
    objective: "Verificar o controle sobre shadow AI.",
    justification: "O shadow AI cria riscos de segurança, conformidade e desperdício fora da visão da governança.",
    marketReference: "ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 10,
    text: "As dependências e sinergias entre casos de uso de IA são consideradas na gestão do portfólio?",
    description: "Avalia a análise de interdependências entre iniciativas.",
    objective: "Verificar a gestão de dependências no portfólio de IA.",
    justification: "Ignorar dependências gera conflitos de recursos e perda de sinergias entre iniciativas.",
    marketReference: "COBIT 2019 — APO05; TOGAF",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 11,
    text: "O portfólio de casos de uso é revisado periodicamente e repriorizado conforme mudanças de contexto?",
    description: "Avalia a dinâmica de revisão contínua do portfólio.",
    objective: "Verificar a agilidade da repriorização do portfólio.",
    justification: "A repriorização periódica mantém o portfólio alinhado a prioridades e restrições em evolução.",
    marketReference: "COBIT 2019 — APO05",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 12,
    text: "Existe uma taxonomia padronizada para descrever e categorizar os casos de uso de IA?",
    description: "Verifica a padronização na descrição dos casos de uso.",
    objective: "Avaliar a consistência na catalogação dos casos de uso.",
    justification: "Uma taxonomia comum facilita comparação, reuso e comunicação do portfólio de IA.",
    marketReference: "DAMA-DMBOK; ISO/IEC 42001",
    criticality: "baixa",
    weight: 2,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 13,
    text: "A capacidade de entrega (recursos, talentos, infraestrutura) é considerada ao dimensionar o portfólio de IA?",
    description: "Avalia o equilíbrio entre ambição do portfólio e capacidade real de execução.",
    objective: "Verificar o realismo do portfólio frente à capacidade de entrega.",
    justification: "Portfólios acima da capacidade de entrega geram atrasos, frustração e desperdício de recursos.",
    marketReference: "COBIT 2019 — APO05; APO07",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 14,
    text: "Os casos de uso replicáveis são identificados para reaproveitamento em outras áreas ou unidades?",
    description: "Avalia a busca por escalabilidade e reuso de soluções bem-sucedidas.",
    objective: "Verificar a exploração de oportunidades de escala e reuso.",
    justification: "A replicação de casos de sucesso multiplica o valor com menor custo marginal.",
    marketReference: "Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "portfolio-casos-uso",
    order: 15,
    text: "Descreva os casos de uso de IA considerados mais estratégicos e o racional de sua priorização.",
    description: "Campo aberto para caracterizar os casos de uso prioritários e sua justificativa.",
    objective: "Coletar a visão qualitativa sobre as prioridades do portfólio.",
    justification: "Compreender o racional de priorização evidencia o alinhamento estratégico do portfólio.",
    marketReference: "COBIT 2019 — APO05",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── gestao-fornecedores ─────────────────────────────────────────────────────
  {
    domainSlug: "gestao-fornecedores",
    order: 1,
    text: "A organização realiza due diligence formal sobre fornecedores de IA antes da contratação?",
    description: "Avalia a existência de avaliação prévia de capacidade, segurança e conformidade dos fornecedores.",
    objective: "Verificar a maturidade da due diligence de fornecedores de IA.",
    justification: "A ausência de due diligence expõe a organização a riscos de segurança, conformidade e continuidade.",
    marketReference: "ISO/IEC 27001 — A.15; NIST AI RMF 1.0 — GOVERN; BACEN Res. 4.893",
    criticality: "alta",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 2,
    text: "Os contratos com fornecedores de IA incluem cláusulas específicas sobre uso de dados, propriedade intelectual e conformidade?",
    description: "Avalia a robustez contratual frente a riscos específicos de IA.",
    objective: "Verificar a adequação das cláusulas contratuais de IA.",
    justification: "Cláusulas específicas protegem a organização quanto a uso indevido de dados e responsabilidades regulatórias.",
    marketReference: "LGPD Art. 39; ISO/IEC 27001 — A.15; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 3,
    text: "A organização avalia o risco de concentração e dependência (lock-in) em fornecedores de IA?",
    description: "Avalia a gestão do risco de dependência excessiva de poucos fornecedores.",
    objective: "Verificar a gestão do risco de concentração de fornecedores.",
    justification: "A dependência excessiva de um fornecedor eleva riscos de custo, continuidade e poder de barganha.",
    marketReference: "BACEN Res. 4.893; ISO/IEC 27001 — A.15",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 4,
    text: "Existe monitoramento contínuo do desempenho e conformidade dos fornecedores de IA (SLAs, auditorias)?",
    description: "Avalia o acompanhamento pós-contratação dos fornecedores de IA.",
    objective: "Verificar a maturidade do monitoramento de fornecedores.",
    justification: "O monitoramento contínuo detecta desvios de desempenho e conformidade antes que gerem impacto.",
    marketReference: "ISO/IEC 27001 — A.15; ITIL 4 — Supplier Management",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 5,
    text: "A organização exige que fornecedores de IA demonstrem conformidade com regulações aplicáveis (LGPD, requisitos setoriais)?",
    description: "Verifica a exigência de conformidade regulatória aos fornecedores.",
    objective: "Avaliar a transferência de requisitos de conformidade à cadeia de fornecedores.",
    justification: "A responsabilidade regulatória permanece com a organização mesmo quando o processamento é terceirizado.",
    marketReference: "LGPD Art. 39; BACEN Res. 4.893; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 6,
    text: "Qual o percentual de fornecedores críticos de IA que passaram por avaliação de risco nos últimos 12 meses?",
    description: "Quantifica a cobertura recente da avaliação de risco de fornecedores críticos.",
    objective: "Medir a abrangência da avaliação contínua de fornecedores.",
    justification: "A cobertura da avaliação indica o quão atualizada está a gestão de risco de terceiros.",
    marketReference: "ISO/IEC 27001 — A.15; BACEN Res. 4.893",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 7,
    text: "Existem planos de saída e contingência (exit strategy) para fornecedores críticos de IA?",
    description: "Avalia a preparação para transição ou substituição de fornecedores.",
    objective: "Verificar a existência de estratégias de saída de fornecedores.",
    justification: "Planos de saída garantem continuidade de negócio em caso de falha ou descontinuidade do fornecedor.",
    marketReference: "BACEN Res. 4.893; ISO/IEC 27001 — A.17",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 8,
    text: "Qual o principal critério utilizado na seleção de fornecedores de IA?",
    description: "Classifica o critério predominante na decisão de contratação.",
    objective: "Mapear o critério dominante de seleção de fornecedores.",
    justification: "Critérios de seleção excessivamente focados em preço podem negligenciar riscos e qualidade.",
    marketReference: "ISO/IEC 27001 — A.15; ITIL 4 — Supplier Management",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Custo/preço", "Capacidade técnica e qualidade", "Segurança e conformidade", "Reputação e estabilidade do fornecedor", "Avaliação multicritério equilibrada"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 9,
    text: "A organização avalia riscos na cadeia de suprimentos de IA (subcontratados, modelos de base de terceiros)?",
    description: "Avalia a visibilidade sobre riscos além do fornecedor direto (fourth parties).",
    objective: "Verificar a gestão de risco da cadeia estendida de fornecedores.",
    justification: "Riscos de subfornecedores e modelos de base podem se propagar sem visibilidade direta da organização.",
    marketReference: "ISO/IEC 27001 — A.15; MITRE ATLAS; NIST AI RMF 1.0",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 10,
    text: "Os fornecedores de IA fornecem documentação adequada sobre seus modelos (ex.: model cards, limitações, dados de treino)?",
    description: "Avalia a transparência exigida dos fornecedores sobre seus modelos.",
    objective: "Verificar o nível de transparência técnica exigido dos fornecedores.",
    justification: "A documentação dos modelos é necessária para avaliação de riscos, viés e conformidade.",
    marketReference: "EU AI Act — technical documentation; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 11,
    text: "Existe uma classificação de criticidade dos fornecedores de IA que orienta a intensidade dos controles?",
    description: "Verifica a segmentação de fornecedores por criticidade.",
    objective: "Avaliar a aplicação de controles proporcionais ao risco do fornecedor.",
    justification: "A classificação de criticidade otimiza esforços de governança sobre os fornecedores que mais importam.",
    marketReference: "ISO/IEC 27001 — A.15; BACEN Res. 4.893",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 12,
    text: "A organização tem clareza sobre como seus dados são utilizados por fornecedores de IA para treino ou melhoria de modelos?",
    description: "Avalia a transparência e o controle sobre o uso de dados corporativos pelos fornecedores.",
    objective: "Verificar o controle sobre o uso de dados por terceiros.",
    justification: "O uso indevido de dados corporativos para treino de modelos gera riscos de vazamento e conformidade.",
    marketReference: "LGPD Art. 39; ISO/IEC 27001; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 13,
    text: "Os incidentes envolvendo fornecedores de IA são registrados e considerados nas avaliações de risco subsequentes?",
    description: "Avalia a integração do histórico de incidentes à gestão de fornecedores.",
    objective: "Verificar o aprendizado com incidentes de fornecedores.",
    justification: "O histórico de incidentes é um insumo essencial para renovações e reavaliações de risco.",
    marketReference: "ISO/IEC 27001 — A.16; ITIL 4",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 14,
    text: "Há colaboração entre as áreas de compras, jurídico, segurança e negócio na gestão de fornecedores de IA?",
    description: "Avalia a integração multidisciplinar na gestão de terceiros de IA.",
    objective: "Verificar a colaboração entre áreas na gestão de fornecedores.",
    justification: "A gestão isolada por compras negligencia riscos técnicos, jurídicos e de segurança dos fornecedores.",
    marketReference: "COBIT 2019 — APO10 (Managed Vendors); ISO/IEC 27001",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "gestao-fornecedores",
    order: 15,
    text: "A organização avalia a estabilidade financeira e a viabilidade de longo prazo dos fornecedores estratégicos de IA?",
    description: "Avalia a análise de solidez e continuidade dos fornecedores críticos.",
    objective: "Verificar a consideração de risco de continuidade do fornecedor.",
    justification: "A descontinuidade de um fornecedor estratégico pode interromper serviços críticos de IA.",
    marketReference: "BACEN Res. 4.893; ISO/IEC 27001 — A.15",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },

  // ── desenvolvimento-modelos ─────────────────────────────────────────────────
  {
    domainSlug: "desenvolvimento-modelos",
    order: 1,
    text: "A organização adota uma metodologia padronizada para o desenvolvimento de modelos de IA/ML?",
    description: "Avalia a existência de um processo estruturado e repetível de desenvolvimento (ex.: CRISP-DM).",
    objective: "Verificar a padronização do processo de desenvolvimento de modelos.",
    justification: "A ausência de metodologia gera resultados inconsistentes e dificulta reprodutibilidade e auditoria.",
    marketReference: "CRISP-DM; ISO/IEC 42001; Gartner AI Maturity Model",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 2,
    text: "Os experimentos de desenvolvimento de modelos são versionados e rastreáveis (código, dados, hiperparâmetros, métricas)?",
    description: "Avalia a rastreabilidade e a reprodutibilidade dos experimentos.",
    objective: "Verificar a maturidade do rastreamento de experimentos.",
    justification: "A rastreabilidade é essencial para reprodutibilidade, auditoria e gestão de risco de modelos.",
    marketReference: "MLOps (Google MLOps maturity); ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 3,
    text: "Os modelos desenvolvidos são documentados de forma padronizada (ex.: model cards com finalidade, dados e limitações)?",
    description: "Avalia a documentação técnica dos modelos ao longo do desenvolvimento.",
    objective: "Verificar a maturidade da documentação de modelos.",
    justification: "A documentação padronizada é exigida por regulações e habilita validação, auditoria e transparência.",
    marketReference: "EU AI Act — technical documentation; ISO/IEC 42001; NIST AI RMF 1.0 — MAP",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 4,
    text: "A qualidade e a representatividade dos dados de treino são avaliadas antes do desenvolvimento dos modelos?",
    description: "Avalia a análise de adequação dos dados de treino, incluindo vieses.",
    objective: "Verificar a avaliação de dados como insumo do desenvolvimento.",
    justification: "Dados inadequados ou enviesados comprometem o desempenho e a equidade dos modelos resultantes.",
    marketReference: "DAMA-DMBOK; ISO/IEC 23894; NIST AI RMF 1.0 — MAP",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 5,
    text: "Existem padrões de codificação, revisão por pares (code review) e boas práticas de engenharia aplicados ao desenvolvimento de modelos?",
    description: "Avalia a disciplina de engenharia de software no desenvolvimento de IA.",
    objective: "Verificar a aplicação de boas práticas de engenharia.",
    justification: "Práticas de engenharia reduzem defeitos, melhoram a manutenibilidade e a qualidade dos modelos.",
    marketReference: "MLOps; ISO/IEC 25010; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 6,
    text: "A organização avalia e mitiga vieses (bias) durante o desenvolvimento dos modelos?",
    description: "Avalia a incorporação de fairness ao ciclo de desenvolvimento.",
    objective: "Verificar a gestão de viés e equidade no desenvolvimento.",
    justification: "Modelos enviesados geram decisões discriminatórias com riscos legais, reputacionais e regulatórios.",
    marketReference: "ISO/IEC 24027; NIST AI RMF 1.0 — MEASURE; EU AI Act",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 7,
    text: "Qual a abordagem predominante da organização para a origem dos modelos de IA utilizados?",
    description: "Classifica a estratégia dominante de obtenção de modelos.",
    objective: "Mapear o modelo de sourcing de modelos de IA.",
    justification: "A origem dos modelos impacta requisitos de governança, custo e controle sobre o ciclo de vida.",
    marketReference: "Gartner AI Maturity Model; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "multiple_choice",
    options: ["Desenvolvimento próprio do zero", "Fine-tuning de modelos pré-treinados", "Uso de modelos de terceiros via API", "Modelos open source adaptados", "Combinação de abordagens"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 8,
    text: "Qual o percentual de modelos desenvolvidos que possui documentação completa antes de seguir para validação?",
    description: "Quantifica a cobertura de documentação no pipeline de desenvolvimento.",
    objective: "Medir a disciplina de documentação prévia à validação.",
    justification: "Modelos sem documentação completa comprometem a validação independente e a rastreabilidade.",
    marketReference: "ISO/IEC 42001; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 9,
    text: "A segurança é incorporada ao desenvolvimento de modelos (ex.: proteção contra data poisoning e testes adversariais)?",
    description: "Avalia a integração de segurança ao ciclo de desenvolvimento (security by design).",
    objective: "Verificar a incorporação de segurança no desenvolvimento de modelos.",
    justification: "Ameaças como envenenamento de dados comprometem a integridade dos modelos desde o treino.",
    marketReference: "MITRE ATLAS; OWASP Top 10 for LLM; NIST AI RMF 1.0",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 10,
    text: "Existe um ambiente de desenvolvimento padronizado e reprodutível para os times de modelagem?",
    description: "Avalia a padronização de ambientes e ferramentas de desenvolvimento.",
    objective: "Verificar a reprodutibilidade dos ambientes de desenvolvimento.",
    justification: "Ambientes não padronizados geram inconsistências e problemas de reprodutibilidade entre times.",
    marketReference: "MLOps; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 11,
    text: "Os requisitos de negócio e as métricas de sucesso são definidos formalmente antes do início do desenvolvimento?",
    description: "Avalia o alinhamento de requisitos na fase inicial do desenvolvimento.",
    objective: "Verificar a clareza de requisitos e critérios de sucesso.",
    justification: "Requisitos mal definidos levam a modelos tecnicamente corretos mas irrelevantes ao negócio.",
    marketReference: "CRISP-DM; COBIT 2019 — BAI03",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 12,
    text: "A organização reutiliza componentes, features e modelos (ex.: feature store, repositório de modelos) entre projetos?",
    description: "Avalia a existência de ativos reutilizáveis no desenvolvimento.",
    objective: "Verificar a maturidade do reuso de ativos de modelagem.",
    justification: "O reuso de ativos acelera o desenvolvimento e melhora a consistência entre modelos.",
    marketReference: "MLOps; DAMA-DMBOK",
    criticality: "baixa",
    weight: 2,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 13,
    text: "As decisões de design dos modelos (escolha de algoritmo, trade-offs) são registradas e justificadas?",
    description: "Avalia o registro do racional das decisões técnicas de modelagem.",
    objective: "Verificar a rastreabilidade das decisões de design.",
    justification: "O registro das decisões apoia auditoria, explicabilidade e manutenção futura dos modelos.",
    marketReference: "ISO/IEC 42001; EU AI Act",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 14,
    text: "Os requisitos de explicabilidade (interpretabilidade) são considerados na escolha e no desenvolvimento dos modelos?",
    description: "Avalia a incorporação de explicabilidade desde o design do modelo.",
    objective: "Verificar a consideração de explicabilidade no desenvolvimento.",
    justification: "A explicabilidade é exigida em setores regulados para justificar decisões automatizadas a clientes e reguladores.",
    marketReference: "EU AI Act; BACEN; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "desenvolvimento-modelos",
    order: 15,
    text: "Descreva as principais ferramentas e frameworks utilizados no desenvolvimento de modelos de IA na organização.",
    description: "Campo aberto para mapear o stack tecnológico de desenvolvimento.",
    objective: "Coletar informações sobre o ecossistema de ferramentas de modelagem.",
    justification: "Conhecer o stack revela o nível de padronização e a maturidade tecnológica do desenvolvimento.",
    marketReference: "MLOps; Gartner AI Maturity Model",
    criticality: "baixa",
    weight: 1,
    answerType: "text",
    required: false,
    eliminatory: false,
  },

  // ── validacao-modelos ───────────────────────────────────────────────────────
  {
    domainSlug: "validacao-modelos",
    order: 1,
    text: "Existe uma função de validação independente de modelos, segregada da equipe de desenvolvimento?",
    description: "Avalia a segregação de funções entre quem desenvolve e quem valida os modelos.",
    objective: "Verificar a independência da validação de modelos.",
    justification: "A validação independente é princípio central do model risk management e reduz vieses de autoavaliação.",
    marketReference: "SR 11-7 (Model Risk Management); BACEN; ISO/IEC 42001",
    criticality: "critica",
    weight: 5,
    answerType: "scale_1_5",
    required: true,
    eliminatory: true,
  },
  {
    domainSlug: "validacao-modelos",
    order: 2,
    text: "Existe um processo formal de aprovação de modelos antes de sua implantação em produção?",
    description: "Avalia a existência de gates de aprovação formal para produção.",
    objective: "Verificar a formalização da aprovação de modelos.",
    justification: "A aprovação formal garante que modelos só entrem em produção após validação e aceite de risco.",
    marketReference: "SR 11-7; ISO/IEC 42001; NIST AI RMF 1.0 — GOVERN",
    criticality: "alta",
    weight: 5,
    answerType: "yes_no",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 3,
    text: "A validação avalia o desempenho dos modelos em dados representativos e cenários de estresse?",
    description: "Avalia a abrangência dos testes de desempenho na validação.",
    objective: "Verificar a robustez dos testes de desempenho na validação.",
    justification: "Testes limitados não revelam falhas de desempenho em condições reais e extremas.",
    marketReference: "SR 11-7; NIST AI RMF 1.0 — MEASURE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 4,
    text: "A validação verifica conceitualmente a adequação da abordagem, premissas e limitações do modelo?",
    description: "Avalia a validação conceitual (soundness) além dos testes empíricos.",
    objective: "Verificar a profundidade da validação conceitual.",
    justification: "A validação conceitual identifica premissas inadequadas que testes empíricos podem não capturar.",
    marketReference: "SR 11-7; ISO/IEC 42001",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 5,
    text: "A validação avalia riscos de viés, equidade e conformidade regulatória dos modelos?",
    description: "Avalia a inclusão de dimensões éticas e regulatórias na validação.",
    objective: "Verificar a cobertura de fairness e conformidade na validação.",
    justification: "A validação de viés e conformidade é exigida por reguladores e mitiga riscos legais e reputacionais.",
    marketReference: "EU AI Act; ISO/IEC 24027; NIST AI RMF 1.0 — MEASURE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 6,
    text: "Existe um inventário de modelos com sua classificação de risco e status de validação atualizado?",
    description: "Avalia a manutenção de um inventário de modelos com estado de validação.",
    objective: "Verificar a gestão do inventário de modelos validados.",
    justification: "Um inventário atualizado é base do model risk management e da supervisão regulatória.",
    marketReference: "SR 11-7; ISO/IEC 42001; BACEN",
    criticality: "alta",
    weight: 4,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 7,
    text: "Qual o percentual de modelos em produção que passou por validação independente formal?",
    description: "Quantifica a cobertura da validação no parque de modelos em produção.",
    objective: "Medir a abrangência da validação independente.",
    justification: "Modelos em produção sem validação representam risco não gerenciado e potencial não conformidade.",
    marketReference: "SR 11-7; BACEN",
    criticality: "alta",
    weight: 4,
    answerType: "percent",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 8,
    text: "Os modelos são revalidados periodicamente e após mudanças significativas de dados ou contexto?",
    description: "Avalia a existência de revalidação recorrente e orientada a eventos.",
    objective: "Verificar a maturidade da revalidação de modelos.",
    justification: "Modelos degradam com o tempo (drift); a revalidação periódica mantém a confiabilidade das decisões.",
    marketReference: "SR 11-7; NIST AI RMF 1.0 — MANAGE",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: true,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 9,
    text: "Como a organização trata modelos identificados como de alto risco durante a validação?",
    description: "Classifica a abordagem para modelos de alto risco na validação.",
    objective: "Mapear o tratamento de modelos de alto risco.",
    justification: "O tratamento adequado de modelos de alto risco é essencial para conformidade e mitigação de danos.",
    marketReference: "EU AI Act — high-risk systems; SR 11-7",
    criticality: "alta",
    weight: 4,
    answerType: "multiple_choice",
    options: ["Controles adicionais e supervisão humana reforçada", "Aprovação por instância superior de governança", "Monitoramento intensivo em produção", "Restrição ou proibição de uso", "Não há tratamento diferenciado"],
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 10,
    text: "As conclusões e recomendações da validação são formalmente documentadas e comunicadas aos decisores?",
    description: "Avalia a documentação e a comunicação dos resultados de validação.",
    objective: "Verificar a formalização dos resultados de validação.",
    justification: "A documentação dos resultados sustenta decisões de aprovação e evidencia diligência a reguladores.",
    marketReference: "SR 11-7; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 11,
    text: "Existem limiares e critérios de aceitação predefinidos que orientam a aprovação ou rejeição de modelos?",
    description: "Avalia a objetividade dos critérios de aprovação de modelos.",
    objective: "Verificar a existência de critérios de aceitação claros.",
    justification: "Critérios predefinidos evitam decisões subjetivas e tornam a validação consistente e auditável.",
    marketReference: "SR 11-7; NIST AI RMF 1.0 — MEASURE",
    criticality: "media",
    weight: 3,
    answerType: "yes_no",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 12,
    text: "As restrições de uso e limitações identificadas na validação são registradas e comunicadas aos usuários dos modelos?",
    description: "Avalia a comunicação de limitações de uso aprovado dos modelos.",
    objective: "Verificar a gestão das restrições de uso dos modelos.",
    justification: "O uso de modelos fora de suas condições validadas gera decisões inadequadas e riscos não gerenciados.",
    marketReference: "SR 11-7; EU AI Act; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 13,
    text: "Os modelos de fornecedores e de terceiros (incluindo modelos de base) também passam por validação da organização?",
    description: "Avalia a extensão da validação a modelos não desenvolvidos internamente.",
    objective: "Verificar a cobertura da validação sobre modelos de terceiros.",
    justification: "A responsabilidade pelo risco do modelo permanece com a organização mesmo quando o modelo é externo.",
    marketReference: "SR 11-7; ISO/IEC 42001; BACEN Res. 4.893",
    criticality: "alta",
    weight: 4,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 14,
    text: "A função de validação possui recursos, competências e independência suficientes para exercer seu papel?",
    description: "Avalia a capacidade e a autonomia efetiva da função de validação.",
    objective: "Verificar a adequação de recursos e independência da validação.",
    justification: "Uma validação subdimensionada ou sem independência real não mitiga efetivamente o risco de modelos.",
    marketReference: "SR 11-7; COBIT 2019 — MEA02",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
  {
    domainSlug: "validacao-modelos",
    order: 15,
    text: "As auditorias interna e externa avaliam periodicamente o processo de validação e gestão de risco de modelos?",
    description: "Avalia a supervisão de terceira linha sobre o processo de validação.",
    objective: "Verificar a existência de auditoria sobre o model risk management.",
    justification: "A auditoria independente assegura a eficácia e a conformidade contínua do processo de validação.",
    marketReference: "SR 11-7; COBIT 2019 — MEA02; ISO/IEC 42001",
    criticality: "media",
    weight: 3,
    answerType: "scale_1_5",
    required: false,
    eliminatory: false,
  },
];
